(function(global){
'use strict';
const FEATURES = [
 ['alive','Is it alive?'],['person','Is it a person?'],['animal','Is it an animal?'],['plant','Is it a plant?'],['place','Is it a place?'],['food','Is it food?'],['drink','Is it a drink?'],['manmade','Is it man-made?'],['indoors','Is it usually found indoors?'],['outdoors','Is it usually found outdoors?'],['household','Would you find it in a home?'],['kitchen','Would you find it in a kitchen?'],['bedroom','Would you keep it in a bedroom?'],['bathroom','Would you find it in a bathroom?'],['wearable','Can you wear it?'],['electronic','Does it use electricity?'],['battery','Does it need batteries?'],['screen','Does it have a screen?'],['wheels','Does it have wheels?'],['vehicle','Is it a vehicle?'],['fly','Can it fly?'],['swim','Can it swim?'],['pet','Is it commonly kept as a pet?'],['farm','Would you find it on a farm?'],['wild','Does it usually live in the wild?'],['danger','Could it hurt you?'],['big','Is it bigger than an adult human?'],['handheld','Can you hold it in one hand?'],['soft','Is it soft to the touch?'],['fragile','Does it break easily?'],['metal','Is it mostly made of metal?'],['wood','Is it mostly made of wood?'],['paper','Is it mostly made of paper?'],['plastic','Is it mostly made of plastic?'],['edible','Can you eat it?'],['sweet','Is it usually sweet?'],['salty','Is it usually salty?'],['hot','Is it usually served or used hot?'],['cold','Is it usually cold?'],['liquid','Is it a liquid?'],['round','Is it round?'],['handle','Does it have a handle?'],['opens','Does it open and close?'],['sound','Does it make a sound by itself?'],['light','Does it give off light?'],['tool','Is it a tool?'],['toy','Is it mainly used for play?'],['school','Would you commonly find it at school?'],['work','Would you commonly find it at a workplace?'],['sports','Is it related to sports?'],['music','Is it related to music?'],['communication','Is it used to communicate?'],['cleaning','Is it used for cleaning?'],['furniture','Is it furniture?'],['clothing','Is it clothing?'],['nature','Is it part of nature?'],['water','Is it strongly associated with water?'],['legs','Does it have legs?'],['fur','Does it have fur or hair?'],['bird','Is it a bird?'],['insect','Is it an insect or bug?'],['mammal','Is it a mammal?'],
 ['fruit','Is it a fruit?'],['vegetable','Is it a vegetable?'],['baked','Is it baked?'],['dairy','Is it a dairy food?'],['meat','Is it meat?'],['dessert','Is it a dessert?'],['frozen','Is it usually frozen?'],['caffeinated','Does it usually contain caffeine?'],['appliance','Is it an appliance?'],['container','Is it mainly used to hold things?'],['cutting','Is it used for cutting?'],['writing','Is it used for writing or drawing?'],['reading','Is it mainly for reading?'],['computer','Is it a kind of computer?'],['phone','Is it a phone?'],['road','Does it usually travel on roads?'],['rail','Does it travel on rails?'],['air','Does it travel through the air?'],['sea','Does it travel on water?'],['public','Is it commonly shared with strangers?'],['building','Is it a building?'],['naturalPlace','Is it a natural place?'],['medical','Is it strongly associated with medicine or health care?'],['profession','Is it a kind of job or profession?'],['fire','Is it associated with fire?'],['striped','Does it usually have stripes?'],['fallingWater','Does the water fall downward?'],['citrus','Is it citrus-based?'],['berry','Is it a berry?'],['rootVeg','Is it a root vegetable?'],['leafyVeg','Is it a leafy or flowering vegetable?'],['coffeeBased','Is it made from coffee beans?'],['teaBased','Is it made from tea leaves?'],['lemonBased','Is it made from lemons?'],['headRest','Do you rest your head on it?'],['prongs','Does it have prongs?'],['scoop','Is it shaped for scooping?'],['upperBody','Is it worn on your upper body?'],['legwear','Is it worn mainly on your legs?'],['footwear','Is it worn on your feet?'],['hardSole','Does it usually have a hard sole?'],['shopping','Do people mainly go there to shop?'],['preparedFood','Do people mainly go there to eat prepared food?'],['prescribe','Can this profession prescribe medicine in many places?']
].map(([id,q])=>({id,q,label:id}));

const B={
 animal:['alive','animal','wild','outdoors'], pet:['alive','animal','pet','household'], food:['food','edible','kitchen','household','handheld'], drink:['drink','edible','liquid','kitchen','household'], household:['manmade','indoors','household'], tech:['manmade','electronic','indoors'], place:['place'], person:['alive','person','profession'], vehicle:['manmade','vehicle','big']
};
const O=[];
function add(name, base, yes=[], maybe=[], article){O.push({name,article,yes:[...(B[base]||[]),...yes],maybe});}
// Animals
add('Dog','pet',['mammal','fur','legs','sound','swim']); add('Cat','pet',['mammal','fur','legs','sound','soft']); add('Horse','animal',['mammal','fur','legs','farm','big','sports']); add('Cow','animal',['mammal','fur','legs','farm','big']); add('Pig','animal',['mammal','legs','farm','sound']); add('Sheep','animal',['mammal','fur','legs','farm','soft']); add('Elephant','animal',['mammal','legs','big','danger','water']); add('Lion','animal',['mammal','fur','legs','big','danger']); add('Tiger','animal',['mammal','fur','legs','big','danger','swim','striped']); add('Bear','animal',['mammal','fur','legs','big','danger','swim']); add('Monkey','animal',['mammal','fur','legs','sound']); add('Rabbit','animal',['mammal','fur','legs','soft'],['pet']); add('Mouse','animal',['mammal','fur','legs','handheld'],['pet','indoors']); add('Whale','animal',['mammal','swim','water','big','sound']); add('Dolphin','animal',['mammal','swim','water','sound']); add('Shark','animal',['swim','water','big','danger']); add('Goldfish','pet',['swim','water','handheld']); add('Eagle','animal',['bird','fly','legs','danger']); add('Owl','animal',['bird','fly','legs','sound']); add('Penguin','animal',['bird','swim','water','legs']); add('Chicken','animal',['bird','farm','legs','food','edible']); add('Duck','animal',['bird','swim','water','fly','legs'],['farm']); add('Butterfly','animal',['insect','fly','legs','handheld']); add('Bee','animal',['insect','fly','legs','danger','sound','handheld']); add('Spider','animal',['insect','legs','danger','handheld'],['indoors']); add('Snake','animal',['danger','swim','handheld']); add('Frog','animal',['swim','water','legs','handheld']);
// Plants/nature
add('Oak tree','animal',['plant','alive','nature','big','wood'],[],undefined); O[O.length-1].yes=O[O.length-1].yes.filter(x=>x!=='animal'&&x!=='wild'); add('Rose','animal',['plant','alive','nature','handheld','soft'],['danger']); O[O.length-1].yes=O[O.length-1].yes.filter(x=>x!=='animal'&&x!=='wild'); add('Cactus','animal',['plant','alive','nature','handheld','danger'],['indoors']); O[O.length-1].yes=O[O.length-1].yes.filter(x=>x!=='animal'&&x!=='wild'); add('Grass','animal',['plant','alive','nature','soft'],[], ''); O[O.length-1].yes=O[O.length-1].yes.filter(x=>x!=='animal'&&x!=='wild'); add('Sunflower','animal',['plant','alive','nature','handheld','round'],[],undefined); O[O.length-1].yes=O[O.length-1].yes.filter(x=>x!=='animal'&&x!=='wild');
add('Sun','place',['nature','outdoors','big','round','light','hot'],[], 'the'); add('Moon','place',['nature','outdoors','big','round','light'],[], 'the'); add('Mountain','place',['nature','naturalPlace','outdoors','big','danger']); add('River','place',['nature','naturalPlace','outdoors','water','liquid','big']); add('Ocean','place',['nature','naturalPlace','outdoors','water','liquid','big','danger']); add('Beach','place',['nature','naturalPlace','outdoors','water']); add('Forest','place',['nature','naturalPlace','outdoors','big']); add('Waterfall','place',['nature','naturalPlace','outdoors','water','liquid','big','fallingWater']);
// Food and drink
add('Apple','food',['fruit','sweet','round']); add('Banana','food',['fruit','sweet','soft']); add('Orange','food',['fruit','sweet','round','citrus']); add('Strawberry','food',['fruit','sweet','soft','berry']); add('Watermelon','food',['fruit','sweet','round','big']); add('Carrot','food',['vegetable','rootVeg']); add('Broccoli','food',['vegetable','leafyVeg']); add('Potato','food',['vegetable','round']); add('Bread','food',['baked','soft'],[], ''); add('Cheese','food',['dairy','salty','soft'],[], ''); add('Egg','food',['round','fragile']); add('Chicken dinner','food',['meat','salty','hot']); add('Hamburger','food',['meat','salty','hot','soft']); add('Pizza','food',['baked','dairy','salty','hot','round']); add('Pasta','food',['salty','hot','soft'],[], ''); add('Soup','food',['hot','liquid','container']); add('Ice cream','food',['dairy','sweet','dessert','frozen','cold','soft'],[], ''); add('Cake','food',['baked','sweet','dessert','soft']); add('Cookie','food',['baked','sweet','dessert','round']); add('Chocolate','food',['sweet','dessert','soft'],[], ''); add('Popcorn','food',['salty'],[], ''); add('Sandwich','food',['soft']); add('Coffee','drink',['hot','caffeinated','coffeeBased'],[], ''); add('Tea','drink',['hot','caffeinated','teaBased'],[], ''); add('Milk','drink',['cold','dairy'],[], ''); add('Orange juice','drink',['cold','fruit','sweet','citrus'],[], ''); add('Lemonade','drink',['cold','fruit','sweet','citrus','lemonBased'],[], ''); add('Water','drink',['cold','water'],[], '');
// Household/furniture/appliances
add('Chair','household',['furniture','wood','legs']); add('Table','household',['furniture','wood','legs','big']); add('Couch','household',['furniture','soft','big']); add('Bed','household',['furniture','soft','big','bedroom']); add('Desk','household',['furniture','wood','work','school','legs']); add('Bookshelf','household',['furniture','wood','big','reading']); add('Lamp','household',['electronic','light','fragile']); add('Clock','household',['round','sound'],['electronic','battery']); add('Mirror','household',['fragile','bathroom','bedroom']); add('Pillow','household',['soft','bedroom','headRest']); add('Blanket','household',['soft','bedroom']); add('Towel','household',['soft','bathroom']); add('Toothbrush','household',['bathroom','handheld','plastic','cleaning']); add('Soap','household',['bathroom','handheld','cleaning'],[], ''); add('Vacuum cleaner','household',['electronic','cleaning','sound','handle','wheels']); add('Broom','household',['cleaning','handle','wood']); add('Mop','household',['cleaning','handle','water']); add('Bucket','household',['container','handle','plastic','water']); add('Refrigerator','household',['kitchen','appliance','electronic','cold','big','opens']); add('Oven','household',['kitchen','appliance','electronic','hot','big','opens']); add('Microwave','household',['kitchen','appliance','electronic','hot','opens']); add('Toaster','household',['kitchen','appliance','electronic','hot']); add('Blender','household',['kitchen','appliance','electronic','sound','container']); add('Kettle','household',['kitchen','appliance','electronic','hot','handle','container']); add('Frying pan','household',['kitchen','metal','hot','handle','container']); add('Pot','household',['kitchen','metal','hot','handle','container','round']); add('Plate','household',['kitchen','fragile','round']); add('Mug','household',['kitchen','fragile','handle','container']); add('Glass','household',['kitchen','fragile','container'],[], ''); add('Fork','household',['kitchen','metal','handheld','prongs']); add('Spoon','household',['kitchen','metal','handheld','scoop']); add('Kitchen knife','household',['kitchen','metal','handheld','tool','cutting','danger']); add('Scissors','household',['metal','handheld','tool','cutting','danger','school'],[], ''); add('Tupperware container','household',['kitchen','plastic','container','opens']);
// Tech / tools / school / recreation
add('Smartphone','tech',['battery','screen','handheld','communication','phone','computer','fragile']); add('Laptop','tech',['battery','screen','computer','communication','work','school','fragile']); add('Tablet','tech',['battery','screen','handheld','computer','communication','fragile']); add('Desktop computer','tech',['screen','computer','communication','work','big']); add('Television','tech',['screen','sound','big']); add('Camera','tech',['battery','screen','handheld','fragile']); add('Headphones','tech',['battery','sound','music','handheld'],['communication']); add('Radio','tech',['sound','music','communication']); add('Flashlight','tech',['battery','light','handheld']); add('Remote control','tech',['battery','handheld']); add('Video game controller','tech',['battery','handheld','toy']); add('Printer','tech',['paper','work','school','big']); add('Calculator','tech',['battery','screen','handheld','school','work']); add('Hammer','household',['tool','handheld','metal','wood','danger']); add('Screwdriver','household',['tool','handheld','metal','plastic']); add('Drill','tech',['battery','tool','handheld','sound','danger']); add('Saw','household',['tool','handheld','cutting','danger','metal']); add('Tape measure','household',['tool','handheld']); add('Pencil','household',['handheld','writing','school','wood']); add('Pen','household',['handheld','writing','school','plastic']); add('Notebook','household',['paper','writing','reading','school']); add('Book','household',['paper','reading','school'],[],undefined); add('Backpack','household',['container','school','wearable','soft']); add('Soccer ball','household',['toy','sports','round','soft','outdoors']); add('Basketball','household',['toy','sports','round','sound']); add('Tennis racket','household',['sports','handheld']); add('Guitar','household',['music','sound','wood','handheld']); add('Piano','household',['music','sound','big','wood']); add('Drum','household',['music','sound','round','big']);
// Clothing
add('T-shirt','household',['wearable','clothing','soft','upperBody']); add('Jeans','household',['wearable','clothing','soft','legwear']); add('Jacket','household',['wearable','clothing','soft','outdoors','upperBody']); add('Shoes','household',['wearable','clothing','footwear','hardSole'],[], ''); add('Hat','household',['wearable','clothing','handheld']); add('Gloves','household',['wearable','clothing','soft','handheld'],[], ''); add('Socks','household',['wearable','clothing','soft','footwear'],[], '');
// Transport
add('Car','vehicle',['wheels','road','metal','opens']); add('Bus','vehicle',['wheels','road','metal','public']); add('Bicycle','vehicle',['wheels','road','metal','sports']); add('Motorcycle','vehicle',['wheels','road','metal','sports','danger']); add('Train','vehicle',['wheels','rail','metal','public']); add('Airplane','vehicle',['fly','air','metal','public']); add('Helicopter','vehicle',['fly','air','metal','sound']); add('Boat','vehicle',['swim','sea','water'],['wood','metal']); add('Ship','vehicle',['swim','sea','water','metal','public','big']);
// Places/buildings
add('House','place',['manmade','building','indoors','household','big']); add('School','place',['manmade','building','indoors','school','public','big']); add('Hospital','place',['manmade','building','indoors','medical','public','big']); add('Library','place',['manmade','building','indoors','reading','public','big']); add('Restaurant','place',['manmade','building','indoors','food','public','big','preparedFood']); add('Grocery store','place',['manmade','building','indoors','food','public','big','shopping']); add('Park','place',['manmade','outdoors','nature','public','big']); add('Airport','place',['manmade','building','indoors','air','public','big']); add('Train station','place',['manmade','building','indoors','rail','public','big']); add('Office','place',['manmade','building','indoors','work','public','big']);
// People/professions
add('Teacher','person',['school','work','communication']); add('Doctor','person',['medical','work','communication','prescribe']); add('Nurse','person',['medical','work','communication']); add('Firefighter','person',['fire','work','danger']); add('Police officer','person',['work','danger','communication']); add('Chef','person',['work','kitchen','food']); add('Musician','person',['work','music','sound']); add('Athlete','person',['work','sports']); add('Pilot','person',['work','air','fly']); add('Farmer','person',['work','farm','outdoors']);

const seen=new Set();
for(const o of O){o.yes=[...new Set(o.yes)];o.maybe=[...new Set(o.maybe||[])];const k=o.name.toLowerCase();if(seen.has(k))throw new Error('duplicate object '+o.name);seen.add(k);}
global.MOM_KNOWLEDGE={FEATURES,OBJECTS:O};
if(typeof module!=='undefined')module.exports=global.MOM_KNOWLEDGE;
})(typeof window!=='undefined'?window:globalThis);
