// Dataset v4 additions (original, hand-written data; no third-party association norms).
//
// Why: the engine-2.3 vocabulary audit. Words real players type in Solo games (business, cubicle,
// heat, sunny, nap, cage, crate, destination, gravy, roasted, squash, puree, liquid) and a
// systematic sweep of everyday words (household objects, work and jobs, school, food, places,
// travel, animals, holidays, activities, descriptive words, basic abstract ideas) were either not
// understood or were misread from a piece of the word (hotel → hot, passport → sport, alarm → arm,
// friendship → friend + ship, garbage → garage). An unknown word leaves the bot answering only the
// other word, which reads as ignoring the player, and a misread word is worse. These rows add the
// words with ordinary, familiar links (the first links are what most people would think of first).
// Same row shape as data.js: [id, englishLabel, frenchLabel, tags, links].
//
// "vacation" was an alias of "holiday" (which here means a festive holiday: Christmas, Easter), so
// vacation + farm read as holiday + farm and led to TURKEY. It is now its own concept (beach, trip).

export const DATASET_VERSION = "lexicon-4";

export const ADDED_CONCEPTS_4 = [
  // Work and jobs
  ["business", "business", "les affaires", ["job", "city"], ["work", "office", "money", "boss", "meeting", "job", "suit", "shop", "bank"]],
  ["coworker", "coworker", "collègue", ["job"], ["work", "office", "boss", "meeting", "job", "team", "friend", "lunch"]],
  ["employee", "employee", "employé", ["job"], ["work", "boss", "job", "office", "salary", "coworker", "shop", "uniform"]],
  ["salary", "salary", "salaire", ["job"], ["money", "work", "job", "bank", "boss", "pay"]],
  ["interview", "interview", "entretien", ["job"], ["job", "work", "boss", "question", "office", "suit", "nervous"]],
  ["deadline", "deadline", "date limite", ["job", "time"], ["work", "homework", "late", "calendar", "boss", "office", "hurry"]],
  ["email", "email", "e-mail", ["tech", "job"], ["computer", "message", "letter", "phone", "work", "office", "internet"]],
  ["printer", "printer", "imprimante", ["tech", "job"], ["paper", "computer", "office", "ink", "desk"]],
  ["folder", "folder", "dossier", ["school", "job"], ["paper", "office", "desk", "computer", "school", "report"]],
  ["report", "report", "rapport", ["school", "job"], ["work", "school", "paper", "boss", "grade", "office"]],
  ["presentation", "presentation", "présentation", ["job", "school"], ["meeting", "work", "office", "screen", "talk", "school"]],
  ["lawyer", "lawyer", "juriste", ["job"], ["judge", "suit", "office", "police", "money"]],
  ["judge", "judge", "juge", ["job"], ["lawyer", "police", "rule", "hammer"]],
  ["accountant", "accountant", "comptable", ["job"], ["money", "number", "office", "math", "work", "boss", "calculator"]],
  ["calculator", "calculator", "calculatrice", ["school", "tech"], ["math", "number", "school", "accountant", "count"]],
  ["engineer", "engineer", "ingénieur", ["job", "science"], ["build", "machine", "bridge", "science", "computer", "math"]],
  ["programmer", "programmer", "programmeur", ["job", "tech"], ["computer", "work", "office", "screen", "keyboard"]],
  ["mechanic", "mechanic", "mécanicien", ["job", "transport"], ["car", "tool", "fix", "garage", "wheel", "engine", "truck"]],
  ["plumber", "plumber", "plombier", ["job", "home"], ["water", "sink", "toilet", "bathroom", "fix", "tool"]],
  ["carpenter", "carpenter", "menuisier", ["job"], ["wood", "hammer", "nail", "build", "tool", "table", "chair"]],
  ["electrician", "electrician", "électricien", ["job"], ["electricity", "light", "lamp", "fix", "tool", "battery"]],
  ["cashier", "cashier", "caissier", ["job", "city"], ["shop", "money", "market", "pay", "bag"]],
  ["librarian", "librarian", "bibliothécaire", ["job", "book"], ["library", "book", "read", "quiet", "school", "story"]],
  ["janitor", "janitor", "concierge", ["job", "school"], ["clean", "broom", "mop", "school", "trash", "bucket", "vacuum"]],
  ["secretary", "secretary", "secrétaire", ["job"], ["office", "phone", "desk", "boss", "email", "meeting", "calendar"]],
  ["singer", "singer", "chanteur", ["job", "music"], ["sing", "song", "music", "stage", "concert", "band"]],
  ["dancer", "dancer", "danseur", ["job", "music"], ["dance", "ballet", "music", "stage", "show"]],
  ["actor", "actor", "acteur", ["job", "art"], ["movie", "theater", "stage", "show", "star", "tv", "costume"]],
  ["writer", "writer", "écrivain", ["job", "book"], ["book", "write", "story", "pen", "paper", "library"]],
  ["driver", "driver", "conducteur", ["job", "transport"], ["car", "bus", "taxi", "truck", "drive", "road"]],
  ["lifeguard", "lifeguard", "maître-nageur", ["job", "water"], ["beach", "pool", "swim", "ocean", "whistle", "help"]],
  ["referee", "referee", "arbitre", ["job", "sport"], ["whistle", "soccer", "game", "sport", "team", "rule"]],
  ["coach", "coach", "entraîneur", ["job", "sport"], ["team", "sport", "player", "whistle", "win", "game"]],
  ["gardener", "gardener", "jardinier", ["job", "plant"], ["garden", "flower", "plant", "grow", "tree", "shovel", "grass"]],
  ["butcher", "butcher", "boucher", ["job", "food"], ["meat", "knife", "shop", "steak", "sausage"]],
  ["factory", "factory", "usine", ["job", "city"], ["work", "machine", "build", "car", "smoke", "robot"]],
  ["busy", "busy", "occupé", ["job", "city"], ["work", "city", "office", "bee", "traffic", "boss", "week"]],

  // School
  ["principal", "principal", "directeur d’école", ["school", "job"], ["school", "teacher", "office", "student", "class", "boss"]],
  ["cafeteria", "cafeteria", "cantine", ["school", "food"], ["lunch", "school", "food", "tray", "table", "student"]],
  ["gym", "gym", "salle de sport", ["sport", "school"], ["sport", "exercise", "muscle", "run", "basketball", "school", "strong"]],
  ["exercise", "exercise", "exercice", ["sport", "body"], ["gym", "run", "sport", "muscle", "strong", "jog"]],
  ["locker", "locker", "casier", ["school", "sport"], ["school", "key", "backpack", "gym", "door", "student"]],
  ["grade", "grade", "note scolaire", ["school"], ["school", "test", "teacher", "report", "student", "class", "math"]],
  ["lunchbox", "lunchbox", "boîte à goûter", ["school", "food"], ["lunch", "school", "sandwich", "snack", "backpack", "apple"]],
  ["study", "study", "étudier", ["school"], ["school", "homework", "test", "book", "learn", "read", "student", "library"]],
  ["university", "university", "université", ["school", "city"], ["school", "student", "study", "class", "book", "city"]],
  ["question", "question", "question", ["school"], ["answer", "test", "teacher", "interview", "school"]],
  ["answer", "answer", "réponse", ["school"], ["question", "test", "math", "teacher", "school"]],
  ["idea", "idea", "idée", ["school"], ["brain", "lightbulb", "think", "dream", "smart"]],
  ["think", "think", "penser", ["school"], ["brain", "idea", "dream", "learn", "smart"]],
  ["smart", "smart", "intelligent", ["school"], ["brain", "school", "owl", "teacher", "scientist", "idea", "book"]],
  ["sticker", "sticker", "autocollant", ["school", "toy"], ["paper", "notebook", "star", "school", "sticky"]],
  ["diary", "diary", "journal intime", ["book"], ["secret", "write", "book", "notebook", "pen", "day"]],
  ["ink", "ink", "encre", ["school", "art"], ["pen", "octopus", "squid", "paper", "write", "printer", "black"]],

  // Travel and places
  ["vacation", "vacation", "vacances d’été", ["travel", "holiday"], ["beach", "travel", "trip", "summer", "hotel", "plane", "suitcase", "relax", "island", "sun"]],
  ["trip", "trip", "excursion", ["travel"], ["travel", "vacation", "car", "plane", "suitcase", "map", "road", "bus", "adventure"]],
  ["hotel", "hotel", "hôtel", ["travel", "city"], ["vacation", "room", "bed", "trip", "travel", "pool", "key", "city"]],
  ["passport", "passport", "passeport", ["travel"], ["travel", "airport", "plane", "trip", "vacation", "ticket", "photo", "country"]],
  ["tourist", "tourist", "touriste", ["travel"], ["travel", "vacation", "camera", "map", "city", "museum", "trip", "hotel"]],
  ["souvenir", "souvenir", "souvenir", ["travel"], ["trip", "vacation", "gift", "shop", "travel", "memory"]],
  ["cruise", "cruise", "croisière", ["travel", "ocean"], ["ship", "boat", "sea", "ocean", "vacation", "island", "travel"]],
  ["country", "country", "pays", ["travel"], ["world", "map", "flag", "city", "travel", "france", "language", "king"]],
  ["village", "village", "village", ["city"], ["farm", "home", "church", "small", "country", "city"]],
  ["mall", "mall", "centre commercial", ["city"], ["shop", "buy", "money", "clothes", "city", "food"]],
  ["bank", "bank", "banque", ["city"], ["money", "gold", "coin", "pay", "city", "salary"]],
  ["apartment", "apartment", "appartement", ["home", "city"], ["home", "city", "building", "room", "stairs", "neighbor"]],
  ["building", "building", "immeuble", ["city"], ["city", "tower", "office", "apartment", "stairs", "build", "roof"]],
  ["neighbor", "neighbor", "voisin", ["home", "family"], ["home", "street", "friend", "apartment", "door", "fence"]],
  ["basement", "basement", "sous-sol", ["home"], ["stairs", "home", "dark", "garage", "spider", "box"]],
  ["attic", "attic", "grenier", ["home"], ["roof", "home", "box", "old", "ghost", "stairs"]],
  ["balcony", "balcony", "balcon", ["home", "city"], ["apartment", "window", "flower", "home", "building", "garden"]],
  ["hallway", "hallway", "couloir", ["home", "school"], ["door", "school", "home", "stairs", "locker"]],
  ["pharmacy", "pharmacy", "pharmacie", ["city"], ["medicine", "doctor", "sick", "hospital", "shop"]],
  ["harbor", "harbor", "port", ["ocean", "city"], ["boat", "ship", "sea", "anchor", "lighthouse", "fish", "sailor"]],
  ["cliff", "cliff", "falaise", ["nature"], ["mountain", "rock", "sea", "beach", "high", "fall"]],
  ["canyon", "canyon", "canyon", ["nature"], ["desert", "river", "rock", "cliff", "mountain"]],
  ["valley", "valley", "vallée", ["nature"], ["mountain", "river", "hill", "field", "farm"]],
  ["swamp", "swamp", "marais", ["nature", "water"], ["mud", "frog", "crocodile", "mosquito", "pond", "toad"]],
  ["stream", "stream", "ruisseau", ["nature", "water"], ["river", "water", "forest", "fish", "rock", "frog"]],
  ["glacier", "glacier", "glacier", ["nature", "cold"], ["ice", "mountain", "cold", "snow", "polar_bear"]],
  ["path", "path", "chemin", ["nature"], ["road", "forest", "hike", "walk", "garden", "map"]],
  ["traffic", "traffic", "embouteillage", ["city", "transport"], ["car", "road", "city", "bus", "taxi", "late"]],
  ["tunnel", "tunnel", "tunnel", ["transport"], ["train", "dark", "mountain", "car", "road", "bridge"]],
  ["subway", "subway", "métro", ["transport", "city"], ["train", "city", "station", "ticket", "tunnel", "bus"]],
  ["engine", "engine", "moteur", ["transport"], ["car", "train", "truck", "plane", "mechanic", "motorcycle"]],

  // Space and nature
  ["galaxy", "galaxy", "galaxie", ["space"], ["star", "space", "planet", "universe", "sky", "rocket"]],
  ["universe", "universe", "univers", ["space"], ["space", "star", "planet", "galaxy", "earth", "world"]],
  ["comet", "comet", "comète", ["space"], ["star", "space", "sky", "tail", "meteor"]],
  ["meteor", "meteor", "météorite", ["space"], ["space", "dinosaur", "rock", "sky", "star", "comet"]],
  ["sunrise", "sunrise", "lever du soleil", ["sky", "time"], ["sun", "morning", "sunset", "sky", "early", "rooster"]],
  ["noon", "noon", "midi", ["time"], ["lunch", "clock", "sun", "day", "afternoon", "morning"]],
  ["midnight", "midnight", "minuit", ["time", "night"], ["night", "clock", "dark", "moon", "new_year", "ghost", "sleep"]],
  ["today", "today", "aujourd’hui", ["time"], ["day", "morning", "calendar", "tomorrow", "yesterday"]],
  ["tomorrow", "tomorrow", "demain", ["time"], ["day", "today", "future", "morning", "calendar"]],
  ["yesterday", "yesterday", "hier", ["time"], ["day", "today", "memory", "calendar", "tomorrow", "week"]],
  ["future", "future", "futur", ["time", "science"], ["tomorrow", "time", "robot", "space", "dream"]],
  ["tornado", "tornado", "tornade", ["weather"], ["wind", "storm", "hurricane", "cloud", "weather"]],
  ["hurricane", "hurricane", "ouragan", ["weather"], ["storm", "wind", "rain", "sea", "tornado", "weather"]],
  ["frost", "frost", "givre", ["cold", "weather"], ["ice", "cold", "winter", "snow", "window", "morning"]],
  ["heat", "heat", "chaleur", ["hot", "weather"], ["hot", "sun", "summer", "fire", "warm", "oven", "desert"]],
  ["liquid", "liquid", "liquide", ["water", "science"], ["water", "drink", "juice", "milk", "wet", "bottle", "soup"]],
  ["dry", "dry", "sec", ["weather"], ["desert", "sun", "towel", "wet", "hot", "sand", "summer"]],
  ["cool", "cool", "frais", ["cold"], ["cold", "ice", "wind", "fan", "ice_cream", "summer"]],
  ["energy", "energy", "énergie", ["science"], ["electricity", "battery", "sun", "strong", "food", "run"]],
  ["lightbulb", "lightbulb", "ampoule", ["home", "light"], ["light", "lamp", "electricity", "idea", "bright"]],

  // Home
  ["laundry", "laundry", "lessive", ["home"], ["clothes", "wash", "washing_machine", "soap", "sock", "basket", "clean"]],
  ["dishes", "dishes", "vaisselle", ["home", "kitchen"], ["plate", "sink", "wash", "kitchen", "cup", "clean", "soap", "dinner"]],
  ["dishwasher", "dishwasher", "lave-vaisselle", ["home", "kitchen"], ["dishes", "kitchen", "plate", "clean", "wash", "sink"]],
  ["washing_machine", "washing machine", "machine à laver", ["home"], ["laundry", "clothes", "wash", "soap", "sock", "clean"]],
  ["toaster", "toaster", "grille-pain", ["home", "kitchen"], ["toast", "bread", "kitchen", "breakfast", "hot", "butter"]],
  ["kettle", "kettle", "bouilloire", ["home", "kitchen"], ["tea", "water", "hot", "kitchen", "coffee", "cup", "boil"]],
  ["blender", "blender", "mixeur", ["home", "kitchen"], ["smoothie", "kitchen", "fruit", "juice", "soup", "milkshake"]],
  ["sponge", "sponge", "éponge", ["home"], ["soap", "clean", "wash", "sink", "bubble", "dishes", "water"]],
  ["fan", "fan", "ventilateur", ["home", "hot"], ["wind", "hot", "summer", "cool", "cold"]],
  ["heater", "heater", "radiateur", ["home", "cold"], ["warm", "hot", "winter", "cold", "fire", "cozy"]],
  ["curtain", "curtain", "rideau", ["home"], ["window", "stage", "bedroom", "fabric", "dark", "theater"]],
  ["mattress", "mattress", "matelas", ["home"], ["bed", "sleep", "pillow", "blanket", "soft", "bedroom"]],
  ["drawer", "drawer", "tiroir", ["home"], ["desk", "closet", "sock", "table", "kitchen", "spoon"]],
  ["hanger", "hanger", "cintre", ["home", "clothes"], ["closet", "coat", "shirt", "clothes", "dress"]],
  ["vase", "vase", "vase", ["home"], ["flower", "rose", "table", "glass", "water"]],
  ["alarm", "alarm", "alarme", ["home", "sound"], ["clock", "morning", "wake", "loud", "bell", "fire", "police"]],
  ["crate", "crate", "caisse", ["home"], ["box", "wood", "dog", "fruit", "truck", "apple"]],
  ["cage", "cage", "cage", ["animal", "pet"], ["bird", "zoo", "hamster", "parrot", "lion", "pet", "mouse", "rabbit"]],
  ["nap", "nap", "sieste", ["home", "night"], ["sleep", "bed", "tired", "baby", "afternoon", "sofa", "pillow", "cat", "dream"]],
  ["relax", "relax", "se détendre", ["feeling"], ["vacation", "beach", "sofa", "bath", "calm", "sleep", "weekend"]],
  ["wash", "wash", "laver", ["home"], ["clean", "soap", "water", "hand", "bath", "laundry", "dishes", "sink", "shower"]],
  ["wake", "wake", "se réveiller", ["time", "home"], ["morning", "alarm", "sleep", "bed", "sunrise", "rooster", "breakfast"]],
  ["lock", "lock", "serrure", ["home"], ["key", "door", "gate", "bike", "locker", "secret"]],
  ["wallet", "wallet", "portefeuille", ["home"], ["money", "pocket", "coin", "bag", "card"]],
  ["coin", "coin", "pièce de monnaie", ["home"], ["money", "gold", "silver", "bank", "pocket", "treasure"]],
  ["card", "card", "cartes", ["game"], ["birthday", "game", "letter", "gift", "magic", "dice"]],
  ["dice", "dice", "dés", ["game"], ["game", "board_game", "number", "luck", "card"]],
  ["chess", "chess", "échecs", ["game"], ["king", "queen", "knight", "board_game", "game", "castle"]],
  ["magnet", "magnet", "aimant", ["science"], ["metal", "iron", "fridge", "science", "nail", "toy"]],
  ["keyboard", "keyboard", "clavier", ["tech", "music"], ["computer", "piano", "letter", "screen", "programmer"]],
  ["internet", "internet", "internet", ["tech"], ["computer", "phone", "email", "video_game", "screen", "tablet"]],
  ["video", "video", "vidéo", ["tech"], ["camera", "movie", "phone", "tv", "screen"]],
  ["machine", "machine", "machine", ["tech"], ["robot", "factory", "computer", "engine", "washing_machine"]],
  ["message", "message", "message", ["tech"], ["phone", "letter", "email", "friend", "write"]],
  ["jar", "jar", "bocal", ["kitchen"], ["jam", "honey", "cookie", "glass", "pickle"]],
  ["tray", "tray", "plateau", ["kitchen"], ["plate", "cafeteria", "breakfast", "cup", "tea"]],
  ["napkin", "napkin", "serviette de table", ["kitchen"], ["table", "dinner", "restaurant", "plate", "fork", "mouth"]],
  ["straw", "straw", "paille", ["drink", "farm"], ["drink", "juice", "milkshake", "hay", "cup", "soda"]],
  ["oil", "oil", "huile", ["food", "kitchen"], ["olive", "cook", "pan", "fries", "car", "salad"]],
  ["dust", "dust", "poussière", ["home"], ["dirty", "clean", "vacuum", "attic", "sneeze", "broom"]],

  // Clothes
  ["button", "button", "bouton", ["clothes"], ["shirt", "coat", "jacket", "phone", "pocket", "zipper"]],
  ["zipper", "zipper", "fermeture éclair", ["clothes"], ["jacket", "bag", "coat", "backpack", "pants"]],
  ["belt", "belt", "ceinture", ["clothes"], ["pants", "karate", "shorts", "dress", "suit", "zipper"]],
  ["apron", "apron", "tablier", ["clothes", "kitchen"], ["cook", "chef", "kitchen", "bake", "baker"]],
  ["uniform", "uniform", "uniforme", ["clothes", "job"], ["school", "police", "soldier", "nurse", "team", "shirt"]],
  ["slippers", "slippers", "chaussons", ["clothes", "home"], ["sock", "shoe", "pajamas", "bed", "warm", "cozy"]],
  ["bracelet", "bracelet", "bracelet", ["clothes"], ["necklace", "ring", "jewel", "arm", "gold", "watch"]],

  // Food
  ["gravy", "gravy", "jus de viande", ["food"], ["turkey", "potato", "meat", "dinner", "thanksgiving", "sauce", "roast", "chicken"]],
  ["sauce", "sauce", "sauce", ["food"], ["pasta", "ketchup", "pizza", "tomato", "gravy", "dinner"]],
  ["roast", "roast", "rôti", ["food"], ["meat", "oven", "chicken", "dinner", "potato", "turkey"]],
  ["stuffing", "stuffing", "farce", ["food", "holiday"], ["turkey", "thanksgiving", "bread", "dinner", "chicken"]],
  ["stew", "stew", "ragoût", ["food"], ["soup", "meat", "pot", "potato", "carrot", "dinner", "winter"]],
  ["curry", "curry", "curry", ["food"], ["rice", "spicy", "chicken", "sauce", "pepper"]],
  ["burrito", "burrito", "burrito", ["food"], ["taco", "rice", "bean", "cheese", "wrap"]],
  ["sushi", "sushi", "sushi", ["food"], ["fish", "rice", "chopsticks", "tuna", "restaurant", "salmon"]],
  ["dumpling", "dumpling", "raviole chinoise", ["food"], ["noodle", "chopsticks", "soup", "rice", "meat", "restaurant"]],
  ["lasagna", "lasagna", "lasagnes", ["food"], ["pasta", "cheese", "tomato", "oven", "dinner", "sauce"]],
  ["omelette", "omelette", "omelette", ["food"], ["egg", "breakfast", "cheese", "pan", "cook", "ham"]],
  ["bagel", "bagel", "bagel", ["food"], ["bread", "breakfast", "toast", "butter", "donut"]],
  ["cracker", "cracker", "biscuit salé", ["food"], ["cheese", "snack", "chips", "soup", "salt"]],
  ["pretzel", "pretzel", "bretzel", ["food"], ["salt", "snack", "bread", "chips", "cracker", "popcorn"]],
  ["nachos", "nachos", "nachos", ["food"], ["cheese", "chips", "salsa", "taco", "snack", "movie"]],
  ["salsa", "salsa", "salsa", ["food", "music"], ["tomato", "chips", "spicy", "taco", "dance", "nachos"]],
  ["guacamole", "guacamole", "guacamole", ["food"], ["avocado", "chips", "nachos", "taco", "green", "salsa"]],
  ["pudding", "pudding", "pudding", ["food", "sweet"], ["dessert", "chocolate", "spoon", "cake", "cream"]],
  ["jelly", "jelly", "gelée", ["food", "sweet"], ["jam", "peanut", "bread", "sandwich", "dessert"]],
  ["porridge", "porridge", "porridge", ["food"], ["breakfast", "milk", "bowl", "honey", "bear", "cereal"]],
  ["smoothie", "smoothie", "smoothie", ["drink"], ["fruit", "banana", "strawberry", "blender", "yogurt", "juice", "milkshake"]],
  ["milkshake", "milkshake", "milk-shake", ["drink", "sweet"], ["milk", "ice_cream", "chocolate", "strawberry", "straw", "burger"]],
  ["brunch", "brunch", "brunch", ["food"], ["breakfast", "lunch", "weekend", "pancake", "egg", "coffee", "waffle"]],
  ["puree", "puree", "purée", ["food"], ["potato", "baby", "soup", "soft", "carrot", "blender", "apple"]],
  ["vanilla", "vanilla", "vanille", ["sweet"], ["ice_cream", "chocolate", "cake", "cream", "sugar", "cookie"]],
  ["caramel", "caramel", "caramel", ["sweet"], ["candy", "sugar", "sweet", "apple", "chocolate", "popcorn"]],
  ["mustard", "mustard", "moutarde", ["food"], ["ketchup", "sandwich", "yellow", "burger", "sausage"]],
  ["mayonnaise", "mayonnaise", "mayonnaise", ["food"], ["ketchup", "fries", "sandwich", "egg", "burger"]],
  ["spicy", "spicy", "épicé", ["food", "hot"], ["pepper", "hot", "taco", "curry", "salsa"]],
  ["salmon", "salmon", "saumon", ["animal", "food", "water"], ["fish", "river", "bear", "pink", "sushi", "sea"]],
  ["shrimp", "shrimp", "crevette", ["animal", "ocean", "food"], ["sea", "fish", "crab", "lobster", "ocean", "pink"]],
  ["squid", "squid", "calamar", ["animal", "ocean"], ["octopus", "sea", "ocean", "ink", "fish"]],
  ["squash", "squash", "courge", ["food", "plant"], ["pumpkin", "vegetable", "soup", "autumn", "zucchini", "garden"]],
  ["zucchini", "zucchini", "courgette", ["food", "plant"], ["vegetable", "squash", "garden", "green", "cucumber"]],
  ["eggplant", "eggplant", "aubergine", ["food", "plant"], ["vegetable", "purple", "garden", "tomato", "zucchini"]],
  ["cabbage", "cabbage", "chou", ["food", "plant"], ["vegetable", "soup", "green", "lettuce", "rabbit", "garden"]],
  ["spinach", "spinach", "épinards", ["food", "plant"], ["vegetable", "green", "salad", "lettuce", "strong"]],
  ["celery", "celery", "céleri", ["food", "plant"], ["vegetable", "green", "carrot", "salad", "soup"]],
  ["radish", "radish", "radis", ["food", "plant"], ["vegetable", "red", "garden", "salad", "carrot", "root"]],
  ["beet", "beet", "betterave", ["food", "plant"], ["vegetable", "red", "purple", "salad", "sugar"]],
  ["asparagus", "asparagus", "asperge", ["food", "plant"], ["vegetable", "green", "spring", "garden", "dinner", "broccoli"]],
  ["avocado", "avocado", "avocat", ["food", "plant"], ["guacamole", "toast", "green", "fruit", "salad"]],
  ["olive", "olive", "olive", ["food", "plant"], ["oil", "pizza", "green", "salad", "tree", "pickle"]],
  ["apricot", "apricot", "abricot", ["food", "fruit"], ["peach", "orange", "fruit", "jam", "tree", "summer"]],
  ["plum", "plum", "prune", ["food", "fruit"], ["fruit", "purple", "cherry", "jam", "peach"]],
  ["kiwi", "kiwi", "kiwi", ["food", "fruit"], ["fruit", "green", "bird", "banana", "mango"]],
  ["melon", "melon", "melon", ["food", "fruit"], ["watermelon", "fruit", "summer", "orange", "green"]],
  ["berry", "berry", "baie", ["food", "fruit"], ["strawberry", "blueberry", "raspberry", "fruit", "bush", "bear", "red"]],
  ["raspberry", "raspberry", "framboise", ["food", "fruit"], ["strawberry", "berry", "red", "jam", "fruit", "blueberry"]],
  ["blueberry", "blueberry", "myrtille", ["food", "fruit"], ["blue", "muffin", "fruit", "pancake", "raspberry", "berry"]],
  ["blackberry", "blackberry", "mûre", ["food", "fruit"], ["berry", "fruit", "bush", "raspberry", "jam", "purple"]],
  ["cranberry", "cranberry", "canneberge", ["food", "fruit"], ["thanksgiving", "juice", "red", "sauce", "fruit", "berry"]],
  ["tangerine", "tangerine", "mandarine", ["food", "fruit"], ["orange", "fruit", "lemon", "christmas", "juice", "lime"]],
  ["grapefruit", "grapefruit", "pamplemousse", ["food", "fruit"], ["orange", "lemon", "sour", "breakfast", "fruit", "juice"]],

  // Animals
  ["llama", "llama", "lama", ["animal", "farm"], ["alpaca", "wool", "mountain", "camel", "farm", "sheep"]],
  ["alpaca", "alpaca", "alpaga", ["animal", "farm"], ["llama", "wool", "farm", "sheep", "fluffy"]],
  ["sloth", "sloth", "paresseux", ["animal"], ["slow", "tree", "jungle", "sleep", "monkey", "lazy"]],
  ["leopard", "leopard", "léopard", ["animal"], ["cheetah", "tiger", "lion", "jungle", "cat", "fast"]],
  ["canary", "canary", "canari", ["animal", "pet"], ["bird", "yellow", "sing", "cage", "pet"]],
  ["buffalo", "buffalo", "bison", ["animal"], ["cow", "bull", "horn", "cowboy", "field"]],
  ["walrus", "walrus", "morse", ["animal", "ocean", "cold"], ["seal", "ice", "sea", "polar_bear", "whale"]],
  ["woodpecker", "woodpecker", "pic-vert", ["animal"], ["bird", "tree", "wood", "beak", "forest"]],
  ["chameleon", "chameleon", "caméléon", ["animal"], ["lizard", "color", "jungle", "hide", "tree"]],
  ["tadpole", "tadpole", "têtard", ["animal", "water"], ["frog", "pond", "toad", "egg", "swim"]],
  ["moth", "moth", "papillon de nuit", ["animal"], ["butterfly", "light", "night", "lamp", "wing"]],
  ["slug", "slug", "limace", ["animal", "garden"], ["snail", "garden", "slow", "rain", "leaf"]],

  // Flowers
  ["tulip", "tulip", "tulipe", ["plant", "nature"], ["flower", "spring", "garden", "rose", "daisy", "vase", "red"]],
  ["daisy", "daisy", "marguerite", ["plant", "nature"], ["flower", "garden", "field", "white", "yellow", "spring", "tulip"]],
  ["lily", "lily", "lys", ["plant", "nature"], ["flower", "pond", "white", "garden", "frog", "rose"]],

  // Holidays and celebrations
  ["new_year", "new year", "Nouvel An", ["holiday", "celebration"], ["fireworks", "party", "midnight", "year", "wish"]],
  ["hanukkah", "Hanukkah", "Hanoukka", ["holiday", "celebration"], ["candle", "holiday", "winter", "family", "gift", "light"]],
  ["diwali", "Diwali", "Diwali", ["holiday", "celebration"], ["light", "candle", "holiday", "fireworks", "family", "sweet"]],
  ["festival", "festival", "festival", ["celebration", "music"], ["music", "party", "concert", "summer", "dance", "band", "parade"]],
  ["ornament", "ornament", "décoration de Noël", ["holiday"], ["christmas", "tree", "star", "ball", "gold"]],

  // Sport and activities
  ["volleyball", "volleyball", "volley", ["sport"], ["ball", "beach", "sport", "team", "sand", "jump"]],
  ["rugby", "rugby", "rugby", ["sport"], ["ball", "sport", "team", "run", "mud"]],
  ["football", "football", "football américain", ["sport"], ["ball", "sport", "team", "stadium", "helmet", "player", "soccer", "run"]],
  ["ballet", "ballet", "ballet", ["music", "art"], ["dance", "music", "stage", "dress", "pink", "show"]],
  ["clay", "clay", "pâte à modeler", ["art", "toy"], ["art", "pot", "mud", "play", "sculpture"]],
  ["sculpture", "sculpture", "sculpture", ["art"], ["statue", "art", "museum", "stone", "clay", "artist"]],
  ["statue", "statue", "statue", ["art", "city"], ["stone", "park", "museum", "sculpture", "city"]],
  ["whistle", "whistle", "sifflet", ["sound", "sport"], ["referee", "sport", "lifeguard", "loud", "bird", "police"]],
  ["buy", "buy", "acheter", ["city"], ["shop", "money", "market", "pay", "gift", "mall"]],
  ["sell", "sell", "vendre", ["city"], ["shop", "market", "money", "buy", "cashier", "pay"]],
  ["pay", "pay", "payer", ["city"], ["money", "shop", "bank", "buy", "salary", "restaurant"]],
  ["visit", "visit", "visiter", ["travel", "family"], ["grandma", "family", "trip", "museum", "friend", "travel"]],
  ["listen", "listen", "écouter", ["sound", "music"], ["music", "ear", "song", "radio", "quiet", "story"]],
  ["touch", "touch", "toucher", ["body"], ["hand", "finger", "soft", "skin", "smooth", "tickle"]],
  ["cut", "cut", "couper", ["kitchen"], ["scissors", "knife", "paper", "hair", "finger", "cook"]],
  ["boil", "boil", "bouillir", ["kitchen"], ["water", "hot", "pot", "egg", "kettle", "soup", "pasta"]],
  ["fry", "fry", "frire", ["kitchen"], ["pan", "egg", "fries", "oil", "cook", "chicken", "bacon"]],
  ["mix", "mix", "mélanger", ["kitchen"], ["bake", "spoon", "bowl", "cake", "flour", "egg", "blender"]],
  ["melt", "melt", "fondre", ["hot", "cold"], ["ice", "snow", "ice_cream", "hot", "sun", "chocolate", "snowman", "butter"]],
  ["freeze", "freeze", "geler", ["cold"], ["ice", "cold", "winter", "snow", "water"]],
  ["burn", "burn", "brûler", ["fire", "hot"], ["fire", "hot", "sun", "candle", "toast", "oven", "smoke"]],
  ["smoke", "smoke", "fumée", ["fire"], ["fire", "chimney", "grey", "cloud", "factory"]],
  ["splash", "splash", "éclaboussure", ["water"], ["water", "puddle", "pool", "swim", "wave", "wet", "rain"]],
  ["bounce", "bounce", "rebondir", ["sport", "toy"], ["ball", "trampoline", "jump", "basketball", "kangaroo", "bubble"]],
  ["chase", "chase", "poursuivre", ["game"], ["run", "dog", "cat", "catch", "police", "mouse"]],
  ["whisper", "whisper", "chuchoter", ["sound"], ["quiet", "secret", "ear", "talk", "voice", "library"]],
  ["shout", "shout", "crier", ["sound"], ["loud", "voice", "angry", "talk", "whisper", "noise"]],
  ["sneeze", "sneeze", "éternuer", ["body"], ["nose", "sick", "cold", "flower", "dust"]],
  ["yawn", "yawn", "bâiller", ["body", "night"], ["tired", "sleep", "bed", "mouth", "bored", "nap"]],
  ["snore", "snore", "ronfler", ["night"], ["sleep", "bed", "loud", "nose", "nap", "night"]],
  ["clap", "clap", "applaudir", ["music"], ["hand", "show", "concert", "stage", "music"]],
  ["tickle", "tickle", "chatouiller", ["feeling"], ["laugh", "feather", "foot", "funny", "smile", "toe"]],
  ["hurry", "hurry", "se dépêcher", ["time"], ["fast", "late", "run", "clock", "bus", "morning"]],
  ["late", "late", "en retard", ["time"], ["clock", "time", "hurry", "night", "school", "bus", "homework"]],
  ["early", "early", "tôt", ["time"], ["morning", "sunrise", "rooster", "breakfast", "alarm"]],

  // Body
  ["knee", "knee", "genou", ["body"], ["leg", "foot", "run", "hurt", "jump"]],
  ["elbow", "elbow", "coude", ["body"], ["arm", "knee", "hand", "shoulder", "body", "hurt"]],
  ["shoulder", "shoulder", "épaule", ["body"], ["arm", "neck", "head", "body", "backpack", "hug"]],
  ["lip", "lip", "lèvre", ["body"], ["mouth", "kiss", "smile", "red", "tooth"]],
  ["thumb", "thumb", "pouce", ["body"], ["finger", "hand", "toe", "nail", "phone", "body"]],
  ["toe", "toe", "orteil", ["body"], ["foot", "shoe", "sock", "finger", "sandal", "nail"]],
  ["stomach", "stomach", "ventre", ["body", "food"], ["hungry", "eat", "food", "body", "hurt"]],
  ["muscle", "muscle", "muscle", ["body", "sport"], ["strong", "arm", "gym", "run", "body"]],

  // Feelings and descriptions
  ["calm", "calm", "serein", ["feeling"], ["quiet", "peace", "relax", "lake", "sleep", "soft", "slow"]],
  ["bored", "bored", "ennuyé", ["feeling"], ["tired", "homework", "school", "tv", "rain", "yawn"]],
  ["excited", "excited", "impatient", ["feeling"], ["happy", "party", "birthday", "surprise", "christmas", "fun", "jump"]],
  ["nervous", "nervous", "nerveux", ["feeling"], ["fear", "test", "interview", "stage", "scary"]],
  ["proud", "proud", "fier", ["feeling"], ["win", "medal", "trophy", "happy", "parent", "family", "hero"]],
  ["lonely", "lonely", "esseulé", ["feeling"], ["sad", "friend", "quiet", "night", "cry", "hug"]],
  ["thirsty", "thirsty", "assoiffé", ["feeling", "drink"], ["water", "drink", "hot", "juice", "desert", "summer", "lemonade"]],
  ["heavy", "heavy", "lourd", [], ["rock", "elephant", "box", "strong", "iron", "big", "suitcase"]],
  ["hard", "hard", "dur", [], ["rock", "stone", "ice", "test", "metal", "wood", "math"]],
  ["smooth", "smooth", "lisse", [], ["soft", "glass", "ice", "skin", "stone"]],
  ["sharp", "sharp", "tranchant", [], ["knife", "scissors", "tooth", "claw", "pencil", "sword", "nail"]],
  ["fluffy", "fluffy", "duveteux", [], ["soft", "cloud", "fur", "cat", "kitten", "pillow", "sheep", "teddy_bear"]],
  ["shiny", "shiny", "étincelant", [], ["gold", "star", "jewel", "metal", "glass", "silver", "new", "sparkle"]],
  ["sticky", "sticky", "collant", [], ["glue", "honey", "tape", "syrup", "candy", "jam"]],
  ["young", "young", "jeune", ["family"], ["baby", "kid", "child", "new", "small", "student"]],
  ["empty", "empty", "vide", [], ["box", "glass", "bottle", "room", "hole"]],
  ["full", "full", "plein", [], ["empty", "glass", "moon", "cup", "box"]],
  ["beautiful", "beautiful", "magnifique", [], ["flower", "princess", "sunset", "rainbow", "rose", "art"]],
  ["weird", "weird", "bizarre", [], ["alien", "monster", "funny", "dream", "magic", "robot", "unicorn"]],
  ["lazy", "lazy", "fainéant", [], ["sleep", "sofa", "nap", "tired", "sloth", "cat", "weekend"]],
  ["rich", "rich", "riche", [], ["money", "gold", "king", "bank", "treasure", "jewel"]],

  // Ideas
  ["luck", "luck", "chance", ["magic"], ["wish", "star", "win", "game", "dice", "coin", "magic"]],
  ["hope", "hope", "espoir", ["feeling"], ["wish", "dream", "star", "love", "future"]],
  ["secret", "secret", "secret", ["story"], ["surprise", "hide", "whisper", "friend", "treasure", "diary", "key"]],
  ["memory", "memory", "mémoire", ["school"], ["brain", "photo", "dream", "family", "old", "story"]],
  ["danger", "danger", "danger", ["adventure"], ["fire", "scary", "adventure", "shark", "hero", "police"]],
  ["friendship", "friendship", "amitié", ["feeling", "family"], ["friend", "love", "hug", "share", "team"]],
  ["rule", "rule", "règlement", ["school", "game"], ["game", "school", "teacher", "referee", "judge"]]
];

// Missing links between existing words that people make instantly.
export const ADDED_LINKS_4 = [
  ["party", "christmas"], ["dog", "homework"], ["movie", "popcorn"], ["movie", "night"], ["rain", "umbrella"],
  ["oven", "hot"], ["microwave", "hot"], ["oven", "cook"], ["microwave", "cook"], ["bed", "dream"], ["moon", "dream"],
  ["paw", "pet"], ["fish", "pet"], ["sun", "hot"], ["summer", "hot"], ["fire", "hot"], ["winter", "snow"],
  ["beach", "vacation"], ["office", "work"], ["office", "boss"], ["computer", "work"], ["school", "bus"],
  ["birthday", "cake"], ["kitchen", "cook"], ["night", "sleep"], ["bed", "sleep"], ["pizza", "cheese"],
  ["rain", "cozy"], ["movie", "cozy"], ["crate", "bottle"], ["squash", "thanksgiving"], ["afternoon", "sun"], ["nap", "summer"],
  // Found by simulated games: everyday pairs with no direct link that people link instantly.
  ["sea", "food"], ["cat", "home"], ["home", "christmas"], ["party", "food"], ["moon", "cloud"], ["treasure", "sea"], ["sky", "weather"],
  ["home", "dinner"], ["plate", "lunch"], ["flower", "sun"], ["ocean", "vacation"], ["kitchen", "water"], ["home", "food"], ["winter", "cozy"],
  ["oven", "dinner"], ["night", "party"], ["fire", "light"], ["weather", "wet"], ["fish", "food"], ["kitchen", "cake"], ["kitchen", "tea"],
  ["pet", "bird"], ["family", "party"], ["flower", "tree"], ["rain", "sky"], ["rain", "sun"], ["lunch", "dinner"], ["park", "bird"],
  ["book", "glasses"], ["treasure", "boat"], ["park", "school"], ["book", "kid"], ["wing", "nest"], ["wing", "owl"], ["weather", "winter"],
  ["dad", "dinner"], ["cook", "eat"], ["kitchen", "restaurant"], ["roof", "window"], ["roof", "wall"], ["puppy", "kitten"], ["paw", "kitten"],
  ["paw", "cute"], ["cookie", "tea"], ["party", "hat"], ["snowman", "christmas"], ["clock", "wake"], ["sleep", "morning"], ["sun", "garden"],
  ["home", "warm"], ["garden", "bed"], ["sky", "rain"], ["dinosaur", "bird"], ["egg", "spring"], ["school", "home"], ["weather", "summer"], ["tea", "breakfast"]
];

export const ADDED_PHRASES_4 = {
  en: [["fire", "alarm"], ["lunch", "box"]],
  fr: []
};

// "Is a kind of" for the new words.
export const ADDED_MEMBERS_4 = [
  ["flower", ["tulip", "daisy", "lily"]],
  ["fruit", ["apricot", "plum", "kiwi", "melon", "berry", "raspberry", "blueberry", "blackberry", "cranberry", "tangerine", "grapefruit", "avocado"]],
  ["vegetable", ["squash", "zucchini", "eggplant", "cabbage", "spinach", "celery", "radish", "beet", "asparagus"]],
  ["animal", ["llama", "alpaca", "sloth", "leopard", "buffalo", "walrus", "chameleon"]],
  ["bird", ["canary", "woodpecker"]],
  ["job", ["lawyer", "judge", "accountant", "engineer", "programmer", "mechanic", "plumber", "carpenter", "electrician", "cashier", "librarian", "janitor", "secretary", "singer", "dancer", "actor", "writer", "driver", "lifeguard", "referee", "coach", "gardener", "butcher", "principal"]],
  ["sport", ["volleyball", "rugby", "football"]],
  ["holiday", ["new_year", "hanukkah", "diwali"]],
  ["drink", ["smoothie", "milkshake"]],
  ["weather", ["tornado", "hurricane", "frost"]]
];

// Synonyms, regional spellings and everyday words that mean an existing word (only where no word
// already has that spelling). Derived words map to their plain meaning (puree → its own word, but
// cubicle → office, destination → trip). Nothing here is a guess from a piece of a word.
export const ALIASES_4 = {
  en: {
    cubicle: "office", destination: "trip", journey: "trip", daytime: "day", luggage: "suitcase", baggage: "suitcase",
    resort: "hotel", motel: "hotel", sunshine: "sun", sunlight: "sun", warmth: "warm", hotness: "heat",
    manager: "boss", paycheck: "salary", wage: "salary", colleague: "coworker", workplace: "office", career: "job",
    garbage: "trash", trashcan: "trash", rubbish: "trash", bin: "trash", dustbin: "trash",
    radiator: "heater", duvet: "blanket", quilt: "blanket", comforter: "blanket", wardrobe: "closet", cabinet: "closet", cupboards: "closet",
    mashed: "potato", mash: "potato", casserole: "stew", biscuit: "cookie", custard: "pudding", oatmeal: "porridge", granola: "cereal",
    courgette: "zucchini", aubergine: "eggplant", kale: "cabbage", clementine: "tangerine", nectarine: "peach", sweetcorn: "corn", mayo: "mayonnaise",
    prawn: "shrimp", chimp: "monkey", chimpanzee: "monkey", orangutan: "monkey", baboon: "monkey", ape: "gorilla",
    rhinoceros: "rhino", hippopotamus: "hippo", tortoise: "turtle", gecko: "lizard", iguana: "lizard", gerbil: "hamster",
    raven: "crow", falcon: "hawk", panther: "leopard", bison: "buffalo", elk: "moose", hare: "rabbit", mule: "donkey", ox: "bull",
    dino: "dinosaur", trex: "dinosaur", "t-rex": "dinosaur", stegosaurus: "dinosaur", triceratops: "dinosaur",
    celebration: "party", festivity: "party", newyear: "new_year", "new years": "new_year", hanukah: "hanukkah", chanukah: "hanukkah",
    cycling: "bike", biking: "bike", jogging: "jog", soccerball: "soccer",
    tiny: "small", little: "small", huge: "big", enormous: "big", large: "big",
    chilly: "cold", freezing: "cold", icy: "cold", boiling: "hot", scorching: "hot", humid: "wet", damp: "wet", soggy: "wet",
    scared: "fear", afraid: "fear", frightened: "fear", terrified: "fear", cheerful: "happy", glad: "happy", joyful: "happy", upset: "sad", unhappy: "sad", mad: "angry", grumpy: "angry",
    sleepy: "tired", exhausted: "tired", starving: "hungry", relaxed: "relax", relaxing: "relax", rest: "relax", resting: "relax",
    pretty: "beautiful", lovely: "beautiful", gorgeous: "beautiful", strange: "weird", odd: "weird", silly: "funny", hilarious: "funny",
    messy: "dirty", filthy: "dirty", tidy: "clean", neat: "clean", delicious: "yummy", tasty: "yummy",
    clever: "smart", intelligent: "smart", genius: "smart", difficult: "hard", dangerous: "danger", wealthy: "rich", lucky: "luck",
    yell: "shout", scream: "shout", giggle: "laugh", chuckle: "laugh", sob: "cry", hear: "listen", hearing: "listen",
    call: "phone", text: "message", texting: "message", teach: "teacher", teaching: "teacher",
    shopping: "shop", purchase: "buy", rush: "hurry", dawn: "sunrise", dusk: "evening", midday: "noon", mist: "fog",
    breeze: "wind", drizzle: "rain", icicle: "ice", hail: "ice",
    laptop: "computer", pc: "computer", charger: "battery", mug: "cup", "t-shirt": "shirt", tshirt: "shirt", tee: "shirt",
    hoodie: "sweater", jumper: "sweater", sweatshirt: "sweater", sneakers: "shoe", purse: "bag", handbag: "bag", jewelry: "jewel", jewellery: "jewel",
    lorry: "truck", motorbike: "motorcycle", jet: "plane", airplane: "plane", aeroplane: "plane", ferry: "boat", yacht: "sailboat", tram: "train", metro: "subway", underground: "subway",
    port: "harbor", harbour: "harbor", coast: "beach", shore: "beach", seaside: "beach", creek: "stream", brook: "stream", marsh: "swamp",
    neighbour: "neighbor", flat: "apartment", college: "university", clinic: "hospital", drugstore: "pharmacy", chemist: "pharmacy",
    supermarket: "market", grocery: "market", groceries: "market", fireman: "firefighter", policeman: "police", policewoman: "police", officer: "police",
    author: "writer", actress: "actor", waitress: "waiter", painter: "artist", programming: "programmer", coder: "programmer",
    belly: "stomach", tummy: "stomach", lips: "lip", toes: "toe", knees: "knee",
    exercising: "exercise", workout: "exercise", fitness: "exercise", teamwork: "team", kindness: "friendship",
    sightseeing: "tourist", power: "energy", slice: "cut", sliced: "cut", chopped: "cut", chop: "cut", weekday: "week", nighttime: "night", stapler: "office",
    volley: "volleyball", jello: "jelly", spice: "spicy", spices: "spicy",
    pancakes: "pancake", spaghettis: "pasta", lasagne: "lasagna", omelet: "omelette", nacho: "nachos"
  },
  fr: {
    "voyage organisé": "trip", "patron": "boss", "boulot": "work", "poubelle": "trash",
    "minuscule": "small", "énorme": "big", "brûlant": "hot", "effrayé": "fear", "content": "happy",
    "ordinateur portable": "computer", "portable": "phone", "t-shirt": "shirt", "pull": "sweater", "baskets": "shoe",
    "supermarché": "market", "pompier": "firefighter", "policier": "police", "avion": "plane"
  }
};

// Real everyday words the speller should know as words (so they are never read as a piece of
// another word or "corrected" into one). Words with a concept or alias above are already known.
export const EXTRA_WORDS_4 = {
  en: ["hotel", "passport", "garbage", "alarm", "friendship", "electrician", "carpool", "classmate", "playdate", "homemade", "toothache", "headache",
    // Real words one letter away from a new word: known as words, so never "corrected" into it.
    "stamp", "swap", "streak", "coil", "lack", "bolt", "felt", "case", "create", "crane", "grate", "heal", "heap", "rust", "must", "trap", "pray",
    "stray", "saucer", "boast", "stow", "curly", "plus", "plumb", "glum", "merry", "myth", "slum", "smug", "bore", "bared", "herd", "harm", "fuel",
    "hull", "coal", "fool", "inch", "hazy", "lacy", "buck", "tuck", "hose", "ideal", "ranger", "anger", "manger", "role", "foil", "bail", "malt",
    "born", "burnt", "spoke", "chose", "snout", "spout", "scout", "lawn", "pawn", "clip", "flap", "slap", "hate", "mate", "rate", "yearly", "nearly",
    "woke", "cash", "dash", "torch", "cell", "sill", "stink", "rank", "sank", "blank", "patch", "funnel", "hostel", "trim", "grip", "strip", "cord",
    "dime", "dine", "mutton", "grave", "gravel", "squad", "squish", "alive", "ballot", "bullet", "mallet", "pallet", "status", "thump", "printed",
    "holder", "older", "export", "layer", "ginger", "linger", "cancer", "factor", "diver", "roach", "poach", "bury", "principle", "rocker", "trade",
    "grace", "sturdy", "steady", "dairy", "bruise", "crude", "county", "click", "canon", "neon", "noun", "coaster", "settle", "nettle", "slender",
    "cheater", "header", "certain", "hunger", "base", "vast", "massage", "thing"],
  fr: []
};
