// Dataset v5 additions (original, hand-written data; no third-party association norms).
//
// Why: the engine-2.4 playtest logs. Ordinary words (frame, peripheral, accessory, goggles,
// protection, solar, structure, spatula…) were not in the graph, so the bot answered only the other
// word ("frame + tree → apple", "goggles + sun → flower"). Worse, some unknown real words were
// "spell-corrected" into a different known word (speaker → shoe, chain → chair, wifi → wife,
// password → passport, cough → sofa, speed → seed, trick → truck, globe → glove). An audit of ~1,000
// everyday words (test/fixtures/common-words.json) found about one in five missing. These rows add
// them with ordinary links (the first links are what most people would think of first), and fill
// obvious gaps between existing words (zoo ↔ bear, game night, movie night).
// Same row shape as data.js: [id, englishLabel, frenchLabel, tags, links].

export const DATASET_VERSION = "lexicon-5";

export const ADDED_CONCEPTS_5 = [
  // Household objects and tools
  ["frame", "frame", "cadre", ["home", "art"], ["picture", "photo", "painting", "wall", "window", "glasses", "door", "wood", "mirror"]],
  ["cushion", "cushion", "coussin", ["home"], ["pillow", "sofa", "soft", "chair"]],
  ["charger", "charger", "chargeur", ["tech", "home"], ["phone", "battery", "cable", "plug", "laptop", "electricity", "socket"]],
  ["news", "news", "actualités", ["tech", "city"], ["tv", "newspaper", "radio", "story", "information", "channel", "phone"]],
  ["newspaper", "newspaper", "journal", ["book", "city"], ["news", "paper", "read", "magazine", "morning", "coffee"]],
  ["bulb", "bulb", "bulbe", ["home", "light"], ["lightbulb", "light", "lamp", "electricity", "idea", "bright", "flower", "tulip"]],
  ["switch", "switch", "interrupteur", ["home", "light", "tech"], ["light", "lamp", "electricity", "button", "wall", "plug"]],
  ["plug", "plug", "prise", ["home", "tech"], ["electricity", "socket", "cable", "charger", "wire", "switch", "sink"]],
  ["socket", "socket", "prise murale", ["home", "tech"], ["plug", "electricity", "wall", "charger", "cable"]],
  ["cable", "cable", "câble", ["tech", "home"], ["wire", "plug", "charger", "computer", "tv", "internet", "electricity", "phone"]],
  ["wire", "wire", "fil électrique", ["tech", "home"], ["cable", "electricity", "plug", "metal", "fence", "phone"]],
  ["remote", "remote", "télécommande", ["tech", "home"], ["tv", "button", "sofa", "battery", "channel", "video_game"]],
  ["tap", "tap", "robinet", ["home", "water", "kitchen"], ["water", "sink", "bathroom", "kitchen", "bath", "shower"]],
  ["razor", "razor", "rasoir", ["home", "body"], ["shave", "beard", "sharp", "bathroom", "face", "blade"]],
  ["shave", "shave", "se raser", ["body", "home"], ["razor", "beard", "face", "bathroom", "dad", "soap"]],
  ["blade", "blade", "lame", ["home"], ["knife", "sword", "sharp", "razor", "cut", "grass", "skate"]],
  ["can", "can", "canette", ["food", "drink", "kitchen"], ["soda", "drink", "tin", "soup", "trash", "recycling", "metal", "open"]],
  ["tin", "tin", "boîte de conserve", ["food", "kitchen"], ["can", "metal", "soup", "food", "box"]],
  ["lid", "lid", "couvercle", ["kitchen", "home"], ["pot", "jar", "box", "pan", "bottle", "cover", "open"]],
  ["cover", "cover", "couverture de livre", ["book", "home"], ["book", "lid", "blanket", "page", "magazine", "protection"]],
  ["spatula", "spatula", "spatule", ["kitchen", "food"], ["pan", "pancake", "cook", "flip", "burger", "kitchen", "spoon", "grill", "bake", "egg"]],
  ["flip", "flip", "retourner", ["kitchen", "sport"], ["pancake", "spatula", "coin", "jump", "gymnastics", "burger"]],
  ["whisk", "whisk", "fouet", ["kitchen", "food"], ["egg", "cream", "bake", "cake", "mix", "bowl", "kitchen", "spoon"]],
  ["ladle", "ladle", "louche", ["kitchen", "food"], ["soup", "spoon", "pot", "stew", "bowl", "kitchen"]],
  ["ceiling", "ceiling", "plafond", ["home"], ["roof", "wall", "room", "lamp", "fan", "floor", "high"]],
  ["stool", "stool", "tabouret", ["home"], ["chair", "seat", "kitchen", "piano", "table"]],
  ["bench", "bench", "banc", ["home", "city"], ["park", "seat", "chair", "garden", "wood", "sit", "bus"]],
  ["needle", "needle", "aiguille", ["home", "clothes"], ["thread", "sew", "doctor", "knit", "sharp"]],
  ["thread", "thread", "fil", ["clothes", "home"], ["needle", "sew", "string", "button", "yarn", "spider"]],
  ["sew", "sew", "coudre", ["clothes", "art"], ["needle", "thread", "button", "dress", "fabric", "knit", "grandma"]],
  ["hook", "hook", "crochet", ["home", "ocean"], ["fish", "pirate", "coat", "wall", "hanger", "worm"]],
  ["screw", "screw", "vis", ["home", "job"], ["screwdriver", "nail", "drill", "wood", "tool", "metal", "fix"]],
  ["screwdriver", "screwdriver", "tournevis", ["home", "job"], ["screw", "tool", "fix", "hammer", "drill", "toolbox"]],
  ["wrench", "wrench", "clé à molette", ["home", "job"], ["tool", "plumber", "fix", "mechanic", "toolbox", "car"]],
  ["drill", "drill", "perceuse", ["home", "job"], ["hole", "screw", "tool", "wall", "dentist", "wood", "noise"]],
  ["saw", "saw", "scie", ["home", "job"], ["wood", "cut", "tree", "tool", "carpenter", "log", "sharp"]],
  ["rake", "rake", "râteau", ["garden", "nature"], ["leaf", "garden", "autumn", "grass", "shovel", "hay"]],
  ["hose", "hose", "tuyau d’arrosage", ["garden", "water"], ["water", "garden", "firefighter", "car", "wash", "flower", "splash"]],
  ["toolbox", "toolbox", "boîte à outils", ["home", "job"], ["tool", "hammer", "screwdriver", "wrench", "fix", "box"]],
  ["tape_measure", "tape measure", "mètre ruban", ["home", "job"], ["ruler", "measure", "carpenter", "builder", "tool", "long"]],
  ["measure", "measure", "mesurer", ["math", "home"], ["ruler", "size", "tall", "long", "scale", "math"]],
  ["envelope", "envelope", "enveloppe", ["home", "job"], ["letter", "stamp", "mail", "card", "paper", "post_office"]],
  ["stamp", "stamp", "timbre", ["home", "job"], ["letter", "envelope", "mail", "post_office", "card", "sticker"]],
  ["mail", "mail", "courrier", ["home", "job"], ["letter", "envelope", "stamp", "package", "post_office", "mailbox", "email"]],
  ["mailbox", "mailbox", "boîte aux lettres", ["home", "city"], ["mail", "letter", "post_office", "home", "door"]],
  ["post_office", "post office", "bureau de poste", ["city", "job"], ["mail", "stamp", "letter", "package", "envelope"]],
  ["package", "package", "colis", ["home", "job"], ["box", "mail", "delivery", "gift", "post_office", "door", "tape"]],
  ["delivery", "delivery", "livraison", ["job", "city"], ["package", "pizza", "truck", "mail", "door", "box"]],
  ["recycling", "recycling", "recyclage", ["home", "nature"], ["trash", "bottle", "paper", "plastic", "can", "earth", "green", "bin"]],
  ["bin", "bin", "bac à ordures", ["home"], ["trash", "recycling", "garbage", "kitchen", "lid"]],
  ["garbage", "garbage", "ordures", ["home", "city"], ["trash", "bin", "smell", "truck", "recycling"]],
  ["chain", "chain", "chaîne", ["home"], ["metal", "lock", "bike", "necklace", "anchor", "dog", "ring", "gold"]],
  ["metal", "metal", "métal", ["science", "home"], ["iron", "gold", "silver", "steel", "magnet", "chain", "robot", "hard", "can"]],
  ["steel", "steel", "acier", ["science", "city"], ["metal", "iron", "bridge", "strong", "building", "hard"]],
  ["plastic", "plastic", "plastique", ["home", "science"], ["bottle", "bag", "toy", "recycling", "cup", "straw"]],
  ["wooden", "wooden", "en bois", ["home", "nature"], ["wood", "tree", "table", "chair", "toy", "log", "boat"]],
  ["globe", "globe", "globe terrestre", ["school", "travel"], ["world", "earth", "map", "country", "round", "school", "ocean"]],
  ["vacuum_bag", "dustpan", "pelle à poussière", ["home"], ["broom", "dust", "clean", "dirt", "floor"]],

  // Tech
  ["monitor", "monitor", "écran d’ordinateur", ["tech"], ["screen", "computer", "keyboard", "desk", "mouse", "tv"]],
  ["laptop", "laptop", "ordinateur portable", ["tech"], ["computer", "screen", "keyboard", "internet", "work", "school", "battery", "mouse"]],
  ["earbuds", "earbuds", "écouteurs", ["tech", "music"], ["headphones", "music", "ear", "phone", "listen", "song"]],
  ["headphones", "headphones", "casque audio", ["tech", "music"], ["music", "ear", "listen", "song", "earbuds", "phone", "loud", "radio"]],
  ["speaker", "speaker", "enceinte", ["tech", "music"], ["music", "loud", "sound", "radio", "party", "song", "phone", "bluetooth"]],
  ["bluetooth", "bluetooth", "bluetooth", ["tech"], ["phone", "speaker", "headphones", "wifi", "earbuds"]],
  ["microphone", "microphone", "micro", ["tech", "music"], ["sing", "singer", "voice", "concert", "stage", "speak", "radio", "podcast"]],
  ["console", "console", "console de jeux", ["tech", "game"], ["video_game", "controller", "tv", "game", "joystick", "play"]],
  ["controller", "controller", "manette", ["tech", "game"], ["video_game", "console", "button", "joystick", "tv", "play", "remote"]],
  ["joystick", "joystick", "joystick", ["tech", "game"], ["video_game", "controller", "console", "game", "plane"]],
  ["website", "website", "site web", ["tech"], ["internet", "computer", "online", "page", "app", "phone"]],
  ["app", "app", "appli", ["tech"], ["phone", "tablet", "game", "internet", "download", "screen", "website"]],
  ["selfie", "selfie", "selfie", ["tech", "art"], ["photo", "phone", "camera", "smile", "face", "friend"]],
  ["drone", "drone", "drone", ["tech", "sky"], ["fly", "camera", "sky", "remote", "plane", "helicopter", "robot"]],
  ["device", "device", "appareil", ["tech"], ["phone", "computer", "tablet", "gadget", "screen", "battery", "charger", "machine"]],
  ["gadget", "gadget", "gadget", ["tech", "toy"], ["device", "phone", "robot", "tool", "spy", "machine"]],
  ["peripheral", "peripheral", "périphérique", ["tech"], ["computer", "keyboard", "mouse", "printer", "monitor", "device", "cable", "speaker"]],
  ["accessory", "accessory", "accessoire", ["clothes", "tech"], ["bag", "bracelet", "necklace", "watch", "hat", "belt", "phone", "sunglasses", "ring", "fashion"]],
  ["software", "software", "logiciel", ["tech"], ["computer", "app", "program", "code", "programmer", "game"]],
  ["hardware", "hardware", "matériel informatique", ["tech"], ["computer", "keyboard", "tool", "device", "machine"]],
  ["program", "program", "programme", ["tech", "school"], ["computer", "code", "software", "programmer", "app", "tv", "show"]],
  ["code", "code", "code", ["tech", "science"], ["computer", "programmer", "password", "secret", "program", "number", "robot", "spy"]],
  ["password", "password", "mot de passe", ["tech"], ["secret", "computer", "code", "lock", "email", "phone", "key"]],
  ["download", "download", "télécharger", ["tech"], ["internet", "app", "computer", "file", "phone", "game", "upload"]],
  ["upload", "upload", "mettre en ligne", ["tech"], ["internet", "photo", "video", "computer", "download", "file"]],
  ["file", "file", "fichier", ["tech", "job"], ["folder", "computer", "paper", "document", "download", "office"]],
  ["document", "document", "document", ["job", "tech"], ["paper", "file", "folder", "report", "office", "printer", "letter"]],
  ["data", "data", "données", ["tech", "science"], ["computer", "number", "file", "internet", "science", "information"]],
  ["information", "information", "information", ["school", "tech"], ["data", "news", "fact", "book", "internet", "library"]],
  ["network", "network", "réseau", ["tech"], ["internet", "computer", "wifi", "phone", "signal", "friend"]],
  ["wifi", "wifi", "wifi", ["tech"], ["internet", "phone", "computer", "password", "signal", "online", "network"]],
  ["signal", "signal", "signal", ["tech", "transport"], ["phone", "wifi", "antenna", "radio", "traffic", "satellite"]],
  ["satellite", "satellite", "satellite", ["space", "tech"], ["space", "planet", "orbit", "rocket", "signal", "antenna", "moon", "earth"]],
  ["orbit", "orbit", "orbite", ["space", "science"], ["planet", "satellite", "moon", "earth", "space", "sun"]],
  ["antenna", "antenna", "antenne", ["tech", "animal"], ["radio", "tv", "signal", "satellite", "insect", "ant", "roof"]],
  ["solar", "solar", "solaire", ["sky", "science", "light"], ["sun", "energy", "panel", "planet", "electricity", "space", "light", "hot"]],
  ["panel", "panel", "panneau", ["tech", "home"], ["solar", "sun", "roof", "button", "wall"]],
  ["motor", "motor", "moteur électrique", ["transport", "tech"], ["engine", "car", "boat", "machine", "electricity", "fan"]],
  ["sensor", "sensor", "capteur", ["tech", "science"], ["robot", "alarm", "light", "camera", "machine"]],
  ["chip", "chip", "puce électronique", ["tech"], ["computer", "phone", "robot", "card", "electricity"]],
  ["virus", "virus", "virus", ["science", "body"], ["sick", "computer", "germ", "doctor", "flu", "cough", "medicine"]],
  ["germ", "germ", "microbe", ["science", "body"], ["virus", "sick", "soap", "wash", "hand", "dirty"]],
  ["flu", "flu", "grippe", ["body"], ["sick", "fever", "cough", "virus", "doctor", "bed", "medicine", "winter"]],
  ["hacker", "hacker", "pirate informatique", ["tech", "job"], ["computer", "password", "code", "internet", "virus", "secret", "spy"]],
  ["spy", "spy", "espion", ["story", "job", "adventure"], ["secret", "agent", "code", "mask", "gadget", "detective", "hide"]],
  ["agent", "agent", "agent secret", ["job", "story"], ["spy", "secret", "police", "detective"]],
  ["detective", "detective", "détective", ["job", "story"], ["mystery", "clue", "police", "spy", "magnifying_glass", "secret"]],
  ["clue", "clue", "indice", ["story", "game"], ["mystery", "detective", "puzzle", "secret", "treasure", "answer", "hint"]],
  ["hint", "hint", "astuce", ["game", "school"], ["clue", "help", "answer", "puzzle", "secret"]],
  ["magnifying_glass", "magnifying glass", "loupe", ["science", "story"], ["detective", "glass", "small", "bug", "science", "clue"]],
  ["online", "online", "en ligne", ["tech"], ["internet", "computer", "website", "wifi", "game", "phone", "shop"]],
  ["offline", "offline", "hors ligne", ["tech"], ["internet", "computer", "online", "phone", "wifi"]],
  ["podcast", "podcast", "podcast", ["tech", "sound"], ["radio", "listen", "headphones", "microphone", "talk", "phone", "story"]],
  ["emoji", "emoji", "émoji", ["tech", "feeling"], ["smile", "phone", "message", "text", "face", "heart", "funny"]],
  ["text", "text", "texto", ["tech", "school"], ["message", "phone", "email", "letter", "word", "read", "emoji"]],
  ["chat", "chat", "discussion", ["tech", "family"], ["talk", "message", "friend", "phone", "text", "online"]],
  ["notification", "notification", "notification", ["tech"], ["phone", "message", "bell", "app", "alarm", "email", "news"]],
  ["timer", "timer", "minuteur", ["time", "kitchen"], ["clock", "time", "alarm", "oven", "kitchen", "race", "watch", "egg"]],
  ["streaming", "streaming", "streaming", ["tech"], ["movie", "video", "tv", "internet", "music", "online", "show"]],
  ["channel", "channel", "chaîne de télé", ["tech"], ["tv", "remote", "show", "video", "news"]],
  ["magazine", "magazine", "magazine", ["book"], ["book", "news", "page", "read", "photo", "paper", "fashion"]],
  ["page", "page", "page", ["book", "school"], ["book", "paper", "read", "notebook", "magazine", "website"]],

  // Nature
  ["trunk", "trunk", "tronc", ["nature", "plant", "animal"], ["tree", "elephant", "bark", "wood", "branch", "root", "car"]],
  ["petal", "petal", "pétale", ["plant", "nature"], ["flower", "rose", "daisy", "tulip", "pink", "spring"]],
  ["pebble", "pebble", "galet", ["nature", "water"], ["stone", "rock", "beach", "river", "sand", "small"]],
  ["soil", "soil", "humus", ["nature", "garden"], ["dirt", "garden", "plant", "seed", "worm", "mud", "grow"]],
  ["iceberg", "iceberg", "iceberg", ["cold", "ocean"], ["ice", "ocean", "cold", "glacier", "ship", "polar_bear", "penguin"]],
  ["shadow", "shadow", "ombre", ["light", "night"], ["dark", "sun", "light", "night", "tree", "ghost"]],
  ["ash", "ash", "cendre", ["fire"], ["fire", "smoke", "volcano", "grey", "burn", "campfire"]],
  ["campfire", "campfire", "feu de camp", ["fire", "adventure"], ["fire", "camping", "marshmallow", "tent", "story", "wood", "night"]],
  ["air", "air", "air", ["sky", "nature"], ["wind", "breath", "sky", "balloon", "bubble", "fresh", "plane"]],
  ["environment", "environment", "environnement", ["nature", "science"], ["nature", "earth", "pollution", "recycling", "tree", "planet", "climate"]],
  ["climate", "climate", "climat", ["weather", "science"], ["weather", "earth", "hot", "cold", "environment", "pollution"]],
  ["pollution", "pollution", "pollution", ["nature", "city"], ["smoke", "car", "trash", "air", "factory", "dirty", "environment", "recycling"]],
  ["fresh", "fresh", "fraîche", ["food", "nature"], ["air", "fruit", "bread", "new", "clean", "vegetable", "cool"]],
  ["rotten", "rotten", "pourri", ["food"], ["apple", "egg", "smell", "old", "trash", "banana", "fruit"]],
  ["natural", "natural", "naturel", ["nature"], ["nature", "plant", "forest", "fresh", "earth"]],

  // Animals
  ["leash", "leash", "laisse", ["pet", "animal"], ["dog", "walk", "collar", "puppy", "park", "pet"]],
  ["collar", "collar", "collier de chien", ["pet", "clothes"], ["dog", "cat", "leash", "shirt", "neck", "pet"]],

  // Body and health
  ["tongue", "tongue", "la langue", ["body"], ["mouth", "taste", "lick", "tooth", "lip", "ice_cream"]],
  ["lick", "lick", "lécher", ["body", "food"], ["tongue", "ice_cream", "lollipop", "dog", "cat"]],
  ["blood", "blood", "sang", ["body"], ["red", "heart", "vampire", "hurt", "doctor", "cut"]],
  ["back", "back", "dos", ["body"], ["spine", "shoulder", "backpack", "chair", "body", "neck"]],
  ["spine", "spine", "colonne vertébrale", ["body"], ["back", "bone", "skeleton", "book", "neck"]],
  ["chest", "chest", "torse", ["body", "adventure"], ["heart", "treasure", "pirate", "body", "shirt", "lungs"]],
  ["lungs", "lungs", "poumons", ["body"], ["breath", "air", "chest", "body", "heart"]],
  ["breath", "breath", "souffle", ["body"], ["air", "lungs", "blow", "yawn", "nose", "mouth", "swim"]],
  ["blow", "blow", "souffler", ["body", "weather"], ["wind", "candle", "balloon", "bubble", "breath", "birthday"]],
  ["health", "health", "santé", ["body"], ["doctor", "healthy", "hospital", "medicine", "exercise", "body", "vegetable"]],
  ["healthy", "healthy", "en bonne santé", ["body", "food"], ["vegetable", "fruit", "exercise", "strong", "health", "salad"]],
  ["pill", "pill", "pilule", ["body"], ["medicine", "doctor", "sick", "water", "pharmacy"]],
  ["bandage", "bandage", "pansement", ["body"], ["hurt", "cut", "doctor", "nurse", "knee", "blood"]],
  ["fever", "fever", "fièvre", ["body", "hot"], ["sick", "hot", "flu", "doctor", "thermometer", "bed"]],
  ["thermometer", "thermometer", "thermomètre", ["science", "body"], ["fever", "hot", "cold", "weather", "doctor"]],
  ["cough", "cough", "toux", ["body"], ["sick", "cold", "flu", "throat", "sneeze", "doctor", "medicine"]],
  ["throat", "throat", "gorge", ["body"], ["neck", "cough", "voice", "mouth", "pain"]],
  ["pain", "pain", "douleur", ["body", "feeling"], ["hurt", "ouch", "doctor", "medicine", "cry", "headache"]],
  ["ouch", "ouch", "aïe", ["body", "sound"], ["hurt", "pain", "bee", "fall", "cry"]],
  ["headache", "headache", "mal de tête", ["body"], ["head", "pain", "loud", "medicine", "tired"]],
  ["goggles", "goggles", "lunettes de protection", ["clothes", "sport"], ["swim", "pool", "eyes", "glasses", "ski", "water", "scientist", "protection", "sunglasses", "snow"]],
  ["eyes", "eyes", "yeux", ["body"], ["eye", "see", "glasses", "look", "face", "blue"]],
  ["see", "see", "voir", ["body"], ["eye", "look", "glasses", "light", "watch"]],
  ["look", "look", "regarder", ["body"], ["see", "eye", "watch", "mirror"]],
  ["contact", "contact", "contact", ["family", "tech"], ["phone", "friend", "email", "touch", "message"]],

  // Places and structures
  ["highway", "highway", "autoroute", ["transport", "city"], ["road", "car", "traffic", "truck", "fast", "drive", "bridge"]],
  ["temple", "temple", "temple", ["city", "holiday"], ["church", "pray", "old", "monument", "statue", "mountain"]],
  ["pray", "pray", "prier", ["holiday", "feeling"], ["church", "temple", "hope", "wish", "religion"]],
  ["religion", "religion", "religion", ["holiday"], ["church", "temple", "pray", "god", "tradition", "holiday"]],
  ["god", "god", "dieu", ["story", "holiday"], ["religion", "church", "pray", "angel", "heaven"]],
  ["heaven", "heaven", "paradis", ["story", "sky"], ["angel", "sky", "cloud", "god"]],
  ["prison", "prison", "prison", ["city", "job"], ["police", "jail_bars", "bad", "thief", "lock", "key", "judge"]],
  ["jail_bars", "bars", "barreaux", ["city"], ["prison", "cage", "metal", "window"]],
  ["thief", "thief", "voleur", ["story", "city"], ["police", "steal", "prison", "money", "mask", "night", "bank"]],
  ["steal", "steal", "dérober", ["story"], ["thief", "money", "police", "secret"]],
  ["skyscraper", "skyscraper", "gratte-ciel", ["city"], ["building", "tall", "city", "tower", "elevator", "window", "sky"]],
  ["elevator", "elevator", "ascenseur", ["city", "home"], ["building", "stairs", "skyscraper", "button", "up", "down", "hotel"]],
  ["structure", "structure", "structure", ["city", "science"], ["building", "bridge", "tower", "frame", "build", "shape", "skeleton"]],
  ["construction", "construction", "chantier", ["city", "job"], ["build", "builder", "crane", "building", "truck", "helmet", "brick"]],
  ["crane", "crane", "grue", ["city", "job", "animal"], ["construction", "build", "tall", "bird", "truck", "building"]],
  ["brick", "brick", "brique", ["city", "home"], ["wall", "home", "build", "red", "builder", "chimney", "construction"]],
  ["monument", "monument", "monument", ["city", "travel"], ["statue", "tower", "history", "old", "tourist", "museum", "city"]],
  ["fountain", "fountain", "fontaine", ["city", "water"], ["water", "park", "coin", "wish", "statue", "splash"]],
  ["hut", "hut", "hutte", ["home", "nature"], ["cabin", "wood", "forest", "beach", "small", "treehouse"]],

  // People
  ["worker", "worker", "travailleur", ["job"], ["work", "job", "boss", "factory", "office", "builder", "employee"]],
  ["villain", "villain", "méchant", ["story"], ["hero", "superhero", "evil", "bad", "monster", "movie"]],
  ["evil", "evil", "maléfique", ["story", "magic"], ["villain", "witch", "bad", "monster", "dark"]],
  ["athlete", "athlete", "athlète", ["sport", "job"], ["sport", "run", "race", "medal", "strong", "team", "trophy", "gym"]],
  ["audience", "audience", "public", ["music", "art"], ["concert", "show", "clap", "theater", "stage", "crowd", "movie"]],
  ["crowd", "crowd", "foule", ["city"], ["people", "stadium", "concert", "audience", "noise", "city", "busy"]],
  ["guest", "guest", "invité", ["home", "celebration"], ["party", "visit", "hotel", "dinner", "friend", "wedding"]],
  ["adult", "adult", "adulte", ["family"], ["parent", "grown_up", "work", "child", "old", "teenager"]],
  ["grown_up", "grown-up", "grande personne", ["family"], ["adult", "parent", "kid", "work"]],
  ["teenager", "teenager", "adolescent", ["family"], ["phone", "school", "young", "kid", "adult", "music"]],
  ["person", "person", "personne", ["family"], ["people", "man", "woman", "human", "friend"]],
  ["people", "people", "les gens", ["family", "city"], ["person", "crowd", "city", "friend", "family"]],
  ["human", "human", "humain", ["body", "science"], ["person", "body", "brain", "people", "robot"]],
  ["stranger", "stranger", "inconnu", ["family", "city"], ["danger", "new", "people", "friend"]],
  ["champion", "champion", "champion", ["sport"], ["win", "trophy", "medal", "winner", "sport", "team"]],
  ["winner", "winner", "gagnant", ["sport", "game"], ["win", "champion", "trophy", "prize", "medal"]],
  ["fan_supporter", "supporter", "supporter", ["sport"], ["team", "stadium", "football", "flag", "cheer"]],
  ["cheer", "cheer", "acclamer", ["sport", "feeling"], ["clap", "team", "crowd", "happy", "win"]],

  // School, work, money
  ["board", "board", "planche", ["school", "home"], ["chalkboard", "wood", "skateboard", "surf", "board_game", "school"]],
  ["history", "history", "cours d’histoire", ["school", "time"], ["past", "old", "king", "museum", "war", "school", "dinosaur"]],
  ["geography", "geography", "géographie", ["school", "travel"], ["map", "country", "globe", "world", "mountain", "river", "school"]],
  ["project", "project", "projet", ["school", "job"], ["school", "work", "team", "plan", "idea", "homework"]],
  ["dollar", "dollar", "dollar", ["job", "city"], ["money", "coin", "bank", "wallet", "price", "pay"]],
  ["price", "price", "prix", ["job", "city"], ["money", "shop", "sale", "pay", "dollar", "buy", "expensive"]],
  ["expensive", "expensive", "cher", ["city"], ["money", "price", "rich", "gold", "jewel"]],
  ["cheap", "cheap", "bon marché", ["city"], ["money", "price", "sale", "shop"]],
  ["sale", "sale", "soldes", ["city"], ["shop", "price", "buy", "money", "cheap", "store"]],
  ["store", "store", "boutique", ["city"], ["shop", "buy", "money", "market", "mall", "sale"]],
  ["note", "note", "note", ["school", "music"], ["paper", "pen", "music", "write", "notebook", "letter"]],
  ["list", "list", "liste", ["school", "home"], ["paper", "shopping", "write", "pen", "number"]],
  ["shopping", "shopping", "courses", ["city"], ["shop", "mall", "buy", "money", "bag", "list"]],
  ["dictionary", "dictionary", "dictionnaire", ["book", "school"], ["word", "book", "language", "spell", "school", "letter"]],
  ["recipe", "recipe", "recette", ["food", "kitchen"], ["cook", "cake", "kitchen", "book", "bake", "chef", "food"]],
  ["stapler", "stapler", "agrafeuse", ["school", "job"], ["paper", "office", "desk", "school"]],
  ["fact", "fact", "fait", ["school", "science"], ["true", "truth", "science", "book", "information"]],
  ["true", "true", "vrai", ["school"], ["fact", "truth", "right", "false"]],
  ["truth", "truth", "vérité", ["feeling"], ["true", "lie", "honest", "fact", "secret"]],
  ["lie", "lie", "mensonge", ["feeling", "story"], ["truth", "secret", "nose", "bad", "trick"]],
  ["honest", "honest", "honnête", ["feeling"], ["truth", "true", "kind", "friend"]],

  // Food
  ["dough", "dough", "pâte", ["food", "kitchen"], ["bread", "pizza", "flour", "bake", "cookie", "baker"]],
  ["feast", "feast", "festin", ["food", "celebration"], ["food", "dinner", "party", "thanksgiving", "king", "table"]],
  ["pastry", "pastry", "viennoiserie", ["food", "sweet"], ["croissant", "bakery", "cake", "pie", "butter", "dough"]],

  // Clothes and style
  ["sleeve", "sleeve", "manche", ["clothes"], ["shirt", "arm", "jacket", "sweater", "coat"]],
  ["fashion", "fashion", "mode", ["clothes", "art"], ["clothes", "style", "dress", "model", "shoe", "shop"]],
  ["style", "style", "style", ["clothes", "art"], ["fashion", "hair", "clothes", "cool", "dress"]],
  ["model", "model", "mannequin", ["clothes", "job"], ["fashion", "photo", "camera", "dress"]],
  ["wear", "wear", "porter", ["clothes"], ["clothes", "shirt", "hat", "shoe", "dress"]],
  ["outfit", "outfit", "tenue", ["clothes"], ["clothes", "dress", "costume", "fashion", "shoe", "shirt"]],
  ["wig", "wig", "perruque", ["clothes"], ["hair", "costume", "clown", "head"]],
  ["sneakers", "sneakers", "baskets", ["clothes", "sport"], ["shoe", "run", "sport", "sock"]],
  ["protection", "protection", "protection", ["sport", "body"], ["helmet", "shield", "safe", "goggles", "sunscreen", "armor", "guard", "police", "umbrella"]],
  ["armor", "armor", "armure", ["story", "adventure"], ["knight", "shield", "helmet", "metal", "sword", "protection"]],
  ["guard", "guard", "garde", ["job", "story"], ["protection", "castle", "police", "door", "safe", "soldier"]],
  ["safe", "safe", "en sécurité", ["home", "feeling"], ["protection", "home", "lock", "helmet", "security", "danger"]],
  ["safety", "safety", "sécurité", ["home", "job"], ["safe", "helmet", "seatbelt", "protection", "rule", "danger"]],
  ["security", "security", "surveillance", ["job", "tech"], ["guard", "lock", "safe", "password", "camera", "police"]],
  ["seatbelt", "seatbelt", "ceinture de sécurité", ["transport"], ["car", "seat", "safety", "plane", "drive"]],

  // Sport and play
  ["yoga", "yoga", "yoga", ["sport"], ["exercise", "relax", "calm", "stretch", "gym", "breath"]],
  ["stretch", "stretch", "s’étirer", ["sport", "body"], ["yoga", "exercise", "yawn", "arm", "gym"]],
  ["match", "match", "match", ["sport"], ["game", "team", "win", "football", "tennis", "score", "stadium"]],
  ["score", "score", "score", ["sport", "game"], ["goal", "point", "win", "game", "match", "number"]],
  ["point", "point", "point", ["game", "sport"], ["score", "win", "game", "number", "finger"]],
  ["lose", "lose", "perdre", ["sport", "game"], ["win", "game", "sad", "match", "lost"]],
  ["lost", "lost", "perdu", ["adventure", "feeling"], ["map", "lose", "forest", "sad", "maze"]],
  ["maze", "maze", "labyrinthe", ["game", "adventure"], ["lost", "puzzle", "path", "garden", "mouse"]],
  ["prize", "prize", "lot", ["game", "celebration"], ["win", "trophy", "gift", "medal", "winner", "reward"]],
  ["reward", "reward", "récompense", ["game", "feeling"], ["prize", "gift", "win", "treat", "star", "sticker"]],
  ["treat", "treat", "gâterie", ["food", "sweet"], ["candy", "dog", "reward", "cookie", "halloween", "sweet"]],
  ["marble", "marble", "bille", ["toy", "game"], ["ball", "glass", "round", "game", "statue"]],
  ["tag_game", "tag", "loup glacé", ["game", "sport"], ["chase", "run", "playground", "game", "catch", "hide_and_seek"]],
  ["hobby", "hobby", "loisir", ["game", "art"], ["fun", "play", "paint", "music", "collect", "weekend"]],
  ["collect", "collect", "collectionner", ["game"], ["stamp", "coin", "card", "sticker", "shell", "hobby"]],
  ["craft", "craft", "bricolage", ["art"], ["glue", "paper", "scissors", "paint", "art", "make"]],
  ["make", "make", "fabriquer", ["art", "home"], ["build", "craft", "cook", "fix", "create"]],
  ["create", "create", "créer", ["art"], ["make", "art", "idea", "build", "draw", "paint"]],
  ["trick", "trick", "tour de magie", ["magic", "game"], ["magic", "magician", "card", "rabbit", "hat", "skateboard", "joke", "halloween"]],
  ["magician", "magician", "magicien", ["magic", "job"], ["magic", "trick", "hat", "rabbit", "wand", "card", "show"]],
  ["joke", "joke", "blague", ["feeling"], ["funny", "laugh", "clown", "trick", "silly"]],
  ["speed", "speed", "vitesse", ["transport", "sport"], ["fast", "race", "car", "run", "rocket", "slow"]],
  ["fuel", "fuel", "carburant", ["transport"], ["gas", "car", "rocket", "energy", "oil", "fire"]],
  ["gas", "gas", "essence", ["transport", "science"], ["car", "fuel", "oil", "station", "air"]],
  ["tire", "tire", "pneu", ["transport"], ["wheel", "car", "bike", "round", "rubber", "truck"]],
  ["rubber", "rubber", "caoutchouc", ["home"], ["tire", "ball", "eraser", "duck", "boots", "bounce"]],
  ["passenger", "passenger", "passager", ["transport", "travel"], ["bus", "train", "plane", "seat", "ticket", "car", "driver"]],
  ["seat", "seat", "siège", ["home", "transport"], ["chair", "car", "bus", "sit", "seatbelt", "movie", "plane"]],
  ["sit", "sit", "s’asseoir", ["home", "body"], ["chair", "seat", "sofa", "bench", "dog"]],

  // Describing words
  ["wide", "wide", "large", ["shape"], ["big", "long", "river", "road", "open"]],
  ["narrow", "narrow", "étroit", ["shape"], ["thin", "small", "path", "street", "tunnel"]],
  ["thin", "thin", "mince", ["shape"], ["narrow", "paper", "stick", "small", "string"]],
  ["rough", "rough", "rugueux", ["shape"], ["hard", "rock", "bark", "sand", "smooth"]],
  ["noisy", "noisy", "bruyante", ["sound"], ["loud", "noise", "crowd", "drum", "city", "party"]],
  ["serious", "serious", "sérieux", ["feeling"], ["boss", "judge", "teacher", "work", "funny"]],
  ["kind", "kind", "gentil", ["feeling"], ["nice", "friend", "help", "share", "smile", "love", "hug"]],
  ["nice", "nice", "sympa", ["feeling"], ["kind", "friend", "smile", "good", "happy"]],
  ["good", "good", "bon", ["feeling"], ["nice", "win", "happy", "bad"]],
  ["bad", "bad", "mauvais", ["feeling"], ["good", "villain", "angry", "wrong", "sad"]],
  ["mean", "mean", "vilain", ["feeling"], ["bully", "angry", "bad", "kind", "villain"]],
  ["bully", "bully", "harceleur", ["school", "feeling"], ["mean", "school", "playground", "sad", "bad"]],
  ["shy", "shy", "timide", ["feeling"], ["quiet", "nervous", "hide", "new"]],
  ["weak", "weak", "faible", ["body"], ["strong", "tired", "sick", "small"]],
  ["poor", "poor", "pauvre", ["feeling"], ["money", "rich", "sad", "hungry"]],
  ["bitter", "bitter", "amer", ["food"], ["coffee", "lemon", "sour", "taste", "chocolate"]],
  ["ugly", "ugly", "laid", ["feeling"], ["monster", "beautiful", "duck"]],
  ["spooky", "spooky", "effrayante", ["night", "magic"], ["ghost", "halloween", "scary", "haunted_house", "night", "skeleton", "witch"]],
  ["normal", "normal", "normal", ["feeling"], ["weird", "boring", "same"]],
  ["same", "same", "pareil", ["game"], ["twin", "different", "copy", "match", "normal"]],
  ["different", "different", "différent", ["game"], ["same", "new", "weird", "special"]],
  ["twin", "twin", "jumeau", ["family"], ["brother", "sister", "same", "baby", "pair"]],
  ["special", "special", "spécial", ["feeling", "celebration"], ["birthday", "gift", "surprise", "magic"]],
  ["famous", "famous", "célèbre", ["job", "music"], ["star", "movie", "singer", "actor", "rich", "photo"]],
  ["free", "free", "libre", ["feeling"], ["bird", "fly", "weekend", "gift", "freedom"]],
  ["freedom", "freedom", "liberté", ["feeling"], ["free", "bird", "fly", "flag", "peace"]],
  ["open", "open", "ouvert", ["home"], ["door", "window", "box", "shop", "gift", "close"]],
  ["close", "close", "fermer", ["home"], ["door", "open", "window", "lock", "eyes", "shop"]],
  ["closed", "closed", "fermée", ["home", "city"], ["door", "shop", "lock", "night", "open"]],
  ["electric", "electric", "électrique", ["tech", "science"], ["electricity", "car", "guitar", "lightning", "battery", "plug"]],
  ["digital", "digital", "numérique", ["tech"], ["computer", "phone", "screen", "clock", "camera", "online"]],
  ["golden", "golden", "doré", ["color"], ["gold", "yellow", "crown", "sun", "treasure", "shiny"]],
  ["colorful", "colorful", "coloré", ["color", "art"], ["rainbow", "color", "paint", "flower", "parrot", "crayon", "bright"]],
  ["invisible", "invisible", "invisible", ["magic", "story"], ["ghost", "magic", "hide", "secret", "superhero", "air"]],
  ["boring", "boring", "ennuyeux", ["feeling"], ["bored", "normal", "homework", "slow"]],

  // Ideas and feelings
  ["joy", "joy", "joie", ["feeling"], ["happy", "smile", "laugh", "love", "fun", "party"]],
  ["anger", "anger", "colère", ["feeling"], ["angry", "red", "shout", "mad"]],
  ["mad", "mad", "fâché", ["feeling"], ["angry", "anger", "shout", "red", "crazy"]],
  ["crazy", "crazy", "fou", ["feeling"], ["silly", "funny", "weird", "mad", "wild"]],
  ["silly", "silly", "rigolo", ["feeling"], ["funny", "clown", "joke", "laugh", "crazy"]],
  ["past", "past", "passé", ["time"], ["history", "old", "yesterday", "memory", "future"]],
  ["care", "care", "prendre soin", ["family", "feeling"], ["love", "help", "nurse", "parent", "kind", "pet"]],
  ["trust", "trust", "confiance", ["feeling", "family"], ["friend", "truth", "secret", "family", "honest"]],
  ["mystery", "mystery", "mystère", ["story"], ["detective", "clue", "secret", "puzzle", "ghost", "question"]],
  ["problem", "problem", "problème", ["school"], ["math", "question", "answer", "fix", "help", "puzzle"]],
  ["mistake", "mistake", "erreur", ["school"], ["wrong", "eraser", "oops", "sorry", "test"]],
  ["oops", "oops", "oups", ["sound", "feeling"], ["mistake", "fall", "sorry"]],
  ["sorry", "sorry", "pardon", ["feeling"], ["oops", "mistake", "sad", "hug"]],
  ["success", "success", "réussite", ["job", "feeling"], ["win", "goal", "trophy", "happy", "work", "champion"]],
  ["failure", "failure", "échec", ["feeling"], ["lose", "mistake", "sad", "test", "try"]],
  ["try", "try", "essayer", ["feeling", "game"], ["practice", "hard", "learn"]],
  ["practice", "practice", "entraînement", ["sport", "music", "school"], ["train", "piano", "sport", "learn", "coach", "try"]],
  ["victory", "victory", "victoire", ["sport", "game"], ["win", "champion", "trophy", "medal", "party"]],
  ["challenge", "challenge", "défi", ["game", "sport"], ["game", "hard", "puzzle", "race", "win", "try"]],
  ["plan", "plan", "plan", ["job", "school"], ["map", "idea", "project", "goal", "list", "build"]],
  ["law", "law", "loi", ["job", "city"], ["rule", "police", "judge", "lawyer", "court"]],
  ["court", "court", "tribunal", ["job", "city", "sport"], ["judge", "law", "lawyer", "tennis", "basketball"]],
  ["right", "right", "juste", ["school"], ["correct", "answer", "wrong", "true"]],
  ["correct", "correct", "correct", ["school"], ["right", "answer", "true", "test", "grade"]],
  ["wrong", "wrong", "faux", ["school"], ["mistake", "right", "bad", "false", "answer"]],
  ["false", "false", "pas vrai", ["school"], ["true", "lie", "wrong", "fake"]],
  ["fake", "fake", "imitation", ["story"], ["false", "lie", "copy", "mask", "costume"]],
  ["copy", "copy", "copie", ["school", "tech"], ["same", "paper", "printer", "twin", "fake"]],
  ["choice", "choice", "choix", ["game"], ["choose", "menu"]],
  ["choose", "choose", "choisir", ["game"], ["choice"]],
  ["chance", "chance", "hasard", ["game"], ["luck", "dice", "coin", "lucky"]],
  ["lucky", "lucky", "chanceux", ["game", "feeling"], ["luck", "clover", "chance", "win", "dice"]],
  ["clover", "clover", "trèfle", ["plant", "nature"], ["luck", "lucky", "green", "grass"]],
  ["punishment", "punishment", "punition", ["school", "family"], ["bad", "rule", "parent", "teacher"]],
  ["silence", "silence", "silence", ["sound"], ["quiet", "library", "night", "noise"]],
  ["size", "size", "taille", ["shape", "clothes"], ["big", "small", "tall", "measure", "shoe"]],
  ["name", "name", "nom", ["family", "school"], ["person", "word", "letter", "friend", "card"]],
  ["beauty", "beauty", "beauté", ["feeling", "art"], ["beautiful", "flower", "princess", "pretty"]],
  ["pretty", "pretty", "joli", ["feeling"], ["beautiful", "flower", "dress", "cute"]],
  ["strength", "strength", "force", ["body", "sport"], ["strong", "muscle", "power", "gym", "superhero"]],
  ["power", "power", "pouvoir", ["science", "magic"], ["energy", "electricity", "strong", "superhero", "king", "magic"]],
  ["courage", "courage", "courage", ["feeling"], ["brave", "hero", "lion", "fear", "knight"]],
  ["patience", "patience", "patience", ["feeling"], ["wait", "calm", "slow", "time"]],
  ["wait", "wait", "attendre", ["time"], ["patience", "bus", "time", "slow"]],
  ["kindness", "kindness", "gentillesse", ["feeling"], ["kind", "help", "share", "love", "smile"]],
  ["teamwork", "teamwork", "travail d’équipe", ["sport", "job"], ["team", "help", "share", "together", "sport"]],
  ["together", "together", "ensemble", ["family"], ["team", "friend", "family", "share", "hug"]],
  ["competition", "competition", "compétition", ["sport", "game"], ["race", "win", "game", "prize", "match", "challenge"]],
  ["tradition", "tradition", "tradition", ["holiday", "family"], ["holiday", "family", "christmas", "old", "culture"]],
  ["culture", "culture", "culture", ["art", "travel"], ["art", "music", "tradition", "country", "language", "food"]],
  ["anniversary", "anniversary", "anniversaire de mariage", ["celebration", "family"], ["wedding", "love", "party", "cake", "year", "gift"]],
  ["design", "design", "design", ["art"], ["draw", "art", "fashion", "pattern", "shape", "plan"]],
  ["pattern", "pattern", "motif", ["art", "shape"], ["stripe", "circle", "shape", "design", "color", "fabric"]],
  ["stripe", "stripe", "rayure", ["shape", "art"], ["zebra", "tiger", "pattern", "shirt"]],
  ["system", "system", "système", ["science", "tech"], ["computer", "solar", "plan", "machine", "rule"]],
  ["balance", "balance", "équilibre", ["sport", "science"], ["scale", "gymnastics", "bike", "rope", "yoga"]],
  ["scale", "scale", "pèse-personne", ["science", "kitchen"], ["weigh", "heavy", "balance", "fish", "music"]],
  ["weigh", "weigh", "peser", ["science"], ["scale", "heavy", "light"]],
  ["change", "change", "changement", ["time"], ["new", "different", "grow", "money", "coin", "season"]],
  ["growth", "growth", "croissance", ["nature", "body"], ["grow", "plant", "tall", "seed", "change"]],
  ["gymnastics", "gymnastics", "gymnastique", ["sport"], ["flip", "jump", "balance", "sport", "trampoline"]],
  ["movie_night", "movie night", "soirée cinéma", ["night", "art"], ["movie", "popcorn", "night", "sofa", "family", "tv"]],
  ["game_night", "game night", "soirée jeux", ["night", "game"], ["game", "board_game", "night", "family", "friend", "card"]],
  // Second sweep (held-out audit): more everyday objects, places, weather, clothes and food
  ["pliers", "pliers", "pince", ["home", "job"], ["tool", "wire", "toolbox", "wrench", "fix", "metal"]],
  ["coaster", "coaster", "sous-verre", ["home"], ["cup", "table", "drink", "glass"]],
  ["doormat", "doormat", "paillasson", ["home"], ["door", "shoe", "mud", "home"]],
  ["lampshade", "lampshade", "abat-jour", ["home", "light"], ["lamp", "light", "bulb", "room"]],
  ["wheelbarrow", "wheelbarrow", "brouette", ["garden", "job"], ["garden", "dirt", "wheel", "builder", "shovel", "farm"]],
  ["lawnmower", "lawnmower", "tondeuse", ["garden", "home"], ["grass", "garden", "noise", "summer", "cut"]],
  ["sprinkler", "sprinkler", "arroseur", ["garden", "water"], ["water", "grass", "garden", "summer", "splash", "hose"]],
  ["thermos", "thermos", "thermos", ["drink", "travel"], ["coffee", "tea", "hot", "soup", "picnic", "bottle"]],
  ["highlighter", "highlighter", "surligneur", ["school"], ["marker", "pen", "yellow", "book", "paper", "school"]],
  ["sharpener", "sharpener", "taille-crayon", ["school"], ["pencil", "sharp", "school", "crayon", "desk"]],
  ["binder", "binder", "classeur", ["school", "job"], ["paper", "folder", "school", "notebook", "office"]],
  ["paperclip", "paperclip", "trombone", ["school", "job"], ["paper", "office", "metal", "desk"]],
  ["webcam", "webcam", "webcam", ["tech"], ["camera", "computer", "video", "meeting", "laptop", "screen"]],
  ["tripod", "tripod", "trépied", ["tech", "art"], ["camera", "photo", "video"]],
  ["lantern", "lantern", "lanterne", ["light", "adventure"], ["light", "candle", "camping", "night", "flashlight", "dark"]],
  ["compass", "compass", "boussole", ["adventure", "travel"], ["map", "north", "direction", "explore", "hike", "pirate", "lost"]],
  ["north", "north", "nord", ["travel", "cold"], ["compass", "south", "cold", "map", "polar_bear"]],
  ["south", "south", "sud", ["travel", "hot"], ["north", "compass", "map", "warm"]],
  ["direction", "direction", "direction", ["travel"], ["compass", "map", "road", "path"]],
  ["binoculars", "binoculars", "jumelles", ["adventure", "nature"], ["bird", "see", "explore", "eyes"]],
  ["telescope", "telescope", "télescope", ["space", "science"], ["star", "space", "planet", "moon", "night", "sky", "astronaut"]],
  ["microscope", "microscope", "microscope", ["science"], ["science", "scientist", "small", "germ", "lab"]],
  ["lab", "lab", "laboratoire", ["science"], ["science", "scientist", "experiment", "microscope", "potion"]],
  ["experiment", "experiment", "expérience scientifique", ["science", "school"], ["science", "scientist", "lab", "test", "potion"]],
  ["goalkeeper", "goalkeeper", "gardien de but", ["sport"], ["goal", "soccer", "football", "glove", "ball"]],
  ["jersey", "jersey", "maillot", ["sport", "clothes"], ["team", "shirt", "number", "football", "soccer", "sport"]],
  ["treadmill", "treadmill", "tapis de course", ["sport"], ["run", "gym", "exercise", "jog", "machine"]],
  ["dumbbell", "dumbbell", "haltère", ["sport"], ["gym", "muscle", "heavy", "exercise", "strong", "lift"]],
  ["frisbee", "frisbee", "frisbee", ["toy", "sport"], ["throw", "catch", "dog", "park", "beach", "round"]],
  ["boomerang", "boomerang", "boomerang", ["toy", "sport"], ["throw", "catch", "kangaroo"]],
  ["yoyo", "yo-yo", "yo-yo", ["toy"], ["toy", "string", "up", "down", "trick"]],
  ["hula_hoop", "hula hoop", "cerceau", ["toy", "sport"], ["circle", "dance", "round", "playground"]],
  ["snorkel", "snorkel", "tuba", ["ocean", "sport"], ["swim", "fish", "ocean", "goggles", "reef", "dive", "mask"]],
  ["flippers", "flippers", "palmes", ["ocean", "sport"], ["swim", "dive", "foot", "snorkel", "duck", "penguin", "seal"]],
  ["dock", "dock", "quai", ["ocean", "transport"], ["boat", "harbor", "ship", "pier", "water", "fish"]],
  ["pier", "pier", "jetée", ["ocean"], ["beach", "boat", "dock", "fish", "sea", "walk"]],
  ["raft", "raft", "radeau", ["water", "adventure"], ["river", "boat", "float", "wood", "paddle", "island"]],
  ["float", "float", "flotter", ["water"], ["boat", "swim", "raft", "balloon", "duck", "water"]],
  ["container", "container", "conteneur", ["transport", "home"], ["box", "ship", "truck", "jar", "cargo"]],
  ["cargo", "cargo", "cargaison", ["transport"], ["ship", "truck", "container", "plane", "box"]],
  ["bulldozer", "bulldozer", "bulldozer", ["transport", "job"], ["construction", "dirt", "truck", "build", "yellow", "crane"]],
  ["trailer", "trailer", "remorque", ["transport"], ["truck", "car", "camping", "movie", "horse"]],
  ["caravan", "caravan", "caravane", ["transport", "travel"], ["camping", "trip", "car", "holiday", "road"]],
  ["brake", "brake", "frein", ["transport"], ["car", "bike", "slow", "wheel", "pedal"]],
  ["pedal", "pedal", "pédale", ["transport"], ["bike", "foot", "car", "brake", "piano"]],
  ["gear", "gear", "vitesse (engrenage)", ["transport", "tech"], ["bike", "car", "machine", "wheel", "engine"]],
  ["bumper", "bumper", "pare-chocs", ["transport"], ["car", "truck"]],
  ["driveway", "driveway", "allée", ["home", "transport"], ["car", "garage", "home", "road", "park"]],
  ["sidewalk", "sidewalk", "trottoir", ["city"], ["street", "walk", "road", "city", "chalk"]],
  ["crosswalk", "crosswalk", "passage piéton", ["city", "transport"], ["street", "walk", "traffic", "road", "stripe"]],
  ["hydrant", "hydrant", "bouche d’incendie", ["city", "fire"], ["fire", "water", "firefighter", "street", "dog", "red"]],
  ["porch", "porch", "porche", ["home"], ["home", "door", "chair", "summer", "step"]],
  ["patio", "patio", "terrasse", ["home", "garden"], ["garden", "table", "chair", "summer", "barbecue"]],
  ["barbecue", "barbecue", "grillade", ["food", "hot"], ["grill", "burger", "summer", "sausage", "fire", "garden", "steak"]],
  ["shed", "shed", "abri de jardin", ["garden", "home"], ["garden", "tool", "wood", "bike", "shovel"]],
  ["fireplace", "fireplace", "cheminée (foyer)", ["home", "fire"], ["fire", "warm", "chimney", "wood", "christmas", "santa", "winter"]],
  ["windmill", "windmill", "moulin à vent", ["farm", "nature"], ["wind", "farm", "flour", "energy"]],
  ["meadow", "meadow", "prairie", ["nature"], ["grass", "flower", "field", "cow", "butterfly"]],
  ["horizon", "horizon", "horizon", ["sky", "nature"], ["sky", "sunset", "sea", "sunrise"]],
  ["dune", "dune", "dune", ["nature"], ["sand", "desert", "beach", "wind", "camel"]],
  ["oasis", "oasis", "oasis", ["nature"], ["desert", "water", "palm_tree", "camel", "sand"]],
  ["peak", "peak", "sommet", ["nature"], ["mountain", "high", "snow", "climb"]],
  ["slope", "slope", "pente", ["nature", "sport"], ["hill", "ski", "mountain", "snow", "slide"]],
  ["avalanche", "avalanche", "avalanche", ["cold", "nature"], ["snow", "mountain", "danger", "ski", "cold"]],
  ["earthquake", "earthquake", "tremblement de terre", ["nature", "science"], ["shake", "ground", "danger", "volcano", "building", "tsunami"]],
  ["shake", "shake", "secouer", ["body"], ["earthquake", "milkshake", "hand", "dance", "cold"]],
  ["tsunami", "tsunami", "tsunami", ["ocean", "nature"], ["wave", "ocean", "earthquake", "danger", "water"]],
  ["flood", "flood", "inondation", ["water", "weather"], ["rain", "water", "river", "storm", "wet"]],
  ["drought", "drought", "sécheresse", ["weather", "hot"], ["dry", "hot", "desert", "rain", "sun"]],
  ["hail", "hail", "grêle", ["weather", "cold"], ["ice", "storm", "rain", "cold", "snow"]],
  ["blizzard", "blizzard", "blizzard", ["weather", "cold"], ["snow", "storm", "wind", "cold", "winter"]],
  ["breeze", "breeze", "brise", ["weather"], ["wind", "cool", "beach", "summer", "air"]],
  ["temperature", "temperature", "température", ["weather", "science"], ["hot", "cold", "thermometer", "weather", "fever"]],
  ["forecast", "forecast", "météo (prévisions)", ["weather"], ["weather", "rain", "sun", "tv", "news", "storm"]],
  ["earmuffs", "earmuffs", "cache-oreilles", ["clothes", "cold"], ["ear", "cold", "winter", "warm", "snow"]],
  ["beanie", "beanie", "bonnet", ["clothes", "cold"], ["hat", "winter", "cold", "head", "wool"]],
  ["poncho", "poncho", "poncho", ["clothes"], ["rain", "raincoat", "wool"]],
  ["cardigan", "cardigan", "gilet", ["clothes"], ["sweater", "button", "wool", "warm", "grandma"]],
  ["vest", "vest", "veste sans manches", ["clothes"], ["jacket", "shirt", "suit", "sweater"]],
  ["leggings", "leggings", "legging", ["clothes", "sport"], ["pants", "yoga", "dance", "sport"]],
  ["gown", "gown", "robe de soirée", ["clothes"], ["dress", "princess", "ball", "wedding", "queen"]],
  ["robe", "robe", "peignoir", ["clothes", "home"], ["bath", "towel", "slippers", "morning", "pajamas"]],
  ["tiara", "tiara", "diadème", ["clothes", "story"], ["princess", "crown", "queen", "jewel", "wedding"]],
  ["lipstick", "lipstick", "rouge à lèvres", ["clothes", "body"], ["lip", "red", "kiss", "makeup", "mirror"]],
  ["makeup", "makeup", "maquillage", ["clothes", "art"], ["lipstick", "face", "mirror", "clown", "brush"]],
  ["lotion", "lotion", "crème hydratante", ["body", "home"], ["skin", "sunscreen", "soft", "hand", "bathroom"]],
  ["hairdryer", "hairdryer", "sèche-cheveux", ["home", "body"], ["hair", "hot", "wind", "bathroom", "noise", "dry"]],
  ["pillowcase", "pillowcase", "taie d’oreiller", ["home"], ["pillow", "bed", "sleep", "sheet"]],
  ["sheet", "sheet", "drap", ["home"], ["bed", "pillow", "paper", "white", "blanket", "ghost"]],
  ["crib", "crib", "lit de bébé", ["home", "family"], ["baby", "bed", "sleep", "blanket"]],
  ["cradle", "cradle", "berceau", ["home", "family"], ["baby", "rock", "sleep", "bed"]],
  ["bookcase", "bookcase", "bibliothèque (meuble)", ["home", "book"], ["book", "shelf", "library", "wood", "room"]],
  ["chandelier", "chandelier", "lustre", ["home", "light"], ["light", "ceiling", "candle", "castle", "jewel"]],
  ["thermostat", "thermostat", "thermostat", ["home", "tech"], ["heater", "temperature", "warm", "cold", "wall"]],
  ["cutlery", "cutlery", "couverts", ["kitchen"], ["fork", "knife", "spoon", "table", "dinner", "drawer"]],
  ["colander", "colander", "passoire", ["kitchen"], ["pasta", "noodle", "water", "sink", "kitchen"]],
  ["grater", "grater", "râpe", ["kitchen"], ["cheese", "carrot", "kitchen", "sharp"]],
  ["peeler", "peeler", "éplucheur", ["kitchen"], ["potato", "carrot", "apple", "kitchen", "knife"]],
  ["rolling_pin", "rolling pin", "rouleau à pâtisserie", ["kitchen"], ["dough", "pie", "cookie", "bake", "flour", "pizza"]],
  ["oven_mitt", "oven mitt", "gant de cuisine", ["kitchen"], ["oven", "hot", "glove", "bake", "kitchen", "mitten"]],
  ["tablecloth", "tablecloth", "nappe", ["home", "kitchen"], ["table", "dinner", "picnic", "napkin", "fabric"]],
  ["saucer", "saucer", "soucoupe", ["kitchen"], ["cup", "tea", "plate", "alien", "coffee"]],
  ["pitcher", "pitcher", "carafe", ["kitchen", "drink"], ["water", "juice", "lemonade", "glass", "milk", "baseball"]],
  ["jug", "jug", "pichet", ["kitchen", "drink"], ["milk", "water", "juice", "pitcher", "glass"]],
  ["flask", "flask", "gourde", ["drink", "science"], ["water", "bottle", "drink", "hike", "lab", "potion"]],
  ["ice_cube", "ice cube", "cube de glace", ["cold", "drink"], ["ice", "cold", "drink", "fridge", "lemonade", "water"]],
  ["pantry", "pantry", "garde-manger", ["kitchen", "home"], ["food", "kitchen", "shelf", "cookie", "jar"]],
  ["cinnamon", "cinnamon", "cannelle", ["food", "sweet"], ["apple", "cake", "spice", "cookie", "christmas", "sugar"]],
  ["spice", "spice", "aromate", ["food"], ["pepper", "salt", "curry", "cinnamon", "spicy", "cook"]],
  ["mint", "mint", "menthe", ["food", "plant"], ["green", "toothpaste", "gum", "tea", "chocolate", "fresh", "candy"]],
  ["ginger", "ginger", "gingembre", ["food", "plant"], ["cookie", "spice", "tea", "gingerbread", "spicy"]],
  ["gingerbread", "gingerbread", "pain d’épices", ["food", "sweet", "holiday"], ["cookie", "christmas", "ginger", "home", "man"]],
  ["basil", "basil", "basilic", ["food", "plant"], ["pizza", "pasta", "tomato", "green", "herb"]],
  ["herb", "herb", "herbe aromatique", ["food", "plant"], ["basil", "mint", "garden", "green", "cook", "spice"]],
  ["vinegar", "vinegar", "vinaigre", ["food"], ["salad", "sour", "oil", "pickle", "chips"]],
  ["tofu", "tofu", "tofu", ["food"], ["vegetable", "white", "soup", "noodle"]],
  ["oats", "oats", "flocons d’avoine", ["food"], ["porridge", "breakfast", "cereal", "horse", "cookie", "milk"]],
  ["crepe", "crepe", "crêpe bretonne", ["food", "sweet"], ["pancake", "france", "sugar", "jam", "chocolate", "breakfast"]],
  ["scone", "scone", "scone", ["food", "sweet"], ["tea", "jam", "cream", "bakery", "muffin"]],
  ["fudge", "fudge", "caramel mou", ["food", "sweet"], ["chocolate", "candy", "sweet", "sugar", "caramel"]],
  ["gum", "gum", "chewing-gum", ["food", "sweet"], ["chew", "bubble", "mint", "candy", "sticky"]],
  ["chew", "chew", "mâcher", ["food", "body"], ["gum", "tooth", "eat", "dog", "bone"]],
  ["sorbet", "sorbet", "sorbet", ["food", "sweet", "cold"], ["ice_cream", "fruit", "cold", "lemon", "dessert"]],
  ["hummus", "hummus", "houmous", ["food"], ["bread", "garlic"]],
  ["toffee", "toffee", "caramel dur", ["food", "sweet"], ["caramel", "candy", "sweet", "sticky", "sugar"]],
  ["lentil", "lentil", "lentille", ["food"], ["soup", "bean", "vegetable", "rice"]],
  ["cellar", "cellar", "cave (sous-sol)", ["home"], ["basement", "dark", "stairs", "home"]],
  ["orchard", "orchard", "verger", ["farm", "plant"], ["apple", "tree", "fruit", "farm", "pear", "cherry"]],
  ["vineyard", "vineyard", "vignoble", ["farm", "plant"], ["grape", "farm", "france", "field"]],
  ["projector", "projector", "projecteur", ["tech", "school"], ["movie", "screen", "light", "presentation", "school"]],
  ["steering_wheel", "steering wheel", "volant", ["transport"], ["car", "drive", "driver", "wheel"]],
  ["bandana", "bandana", "bandana", ["clothes"], ["scarf", "cowboy", "pirate", "head", "neck"]],
  ["chili", "chili", "piment", ["food", "hot"], ["spicy", "hot", "pepper", "red", "taco"]],
  ["padlock", "padlock", "cadenas", ["home"], ["lock", "key", "locker", "chain", "gate", "metal"]],
  ["stopwatch", "stopwatch", "chronomètre", ["sport", "time"], ["time", "race", "run", "clock", "fast", "timer"]],
  ["lifejacket", "life jacket", "gilet de sauvetage", ["water", "transport"], ["boat", "swim", "safe", "water", "lifeguard", "orange"]],
  ["clipboard", "clipboard", "porte-bloc", ["school", "job"], ["paper", "list", "coach", "doctor", "pen"]],
  ["pinwheel", "pinwheel", "moulin à vent jouet", ["toy"], ["wind", "color", "toy"]],
  ["barbell", "barbell", "barre d’haltères", ["sport"], ["gym", "lift", "heavy", "muscle", "strong"]],
  ["lift", "lift", "soulever", ["sport", "body"], ["heavy", "gym", "strong", "muscle"]]
];

/** Links between existing words that were missing (each is a first-thought association). */
export const ADDED_LINKS_5 = [
  ["zoo", "bear"], ["zoo", "monkey"], ["zoo", "elephant"], ["zoo", "lion"], ["zoo", "giraffe"], ["zoo", "zebra"], ["zoo", "tiger"], ["zoo", "penguin"], ["zoo", "panda"],
  ["fur", "bear"], ["fur", "fox"], ["fur", "wolf"], ["fur", "rabbit"], ["fur", "dog"],
  ["night", "movie"], ["night", "game"], ["night", "party"], ["computer", "game"], ["computer", "work"], ["computer", "video_game"],
  ["oven", "pan"], ["oven", "pizza"], ["oven", "hot"], ["cake", "oven"], ["stove", "pan"], ["stove", "pot"], ["stove", "cook"], ["stove", "kitchen"],
  ["sun", "sunglasses"], ["sun", "sunscreen"], ["tree", "wood"], ["tree", "family"], ["picture", "frame"],
  ["phone", "charger"], ["phone", "app"], ["glasses", "eyes"], ["swim", "goggles"], ["ski", "goggles"],
  // Every concept keeps at least five links.
  ["cushion", "living_room"], ["cushion", "bed"], ["agent", "movie"], ["agent", "hero"], ["heaven", "star"], ["heaven", "dream"], ["jail_bars", "zoo"], ["jail_bars", "lock"], ["steal", "bank"], ["steal", "treasure"], ["grown_up", "tall"], ["grown_up", "job"], ["stranger", "door"], ["stranger", "scary"], ["cheap", "market"], ["cheap", "buy"], ["stapler", "paperclip"], ["stapler", "folder"], ["model", "plane"], ["model", "clothes"], ["wig", "actor"], ["wig", "halloween"], ["sneakers", "jog"], ["sneakers", "basketball"], ["good", "kind"], ["good", "smile"], ["shy", "friend"], ["shy", "school"], ["weak", "muscle"], ["weak", "baby"], ["poor", "help"], ["poor", "coin"], ["ugly", "frog"], ["ugly", "face"], ["ugly", "witch"], ["normal", "day"], ["normal", "school"], ["boring", "lesson"], ["boring", "wait"], ["anger", "fight"], ["anger", "storm"], ["oops", "broken"], ["oops", "glass"], ["oops", "funny"], ["sorry", "friend"], ["sorry", "cry"], ["right", "hand"], ["right", "rule"], ["false", "test"], ["false", "answer"], ["choice", "question"], ["choice", "answer"], ["choice", "game"], ["choose", "menu"], ["choose", "game"], ["choose", "question"], ["choose", "player"], ["chance", "game"], ["chance", "win"], ["clover", "bee"], ["clover", "field"], ["punishment", "prison"], ["punishment", "homework"], ["silence", "secret"], ["silence", "sleep"], ["beauty", "rose"], ["beauty", "art"], ["patience", "teacher"], ["patience", "fish"], ["wait", "station"], ["wait", "late"], ["weigh", "fish"], ["weigh", "flour"], ["coaster", "tea"], ["coaster", "coffee"], ["doormat", "boots"], ["doormat", "dirt"], ["lampshade", "bedroom"], ["lampshade", "fabric"], ["paperclip", "folder"], ["tripod", "picture"], ["tripod", "telescope"], ["south", "beach"], ["direction", "street"], ["direction", "arrow"], ["binoculars", "spy"], ["binoculars", "telescope"], ["boomerang", "stick"], ["boomerang", "fly"], ["boomerang", "wood"], ["hula_hoop", "toy"], ["hula_hoop", "fun"], ["bumper", "traffic"], ["bumper", "road"], ["bumper", "wheel"], ["windmill", "wheat"], ["windmill", "field"], ["horizon", "ocean"], ["horizon", "boat"], ["peak", "hike"], ["peak", "cliff"], ["poncho", "coat"], ["poncho", "umbrella"], ["vest", "coat"], ["vest", "clothes"], ["leggings", "run"], ["leggings", "clothes"], ["pillowcase", "bedroom"], ["pillowcase", "laundry"], ["crib", "toy"], ["crib", "bedroom"], ["cradle", "blanket"], ["cradle", "song"], ["grater", "pizza"], ["grater", "pasta"], ["tofu", "rice"], ["tofu", "food"], ["hummus", "carrot"], ["hummus", "snack"], ["hummus", "food"], ["lentil", "pea"], ["lentil", "food"], ["cellar", "cold"], ["cellar", "spider"], ["vineyard", "sun"], ["vineyard", "farmer"], ["steering_wheel", "truck"], ["steering_wheel", "bus"], ["pinwheel", "windmill"], ["pinwheel", "garden"], ["pinwheel", "rainbow"]
];

export const ADDED_PHRASES_5 = {
  en: [["game", "night"], ["movie", "night"], ["solar", "system"], ["solar", "panel"], ["picture", "frame"], ["family", "tree"], ["tape", "measure"], ["post_office", "mail"]],
  fr: [["solar", "system"], ["solar", "panel"]]
};

export const ALIASES_5 = {
  en: {
    skool: "school", friendly: "friend", jail: "prison", parcel: "package", faucet: "tap", smartphone: "phone", cellphone: "phone", mobile: "phone",
    tv_show: "show", television: "tv", trashcan: "bin", "trash can": "bin", dustbin: "bin", rubbish: "garbage", lightswitch: "switch",
    earphones: "earbuds", headset: "headphones", mic: "microphone", gamepad: "controller", webpage: "website",
    sunnies: "sunglasses", specs: "glasses", spectacles: "glasses", toque: "hat", trainers: "sneakers", "running shoes": "sneakers",
    pc: "computer", desktop: "computer", notebook_computer: "laptop", applications: "app", application: "app", downloaded: "download",
    protect: "protection", protective: "protection", protecting: "protection", structures: "structure", accessories: "accessory",
    devices: "device", peripherals: "peripheral", constructions: "construction", builder_site: "construction", "building site": "construction",
    jailed: "prison", thieves: "thief", robber: "thief", burglar: "thief", tidy: "clean", germs: "germ", bacteria: "germ",
    sickness: "sick", illness: "sick", ill: "sick", injured: "hurt", injury: "hurt", sore: "pain", ache: "pain", aches: "pain",
    shadows: "shadow", soils: "soil", earth_soil: "soil", grownup: "grown_up", grownups: "grown_up", adults: "adult", humans: "human",
    teens: "teenager", teen: "teenager", persons: "person", folks: "people", strangers: "stranger", guests: "guest", winners: "winner",
    champions: "champion", prizes: "prize", rewards: "reward", treats: "treat", marbles: "marble", hobbies: "hobby", jokes: "joke",
    tricks: "trick", magicians: "magician", tires: "tire", tyre: "tire", tyres: "tire", passengers: "passenger", seats: "seat",
    sleeves: "sleeve", outfits: "outfit", wigs: "wig", recipes: "recipe", mistakes: "mistake", problems: "problem", mysteries: "mystery",
    laws: "law", choices: "choice", names: "name", patterns: "pattern", stripes: "stripe", systems: "system", traditions: "tradition",
    cultures: "culture", feasts: "feast", pastries: "pastry", lists: "list", notes: "note", dollars: "dollar", prices: "price",
    sales: "sale", stores: "store", stamps: "stamp", envelopes: "envelope", packages: "package", deliveries: "delivery", monitors: "monitor",
    speakers: "speaker", cables: "cable", wires: "wire", plugs: "plug", switches: "switch", bulbs: "bulb", cushions: "cushion",
    frames: "frame", lids: "lid", spatulas: "spatula", whisks: "whisk", ladles: "ladle", stools: "stool", benches: "bench", needles: "needle",
    hooks: "hook", screws: "screw", screwdrivers: "screwdriver", wrenches: "wrench", drills: "drill", saws: "saw", rakes: "rake",
    hoses: "hose", chains: "chain", petals: "petal", pebbles: "pebble", icebergs: "iceberg", bricks: "brick", cranes: "crane",
    fountains: "fountain", monuments: "monument", temples: "temple", prisons: "prison", highways: "highway", skyscrapers: "skyscraper",
    elevators: "elevator", lift: "elevator", motorway: "highway", freeway: "highway", satellites: "satellite", antennas: "antenna",
    drones: "drone", gadgets: "gadget", apps: "app", websites: "website", passwords: "password", files: "file", documents: "document",
    sensors: "sensor", chips: "chips", viruses: "virus", hackers: "hacker", spies: "spy", detectives: "detective", clues: "clue", hints: "hint",
    emojis: "emoji", texts: "text", texting: "text", chatting: "chat", notifications: "notification", timers: "timer", channels: "channel",
    magazines: "magazine", pages: "page", podcasts: "podcast", selfies: "selfie", consoles: "console", controllers: "controller",
    microphones: "microphone", headphone: "headphones", earbud: "earbuds", laptops: "laptop", pills: "pill", bandages: "bandage",
    fevers: "fever", coughs: "cough", coughing: "cough", throats: "throat", pains: "pain", headaches: "headache", tongues: "tongue",
    lung: "lungs", breathe: "breath", breathing: "breath", spines: "spine", backs: "back", chests: "chest"
  },
  fr: {
    portable: "phone", "téléphone portable": "phone", ordi: "computer", pc: "computer", appli: "app", application: "app",
    voleuse: "thief", cambrioleur: "thief", écouteur: "earbuds", "lunettes de piscine": "goggles", "lunettes de ski": "goggles"
  }
};

/** Real words the speller knows (never "corrected" into another word), even without links. */
export const EXTRA_WORDS_5 = {
  en: ["tidy", "ache", "sore", "illness", "injury", "robber", "burglar", "jailed", "folks", "texting", "chatting", "breathe", "breathing", "lift", "motorway", "freeway", "tyre", "tyres", "trainers", "spectacles", "specs", "mic", "gamepad", "webpage", "headset", "earphones", "cellphone", "mobile", "smartphone", "television", "rubbish", "dustbin", "trashcan", "parcel", "faucet", "jail", "protect", "protective", "bacteria", "unknown", "usual", "unique", "option", "decide", "vote", "pick", "maybe", "line", "dots", "irish", "shh", "time-out", "goofy", "blush", "troll", "duckling", "great", "first", "best", "two", "again", "train", "information", "spy", "upload", "comfy", "drip", "bar", "pin", "vaccine", "mix", "grow", "brick", "thermometer", "bagpipe", "bagpipes", "abacus", "sweatband", "skipping", "hitchhike", "gps", "wipers", "clutch", "exhaust", "roundabout", "pavement", "curb", "lamppost", "gutter", "drainpipe", "deck", "silo", "prairie", "savanna", "tundra", "lagoon", "bay", "peninsula", "coastline", "ridge", "summit", "gust", "sleet", "dew", "humidity", "galoshes", "balaclava", "overalls", "tights", "blazer", "tuxedo", "kimono", "sari", "turban", "cufflinks", "brooch", "locket", "pendant", "anklet", "mascara", "polish", "deodorant", "tweezers", "curler", "bunk", "recliner", "nightstand", "conditioner", "ventilator", "humidifier", "placemat", "goblet", "cube", "nutmeg", "oregano", "parsley", "paprika", "relish", "quinoa", "muesli", "trackpad", "sticky", "coaster", "hoop", "hula", "skipping", "manhole", "windshield", "headlight", "horn", "container", "stand", "clip", "welcome", "chickpea", "soy", "wine", "cell", "safari", "explode", "crash", "bump", "ufo", "nursery", "crystal", "australia", "mexico", "spin", "return", "save", "carry", "turn", "stop", "far", "left", "way", "pole", "top", "dip", "roll"],
  fr: []
};
