// Curated, age-appropriate association graph used by the Solo bot and spell assistance.
// Each concept: [id, englishLabel, frenchLabel, tags, links]
// Links are undirected (index.js mirrors them), so each pair only needs to be listed once.
export const TAGS = ["sky","weather","space","night","animal","pet","farm","ocean","water","nature","plant","food","sweet","drink","home","family","body","feeling","school","book","story","magic","music","art","color","sport","game","toy","transport","city","job","time","season","holiday","clothes","tech","science","shape","sound","light","fire","cold","hot","celebration","adventure"];

export const CONCEPTS = [
  // Sky, weather, space
  ["sun","sun","soleil",["sky","light","hot"],["moon","sky","day","summer","star","light","beach","hot","sunflower","yellow","space"]],
  ["moon","moon","lune",["sky","night","space"],["sky","night","star","space","rocket","planet","dream","light","astronaut","owl"]],
  ["star","star","étoile",["sky","night","space"],["sky","night","space","planet","wish","light","shine","rocket","shape"]],
  ["sky","sky","ciel",["sky","nature"],["cloud","bird","plane","rainbow","blue","star","kite","fly","space","night","day"]],
  ["cloud","cloud","nuage",["sky","weather"],["rain","sky","storm","white","soft","snow","wind","thunder","plane"]],
  ["rain","rain","pluie",["weather","water","sky"],["cloud","umbrella","puddle","storm","rainbow","water","flower","grow","garden","wet","boots","spring"]],
  ["snow","snow","neige",["weather","cold","season"],["winter","cold","snowman","sled","ice","white","mountain","ski","christmas","snowflake","mitten"]],
  ["storm","storm","orage",["weather","sky","sound"],["thunder","lightning","rain","wind","cloud","scary","loud"]],
  ["rainbow","rainbow","arc-en-ciel",["sky","color","weather"],["rain","color","sun","sky","unicorn","red","purple","cloud"]],
  ["thunder","thunder","tonnerre",["weather","sound"],["lightning","storm","loud","cloud","scary"]],
  ["lightning","lightning","éclair",["weather","light"],["thunder","storm","fast","electricity","bright"]],
  ["wind","wind","vent",["weather","nature"],["kite","storm","leaf","autumn","cloud","sail","blow","cold"]],
  ["umbrella","umbrella","parapluie",["weather"],["rain","wet","boots","puddle","coat"]],
  ["puddle","puddle","flaque",["weather","water"],["rain","boots","mud","splash","wet","jump"]],
  ["snowman","snowman","bonhomme de neige",["cold","season"],["snow","winter","carrot","scarf","cold","hat"]],
  ["snowflake","snowflake","flocon",["cold","weather"],["snow","winter","ice","cold","white"]],
  ["light","light","lumière",["light"],["sun","lamp","bright","dark","candle","star","day","flashlight","shine"]],
  ["night","night","nuit",["night","time"],["moon","star","dark","sleep","dream","bed","owl","bat","day","pajamas"]],
  ["day","day","jour",["time","light"],["sun","night","morning","light","week","time","sky"]],
  ["morning","morning","matin",["time"],["breakfast","sun","day","wake","school","coffee"]],
  ["dark","dark","sombre",["night","color"],["night","black","scary","light","flashlight","shadow","bat"]],
  ["dream","dream","rêve",["night","feeling"],["sleep","night","bed","wish","pillow","moon","unicorn","nightmare"]],
  ["nightmare","nightmare","cauchemar",["night","feeling"],["dream","scary","monster","night","sleep","ghost"]],
  ["sleep","sleep","dormir",["night","home"],["bed","night","dream","pillow","tired","pajamas","blanket","yawn"]],
  ["bed","bed","lit",["home","night"],["sleep","pillow","blanket","night","dream","bedroom","pajamas","teddy_bear"]],
  ["pillow","pillow","oreiller",["home","night"],["bed","sleep","soft","dream","blanket","feather"]],
  ["blanket","blanket","couverture",["home","night"],["bed","pillow","warm","soft","sleep","cozy"]],
  ["space","space","espace",["space","science"],["rocket","planet","star","moon","astronaut","alien","sun","earth"]],
  ["rocket","rocket","fusée",["space","transport"],["space","moon","astronaut","planet","fast","fire","fly","star"]],
  ["planet","planet","planète",["space","science"],["space","earth","star","moon","rocket","alien","round"]],
  ["earth","earth","terre",["space","nature"],["planet","world","space","moon","nature","round"]],
  ["astronaut","astronaut","astronaute",["space","job"],["rocket","space","moon","planet","helmet","star"]],
  ["alien","alien","extraterrestre",["space","story"],["space","planet","green","rocket","monster","ufo"]],

  // Animals
  ["animal","animal","animal",["animal"],["pet","zoo","farm","dog","cat","jungle","fur","paw","tail","forest","wild"]],
  ["pet","pet","animal domestique",["pet","animal","home"],["dog","cat","fish","hamster","rabbit","animal","home","love","fur","paw","tail","vet"]],
  ["dog","dog","chien",["animal","pet"],["cat","bone","bark","puppy","paw","tail","fur","pet","ball","leash","walk","wolf"]],
  ["puppy","puppy","chiot",["animal","pet"],["dog","baby","cute","play","paw"]],
  ["cat","cat","chat",["animal","pet"],["dog","mouse","milk","kitten","paw","tail","fur","pet","whiskers","purr"]],
  ["kitten","kitten","chaton",["animal","pet"],["cat","baby","cute","purr","milk"]],
  ["fur","fur","fourrure",["animal","body"],["dog","cat","bear","soft","warm","rabbit","fox"]],
  ["paw","paw","patte",["animal","body"],["dog","cat","bear","claw","foot"]],
  ["tail","tail","queue",["animal","body"],["dog","cat","monkey","mouse","fox","fish","horse"]],
  ["whiskers","whiskers","moustaches",["animal","body"],["cat","mouse","rabbit"]],
  ["bird","bird","oiseau",["animal","sky"],["nest","wing","feather","fly","egg","sky","tree","sing","owl","parrot","beak"]],
  ["fish","fish","poisson",["animal","ocean","water"],["water","ocean","swim","sea","shark","boat","pet","river","fin","aquarium"]],
  ["horse","horse","cheval",["animal","farm"],["farm","ride","unicorn","knight","cowboy","tail","pony","hay"]],
  ["pony","pony","poney",["animal","farm"],["horse","ride","farm","cute","unicorn"]],
  ["cow","cow","vache",["animal","farm"],["milk","farm","moo","grass","cheese","barn","farmer"]],
  ["pig","pig","cochon",["animal","farm"],["farm","mud","pink","barn","oink"]],
  ["sheep","sheep","mouton",["animal","farm"],["farm","wool","grass","lamb","white"]],
  ["chicken","chicken","poule",["animal","farm"],["egg","farm","feather","nest","chick","rooster","barn"]],
  ["duck","duck","canard",["animal","water","farm"],["pond","feather","swim","farm","wing","bird","quack"]],
  ["lion","lion","lion",["animal"],["tiger","king","roar","zoo","jungle","cat","wild","mane"]],
  ["tiger","tiger","tigre",["animal"],["lion","stripes","jungle","zoo","orange","roar","wild","cat"]],
  ["elephant","elephant","éléphant",["animal"],["zoo","trunk","big","jungle","circus","grey","giraffe"]],
  ["monkey","monkey","singe",["animal"],["banana","jungle","tree","zoo","tail","climb","funny"]],
  ["bear","bear","ours",["animal","nature"],["forest","honey","teddy_bear","fur","cave","paw","big","winter","panda"]],
  ["teddy_bear","teddy bear","nounours",["toy","home"],["bear","toy","soft","bed","hug","cute"]],
  ["frog","frog","grenouille",["animal","water"],["pond","jump","green","prince","fly","river"]],
  ["bee","bee","abeille",["animal","nature"],["honey","flower","buzz","garden","yellow","insect","sting"]],
  ["butterfly","butterfly","papillon",["animal","nature"],["flower","wing","garden","caterpillar","color","fly","spring","insect"]],
  ["caterpillar","caterpillar","chenille",["animal","nature"],["butterfly","leaf","green","insect"]],
  ["insect","insect","insecte",["animal","nature"],["bee","ant","butterfly","ladybug","spider","garden","grass"]],
  ["ant","ant","fourmi",["animal","nature"],["insect","picnic","small","garden","grass"]],
  ["ladybug","ladybug","coccinelle",["animal","nature"],["insect","red","garden","leaf","spots"]],
  ["spider","spider","araignée",["animal","nature"],["web","insect","halloween","scary","legs"]],
  ["owl","owl","hibou",["animal","night","nature"],["night","bird","forest","tree","wise","moon","feather"]],
  ["bat","bat","chauve-souris",["animal","night"],["night","cave","halloween","dark","wing","vampire"]],
  ["wolf","wolf","loup",["animal","nature","story"],["forest","moon","howl","dog","fox","wild"]],
  ["fox","fox","renard",["animal","nature"],["forest","orange","tail","wolf","rabbit","fur"]],
  ["rabbit","rabbit","lapin",["animal","pet"],["carrot","hop","ears","easter","pet","fur","garden","jump"]],
  ["mouse","mouse","souris",["animal","pet"],["cat","cheese","small","tail","squeak","computer"]],
  ["hamster","hamster","hamster",["animal","pet"],["pet","cage","small","wheel","cute"]],
  ["parrot","parrot","perroquet",["animal","pet"],["bird","pirate","talk","jungle","feather","color"]],
  ["snake","snake","serpent",["animal"],["jungle","hiss","long","scary","desert"]],
  ["giraffe","giraffe","girafe",["animal"],["zoo","tall","neck","elephant","zebra"]],
  ["zebra","zebra","zèbre",["animal"],["stripes","zoo","horse","giraffe","black","white"]],
  ["penguin","penguin","pingouin",["animal","cold"],["ice","cold","snow","fish","swim","bird"]],
  ["panda","panda","panda",["animal"],["bear","zoo","black","white","cute"]],
  ["shark","shark","requin",["animal","ocean"],["ocean","fish","teeth","sea","scary","swim","fin"]],
  ["whale","whale","baleine",["animal","ocean"],["ocean","sea","big","dolphin","swim","fish"]],
  ["dolphin","dolphin","dauphin",["animal","ocean"],["ocean","sea","swim","whale","jump","wave","smart"]],
  ["octopus","octopus","pieuvre",["animal","ocean"],["ocean","sea","arms","ink","fish"]],
  ["crab","crab","crabe",["animal","ocean"],["beach","sand","claw","sea","shell"]],
  ["turtle","turtle","tortue",["animal","water"],["shell","slow","sea","beach","pond","green"]],
  ["snail","snail","escargot",["animal","nature"],["slow","shell","garden","rain","leaf"]],
  ["dinosaur","dinosaur","dinosaure",["animal","science","story"],["fossil","big","roar","egg","volcano","dragon","bone","museum"]],

  // Fantasy and stories
  ["dragon","dragon","dragon",["magic","story","fire"],["fire","castle","knight","princess","wing","treasure","dinosaur","scary","cave","magic"]],
  ["unicorn","unicorn","licorne",["magic","story","animal"],["horse","rainbow","magic","horn","princess","fairy","dream","sparkle"]],
  ["castle","castle","château",["story","magic","home"],["king","queen","princess","knight","dragon","tower","crown","prince","sandcastle"]],
  ["princess","princess","princesse",["story","magic"],["prince","castle","crown","queen","king","dress","fairy","dragon"]],
  ["prince","prince","prince",["story","magic"],["princess","castle","king","frog","crown","knight","horse"]],
  ["knight","knight","chevalier",["story","adventure"],["castle","sword","dragon","horse","shield","armor","king","princess"]],
  ["king","king","roi",["story"],["queen","crown","castle","throne","prince","lion","knight","princess"]],
  ["queen","queen","reine",["story"],["king","crown","castle","princess","throne","bee"]],
  ["crown","crown","couronne",["story","clothes"],["king","queen","princess","gold","castle","jewel","prince"]],
  ["pirate","pirate","pirate",["story","adventure","ocean"],["treasure","ship","parrot","island","map","sea","sword","captain"]],
  ["treasure","treasure","trésor",["adventure","story"],["pirate","gold","map","chest","island","dragon","jewel"]],
  ["magic","magic","magie",["magic"],["wizard","wand","fairy","spell","unicorn","witch","dragon","trick","sparkle"]],
  ["wizard","wizard","sorcier",["magic","story"],["magic","wand","spell","hat","witch","castle","owl","beard"]],
  ["witch","witch","sorcière",["magic","story","holiday"],["broom","halloween","hat","spell","cat","wizard","magic","cauldron"]],
  ["fairy","fairy","fée",["magic","story"],["wing","magic","wand","princess","flower","sparkle","tooth","unicorn"]],
  ["wand","wand","baguette magique",["magic"],["wizard","magic","fairy","spell","witch","star"]],
  ["spell","spell","sortilège",["magic"],["magic","wizard","witch","wand","potion"]],
  ["ghost","ghost","fantôme",["story","holiday"],["halloween","scary","boo","haunted_house","white","monster","night"]],
  ["monster","monster","monstre",["story"],["scary","halloween","ghost","nightmare","teeth","dragon","alien","closet"]],
  ["hero","hero","héros",["story","adventure"],["superhero","save","brave","adventure","cape","knight","story"]],
  ["superhero","superhero","super-héros",["story","adventure"],["hero","cape","mask","fly","power","save","strong"]],
  ["cape","cape","cape",["clothes","story"],["superhero","hero","wizard","fly","mask","costume"]],
  ["robot","robot","robot",["tech","toy","science"],["computer","machine","metal","space","alien","toy","battery"]],
  ["adventure","adventure","aventure",["adventure"],["explore","map","treasure","hero","jungle","pirate","camping","journey"]],
  ["map","map","carte",["adventure"],["treasure","pirate","island","adventure","explore","compass"]],
  ["story","story","histoire",["story","book"],["book","once_upon","read","bedtime","fairy","hero","princess","dragon","write"]],
  ["book","book","livre",["book","school"],["read","story","library","page","school","write","teacher","author"]],

  // School
  ["school","school","école",["school"],["teacher","book","pencil","class","student","read","write","library","backpack","homework","friend"]],
  ["teacher","teacher","maîtresse",["school","job"],["school","class","student","book","read","write","board"]],
  ["student","student","élève",["school"],["school","teacher","class","homework","backpack"]],
  ["class","class","classe",["school"],["school","teacher","student","desk","board"]],
  ["pencil","pencil","crayon",["school","art"],["write","draw","paper","eraser","school","pen","color"]],
  ["pen","pen","stylo",["school"],["write","pencil","paper","ink","letter"]],
  ["paper","paper","papier",["school","art"],["pencil","write","draw","book","letter","scissors"]],
  ["eraser","eraser","gomme",["school"],["pencil","mistake","school"]],
  ["read","read","lire",["book","school"],["book","story","library","write","letter","school","word"]],
  ["write","write","écrire",["book","school"],["pencil","pen","read","paper","letter","story","word"]],
  ["library","library","bibliothèque",["book","school","city"],["book","read","quiet","story","school"]],
  ["homework","homework","devoirs",["school"],["school","pencil","teacher","student","math"]],
  ["backpack","backpack","cartable",["school","clothes"],["school","book","camping","hike","lunch"]],
  ["math","math","maths",["school","science"],["number","count","school","homework","plus"]],
  ["word","word","mot",["school","book"],["letter","read","write","book","story"]],
  ["letter","letter","lettre",["school","book"],["write","read","word","alphabet","mail"]],

  // Family, home, feelings
  ["family","family","famille",["family","home"],["mom","dad","baby","brother","sister","home","love","grandma","grandpa"]],
  ["mom","mom","maman",["family"],["dad","family","baby","love","hug","home"]],
  ["dad","dad","papa",["family"],["mom","family","baby","love","hug","home"]],
  ["baby","baby","bébé",["family"],["mom","dad","cry","small","family","bottle","cute"]],
  ["brother","brother","frère",["family"],["sister","family","mom","dad","play"]],
  ["sister","sister","sœur",["family"],["brother","family","mom","dad","play"]],
  ["grandma","grandma","mamie",["family"],["grandpa","family","cookie","hug","old"]],
  ["grandpa","grandpa","papi",["family"],["grandma","family","story","old","beard"]],
  ["home","home","maison",["home","family"],["family","door","window","kitchen","bed","roof","garden","house_key","cozy"]],
  ["love","love","amour",["feeling","family"],["heart","hug","kiss","family","friend","mom","happy"]],
  ["friend","friend","ami",["feeling","family"],["play","love","hug","share","school","team","happy","party"]],
  ["hug","hug","câlin",["feeling","family"],["love","mom","dad","friend","teddy_bear","warm","arm"]],
  ["kiss","kiss","bisou",["feeling","family"],["love","hug","mom","heart","goodnight"]],
  ["heart","heart","cœur",["body","feeling","shape"],["love","red","kiss","body","valentine","shape"]],
  ["happy","happy","content",["feeling"],["smile","laugh","fun","party","sad","love","joy"]],
  ["sad","sad","triste",["feeling"],["cry","tear","happy","alone","rain"]],
  ["scary","scary","effrayant",["feeling"],["monster","ghost","dark","halloween","spider","nightmare","shark","fear"]],
  ["fear","fear","peur",["feeling"],["scary","dark","monster","brave","scream"]],
  ["fun","fun","amusant",["feeling","game"],["play","game","party","happy","laugh","friend","park","toy"]],
  ["smile","smile","sourire",["feeling","body"],["happy","laugh","tooth","face","mouth"]],
  ["laugh","laugh","rire",["feeling","sound"],["smile","happy","funny","joke","clown","fun"]],
  ["cry","cry","pleurer",["feeling"],["sad","tear","baby","hurt"]],
  ["door","door","porte",["home"],["house_key","window","home","knock","open","room"]],
  ["window","window","fenêtre",["home"],["door","glass","home","curtain","look"]],
  ["kitchen","kitchen","cuisine",["home","food"],["cook","oven","fridge","food","plate","spoon","home","table"]],
  ["garden","garden","jardin",["home","plant","nature"],["flower","grass","tree","grow","seed","vegetable","bee","butterfly","rain","home"]],
  ["candle","candle","bougie",["light","fire","celebration"],["cake","birthday","fire","light","wish","dark"]],

  // Body
  ["body","body","corps",["body"],["hand","foot","head","arm","leg","heart","eye"]],
  ["hand","hand","main",["body"],["finger","arm","clap","wave","glove","body","foot"]],
  ["eye","eye","œil",["body"],["see","look","glasses","face","tear","nose","cry"]],
  ["tooth","tooth","dent",["body"],["smile","brush","dentist","mouth","fairy","bite"]],
  ["foot","foot","pied",["body"],["shoe","sock","toe","leg","walk","hand","run"]],
  ["face","face","visage",["body"],["eye","nose","mouth","smile","head"]],
  ["head","head","tête",["body"],["hat","hair","face","brain","body"]],

  // Clothes
  ["clothes","clothes","vêtements",["clothes"],["shirt","dress","shoe","sock","hat","coat","pajamas","pants"]],
  ["shoe","shoe","chaussure",["clothes"],["foot","sock","boots","walk","run","lace"]],
  ["sock","sock","chaussette",["clothes"],["shoe","foot","warm","pair"]],
  ["hat","hat","chapeau",["clothes"],["head","wizard","witch","sun","cap","cowboy","scarf"]],
  ["boots","boots","bottes",["clothes"],["rain","puddle","snow","shoe","mud","cowboy"]],
  ["coat","coat","manteau",["clothes","cold"],["winter","cold","warm","scarf","rain","jacket"]],
  ["scarf","scarf","écharpe",["clothes","cold"],["winter","cold","warm","snowman","coat","mitten"]],
  ["mitten","mitten","moufle",["clothes","cold"],["winter","snow","cold","hand","scarf"]],
  ["pajamas","pajamas","pyjama",["clothes","night"],["sleep","bed","night","cozy"]],
  ["dress","dress","robe",["clothes"],["princess","party","wedding","skirt","pretty"]],

  // Food
  ["food","food","nourriture",["food"],["eat","hungry","cook","lunch","dinner","kitchen","plate","fruit","vegetable"]],
  ["pizza","pizza","pizza",["food"],["cheese","oven","tomato","party","dinner","slice","italy"]],
  ["apple","apple","pomme",["food","plant"],["tree","fruit","red","pie","juice","green","teacher"]],
  ["banana","banana","banane",["food","plant"],["monkey","yellow","fruit","peel","smoothie"]],
  ["orange","orange","orange",["color","food"],["fruit","juice","color","pumpkin","carrot","fox","tiger"]],
  ["fruit","fruit","fruit",["food","plant"],["apple","banana","orange","strawberry","grape","tree","juice","healthy"]],
  ["strawberry","strawberry","fraise",["food","plant","sweet"],["red","fruit","cake","jam","summer","cream"]],
  ["grape","grape","raisin",["food","plant"],["fruit","purple","juice","green"]],
  ["lemon","lemon","citron",["food","plant"],["yellow","sour","juice","fruit","lemonade"]],
  ["cake","cake","gâteau",["food","sweet","celebration"],["birthday","candle","party","chocolate","oven","sugar","cream","dessert","bake"]],
  ["cookie","cookie","biscuit",["food","sweet"],["chocolate","milk","oven","bake","sugar","grandma","dessert"]],
  ["ice_cream","ice cream","glace",["food","sweet","cold"],["summer","cold","chocolate","cone","dessert","vanilla","strawberry","beach"]],
  ["chocolate","chocolate","chocolat",["food","sweet"],["cake","candy","cookie","easter","sweet","brown","ice_cream","hot_chocolate"]],
  ["candy","candy","bonbon",["food","sweet"],["sweet","sugar","halloween","lollipop","chocolate","party"]],
  ["lollipop","lollipop","sucette",["food","sweet"],["candy","sugar","sweet","stick"]],
  ["sweet","sweet","friandise",["food","sweet"],["sugar","candy","cake","honey","chocolate","dessert"]],
  ["sugar","sugar","sucre",["food","sweet"],["sweet","candy","cake","cookie","tea"]],
  ["dessert","dessert","dessert",["food","sweet"],["cake","ice_cream","pie","cookie","dinner","sweet"]],
  ["bread","bread","pain",["food"],["butter","sandwich","bakery","toast","jam","oven","cheese"]],
  ["cheese","cheese","fromage",["food"],["mouse","pizza","milk","sandwich","cow","bread"]],
  ["milk","milk","lait",["food","drink"],["cow","cookie","cereal","cat","white","glass","baby"]],
  ["water","water","eau",["water","drink","nature"],["drink","river","ocean","rain","swim","glass","lake","wet","fish"]],
  ["juice","juice","jus",["drink","food"],["orange","apple","glass","breakfast","fruit","drink"]],
  ["tea","tea","thé",["drink","hot"],["cup","hot","sugar","milk","party","grandma"]],
  ["hot_chocolate","hot chocolate","chocolat chaud",["drink","hot","sweet"],["chocolate","winter","cup","milk","warm","cozy"]],
  ["drink","drink","boire",["drink"],["water","juice","milk","glass","cup","thirsty"]],
  ["soup","soup","soupe",["food","hot"],["bowl","spoon","hot","vegetable","winter","carrot"]],
  ["egg","egg","œuf",["food","animal"],["chicken","nest","bird","breakfast","easter","dinosaur","shell","bake"]],
  ["honey","honey","miel",["food","sweet"],["bee","bear","sweet","yellow","toast","flower"]],
  ["carrot","carrot","carotte",["food","plant"],["rabbit","orange","vegetable","snowman","garden","soup"]],
  ["vegetable","vegetable","légume",["food","plant"],["carrot","garden","tomato","salad","soup","farm","healthy","potato"]],
  ["tomato","tomato","tomate",["food","plant"],["red","pizza","salad","vegetable","garden"]],
  ["sandwich","sandwich","sandwich",["food"],["bread","cheese","lunch","picnic","butter"]],
  ["picnic","picnic","pique-nique",["food","nature","adventure"],["park","sandwich","basket","ant","summer","blanket","grass","lunch"]],
  ["oven","oven","four",["home","food","hot"],["bake","cake","cookie","pizza","bread","kitchen","hot","cook"]],
  ["cook","cook","cuisiner",["food","home"],["kitchen","oven","chef","food","bake","dinner","soup"]],
  ["bake","bake","pâtisserie",["food","sweet"],["cake","cookie","oven","bread","flour","pie"]],
  ["party","party","fête",["celebration"],["birthday","cake","balloon","dance","music","friend","gift","candy","fun","game","costume"]],
  ["birthday","birthday","anniversaire",["celebration"],["cake","candle","party","gift","balloon","wish","friend","card"]],
  ["gift","gift","cadeau",["celebration","holiday"],["birthday","christmas","surprise","party","ribbon","box","santa"]],
  ["balloon","balloon","ballon gonflable",["celebration","toy"],["party","birthday","air","fly","red","pop"]],
  ["surprise","surprise","surprise",["celebration","feeling"],["gift","party","birthday","box","wow"]],
  ["wish","wish","vœu",["magic","feeling"],["star","birthday","candle","dream","genie","fairy"]],

  // Holidays and seasons
  ["christmas","christmas","noël",["holiday","celebration","cold"],["santa","gift","tree","snow","winter","reindeer","star","elf","candle"]],
  ["santa","santa","père noël",["holiday","story"],["christmas","gift","reindeer","sleigh","elf","beard","red","chimney"]],
  ["reindeer","reindeer","renne",["animal","holiday","cold"],["santa","christmas","snow","sleigh"]],
  ["halloween","halloween","halloween",["holiday","celebration","night"],["ghost","pumpkin","witch","costume","candy","scary","spider","bat","monster","autumn"]],
  ["pumpkin","pumpkin","citrouille",["holiday","food","plant"],["halloween","orange","autumn","pie","witch","farm"]],
  ["costume","costume","déguisement",["clothes","celebration"],["halloween","party","mask","cape","pirate","princess"]],
  ["easter","easter","pâques",["holiday","celebration","season"],["egg","rabbit","chocolate","spring","basket"]],
  ["holiday","holiday","vacances",["holiday","time"],["beach","summer","trip","travel","camping","fun"]],
  ["summer","summer","été",["season","hot"],["sun","beach","hot","holiday","swim","ice_cream","pool","camping","sunflower"]],
  ["winter","winter","hiver",["season","cold"],["snow","cold","ice","christmas","scarf","sled","coat","snowman","ski"]],
  ["spring","spring","printemps",["season","nature"],["flower","rain","grow","garden","butterfly","easter","bird","green"]],
  ["autumn","autumn","automne",["season","nature"],["leaf","orange","wind","pumpkin","halloween","school","rain","brown"]],
  ["season","season","saison",["season","time"],["summer","winter","spring","autumn","year","weather"]],
  ["time","time","temps",["time"],["clock","watch","hour","minute","day","late","year"]],
  ["clock","clock","horloge",["time"],["time","hour","tick","alarm","wall","minute","watch"]],

  // Beach and ocean
  ["beach","beach","plage",["ocean","holiday","hot"],["sand","sea","ocean","wave","sun","summer","shell","swim","sandcastle","crab","towel"]],
  ["ocean","ocean","océan",["ocean","water"],["sea","wave","fish","whale","shark","boat","beach","dolphin","blue","island"]],
  ["sea","sea","mer",["ocean","water"],["ocean","wave","beach","fish","boat","shell","sand","salt","blue"]],
  ["wave","wave","vague",["ocean","water"],["sea","ocean","surf","beach","splash"]],
  ["sand","sand","sable",["ocean","nature"],["beach","sandcastle","desert","shell","bucket"]],
  ["sandcastle","sandcastle","château de sable",["ocean","toy"],["sand","beach","bucket","castle","shovel"]],
  ["shell","shell","coquillage",["ocean","nature"],["beach","sea","sand","snail","turtle","crab"]],
  ["boat","boat","bateau",["transport","water"],["sea","sail","ocean","river","fish","pirate","island","ship"]],
  ["ship","ship","navire",["transport","ocean"],["boat","pirate","sea","sail","captain","anchor"]],
  ["island","island","île",["ocean","nature","adventure"],["sea","ocean","treasure","pirate","beach","palm_tree","boat"]],
  ["swim","swim","nager",["water","sport"],["pool","water","fish","sea","beach","summer","dolphin","duck"]],
  ["pool","pool","piscine",["water","sport"],["swim","summer","splash","water","dive"]],

  // Music and art
  ["music","music","musique",["music","sound"],["song","dance","sing","guitar","piano","drum","party","radio","band","note"]],
  ["song","song","chanson",["music"],["sing","music","dance","radio","band","birthday"]],
  ["sing","sing","chanter",["music","sound"],["song","music","voice","bird","band"]],
  ["dance","dance","danse",["music","celebration"],["music","party","song","ballet","disco","jump"]],
  ["drum","drum","tambour",["music","sound"],["music","band","loud","beat","guitar"]],
  ["guitar","guitar","guitare",["music"],["music","song","band","rock","drum","sing"]],
  ["piano","piano","piano",["music"],["music","song","keys","black","white"]],
  ["band","band","groupe",["music"],["music","drum","guitar","sing","concert"]],
  ["art","art","art",["art"],["paint","draw","color","museum","picture","artist","crayon"]],
  ["paint","paint","peinture",["art","color"],["art","color","brush","picture","draw","rainbow"]],
  ["draw","draw","dessiner",["art"],["pencil","paper","art","picture","crayon","paint"]],
  ["picture","picture","image",["art"],["draw","paint","camera","art","photo"]],
  ["color","color","couleur",["color","art"],["red","blue","green","yellow","rainbow","paint","crayon","purple"]],
  ["red","red","rouge",["color"],["color","apple","fire","heart","strawberry","blue","rainbow","tomato"]],
  ["blue","blue","bleu",["color"],["sky","sea","ocean","color","red","water"]],
  ["green","green","vert",["color","nature"],["grass","leaf","tree","frog","color","nature"]],
  ["yellow","yellow","jaune",["color"],["sun","banana","lemon","color","bee"]],
  ["purple","purple","violet",["color"],["grape","color","rainbow","pink"]],
  ["pink","pink","rose",["color"],["pig","color","princess","flower","purple","candy"]],
  ["white","white","blanc",["color"],["snow","cloud","milk","black","sheep"]],
  ["black","black","noir",["color"],["white","dark","night","bat","panda","zebra"]],
  ["brown","brown","marron",["color"],["chocolate","bear","dirt","autumn","tree"]],

  // Games, sports, toys
  ["game","game","jeu",["game"],["play","win","toy","fun","team","puzzle","ball","board_game","video_game","card"]],
  ["play","play","jouer",["game","toy"],["game","toy","friend","fun","park","ball"]],
  ["toy","toy","jouet",["toy"],["play","game","teddy_bear","doll","ball","puzzle","robot","lego_bricks"]],
  ["ball","ball","balle",["sport","toy"],["soccer","throw","kick","catch","play","basketball","round","dog"]],
  ["soccer","soccer","foot",["sport"],["ball","goal","team","kick","win","field","player"]],
  ["team","team","équipe",["sport","game"],["soccer","win","player","friend","basketball","coach"]],
  ["win","win","gagner",["sport","game"],["game","team","prize","trophy","race","lose","medal"]],
  ["puzzle","puzzle","puzzle",["game","toy"],["game","piece","toy","solve","brain"]],
  ["doll","doll","poupée",["toy"],["toy","play","dress","dollhouse"]],
  ["kite","kite","cerf-volant",["toy","sky"],["wind","fly","sky","string","beach","park"]],
  ["park","park","parc",["city","nature"],["swing","slide","play","tree","grass","picnic","bench","dog"]],
  ["zoo","zoo","zoo",["animal","city"],["animal","lion","elephant","monkey","giraffe","tiger","penguin","zebra"]],
  ["circus","circus","cirque",["celebration","adventure"],["clown","tent","juggle","acrobat","elephant","lion","show"]],
  ["clown","clown","clown",["celebration","job"],["circus","funny","nose","laugh","juggle","balloon"]],

  // Tech, transport, jobs
  ["computer","computer","ordinateur",["tech"],["screen","keyboard","mouse","game","robot","internet","tablet"]],
  ["phone","phone","téléphone",["tech"],["call","screen","camera","computer","talk","tablet"]],
  ["car","car","voiture",["transport","city"],["road","drive","wheel","bus","truck","race","garage"]],
  ["train","train","train",["transport"],["track","station","bus","travel","fast","toot"]],
  ["plane","plane","avion",["transport","sky"],["fly","sky","pilot","airport","wing","cloud","travel"]],
  ["bike","bike","vélo",["transport","sport"],["ride","wheel","helmet","pedal","park","car"]],
  ["bus","bus","bus",["transport","city"],["school","driver","car","train","stop","road"]],
  ["doctor","doctor","docteur",["job","body"],["nurse","hospital","sick","medicine","vet","dentist"]],
  ["firefighter","firefighter","pompier",["job","fire"],["fire","truck","hose","brave","help","police","ladder"]],
  ["police","police","police",["job","city"],["car","help","firefighter","siren","badge","thief"]],

  // Nature
  ["farm","farm","ferme",["farm","animal"],["cow","pig","horse","sheep","chicken","barn","tractor","farmer","hay"]],
  ["tree","tree","arbre",["nature","plant"],["leaf","forest","bird","apple","branch","wood","nest","climb","green"]],
  ["flower","flower","fleur",["nature","plant"],["garden","bee","butterfly","spring","rain","grow","petal","seed","bouquet","sunflower"]],
  ["sunflower","sunflower","tournesol",["plant","nature"],["sun","flower","yellow","seed","summer","garden"]],
  ["grass","grass","herbe",["nature","plant"],["green","garden","cow","park","field","lawn"]],
  ["leaf","leaf","feuille",["nature","plant"],["tree","green","autumn","wind","branch","caterpillar"]],
  ["seed","seed","graine",["plant","nature"],["grow","flower","garden","plant","bird","sunflower"]],
  ["grow","grow","pousser",["plant","nature"],["seed","plant","garden","flower","rain","tall","tree"]],
  ["plant","plant","plante",["plant","nature"],["seed","grow","flower","garden","leaf","water","green"]],
  ["forest","forest","forêt",["nature"],["tree","wolf","bear","owl","fox","leaf","camping","deer","mushroom"]],
  ["mountain","mountain","montagne",["nature","adventure"],["snow","climb","hike","ski","rock","volcano","high"]],
  ["river","river","rivière",["nature","water"],["water","fish","boat","bridge","lake","frog","swim"]],
  ["lake","lake","lac",["nature","water"],["water","river","boat","fish","duck","pond","swim"]],
  ["pond","pond","étang",["nature","water"],["frog","duck","fish","lake","water"]],
  ["fire","fire","feu",["fire","hot"],["hot","dragon","firefighter","smoke","camping","candle","wood","burn","red"]],
  ["ice","ice","glaçon",["cold","water"],["cold","snow","winter","skate","penguin","freeze","water"]],
  ["hot","hot","chaud",["hot"],["sun","fire","summer","cold","warm","soup","desert","oven"]],
  ["cold","cold","froid",["cold"],["ice","snow","winter","hot","penguin","freeze","scarf"]],
  ["warm","warm","tiède",["hot","feeling"],["hot","blanket","sun","cozy","coat","hug"]],
  ["cozy","cozy","douillet",["home","feeling"],["blanket","warm","bed","home","hot_chocolate","pajamas"]],
  ["jungle","jungle","jungle",["nature","animal","adventure"],["monkey","tiger","snake","parrot","tree","adventure","lion"]],
  ["desert","desert","désert",["nature","hot"],["sand","hot","camel","cactus","sun","snake"]],
  ["volcano","volcano","volcan",["nature","fire","science"],["lava","fire","mountain","hot","dinosaur","island"]],
  ["nest","nest","nid",["animal","nature"],["bird","egg","tree","feather","branch"]],
  ["wing","wing","aile",["animal","body"],["bird","fly","feather","butterfly","plane","angel","fairy","dragon"]],
  ["feather","feather","plume",["animal"],["bird","wing","pillow","soft","chicken","owl"]],
  ["fly","fly","voler",["sky"],["bird","wing","plane","sky","kite","rocket","superhero"]],
  ["bone","bone","os",["body","animal"],["dog","skeleton","dinosaur","fossil"]],
  ["camping","camping","camping",["nature","adventure"],["tent","fire","forest","marshmallow","sleeping_bag","hike","star"]],
  ["tent","tent","tente",["adventure","nature"],["camping","circus","sleeping_bag","forest"]],
];
