// Curated, age-appropriate association graph used by the Solo bot and spell assistance.
// Each concept: [id, englishLabel, frenchLabel, tags, links]
// Links are undirected (index.js mirrors them), so each pair only needs to be listed once.
export const TAGS = ["sky","weather","space","night","animal","pet","farm","ocean","water","nature","plant","food","sweet","drink","home","family","body","feeling","school","book","story","magic","music","art","color","sport","game","toy","transport","city","job","time","season","holiday","clothes","tech","science","shape","sound","light","fire","cold","hot","celebration","adventure"];

export const CONCEPTS = [
  // Sky, weather, space
  ["sun","sun","soleil",["sky","light","hot"],["moon","sky","day","summer","star","light","beach","hot","sunflower","yellow","space"]],
  ["moon","moon","lune",["sky","night","space"],["sky","night","star","space","rocket","planet","dream","light","astronaut","owl"]],
  ["star","star","étoile",["sky","night","space"],["sky","night","space","planet","wish","light","shine","rocket","shape"]],
  ["sky","sky","ciel",["sky","nature"],["cloud","bird","plane","rainbow","blue","star","kite","fly","space","night","day"]],
  ["cloud","cloud","nuage",["sky","weather"],["rain","sky","storm","white","soft","snow","wind","thunder","plane"]],
  ["rain","rain","pluie",["weather","water","sky"],["cloud","umbrella","puddle","storm","rainbow","water","flower","grow","garden","wet","boots","spring"]],
  ["snow","snow","neige",["weather","cold","season"],["winter","cold","snowman","sled","ice","white","mountain","ski","christmas","snowflake","mitten"]],
  ["storm","storm","orage",["weather","sky","sound"],["thunder","lightning","rain","wind","cloud","scary","loud"]],
  ["rainbow","rainbow","arc-en-ciel",["sky","color","weather"],["rain","color","sun","sky","unicorn","red","purple","cloud"]],
  ["thunder","thunder","tonnerre",["weather","sound"],["lightning","storm","loud","cloud","scary"]],
  ["lightning","lightning","éclair",["weather","light"],["thunder","storm","fast","electricity","bright"]],
  ["wind","wind","vent",["weather","nature"],["kite","storm","leaf","autumn","cloud","boat","cold"]],
  ["umbrella","umbrella","parapluie",["weather"],["rain","wet","boots","puddle","coat"]],
  ["puddle","puddle","flaque",["weather","water"],["rain","boots","mud","wet","jump"]],
  ["snowman","snowman","bonhomme de neige",["cold","season"],["snow","winter","carrot","scarf","cold","hat"]],
  ["snowflake","snowflake","flocon",["cold","weather"],["snow","winter","ice","cold","white"]],
  ["light","light","lumière",["light"],["sun","lamp","bright","dark","candle","star","day","flashlight","shine"]],
  ["night","night","nuit",["night","time"],["moon","star","dark","sleep","dream","bed","owl","bat","day","pajamas"]],
  ["day","day","jour",["time","light"],["sun","night","morning","light","time","sky"]],
  ["morning","morning","matin",["time"],["breakfast","sun","day","school","coffee"]],
  ["dark","dark","sombre",["night","color"],["night","black","scary","light","flashlight","bat"]],
  ["dream","dream","rêve",["night","feeling"],["sleep","night","bed","wish","pillow","moon","unicorn","nightmare"]],
  ["nightmare","nightmare","cauchemar",["night","feeling"],["dream","scary","monster","night","sleep","ghost"]],
  ["sleep","sleep","dormir",["night","home"],["bed","night","dream","pillow","tired","pajamas","blanket"]],
  ["bed","bed","lit",["home","night"],["sleep","pillow","blanket","night","dream","bedroom","pajamas","teddy_bear"]],
  ["pillow","pillow","oreiller",["home","night"],["bed","sleep","soft","dream","blanket","feather"]],
  ["blanket","blanket","couverture",["home","night"],["bed","pillow","warm","soft","sleep","cozy"]],
  ["space","space","espace",["space","science"],["rocket","planet","star","moon","astronaut","alien","sun","earth"]],
  ["rocket","rocket","fusée",["space","transport"],["space","moon","astronaut","planet","fast","fire","fly","star"]],
  ["planet","planet","planète",["space","science"],["space","earth","star","moon","rocket","alien","round"]],
  ["earth","earth","terre",["space","nature"],["planet","world","space","moon","nature","round"]],
  ["astronaut","astronaut","astronaute",["space","job"],["rocket","space","moon","planet","helmet","star"]],
  ["alien","alien","extraterrestre",["space","story"],["space","planet","green","rocket","monster"]],

  // Animals
  ["animal","animal","animal",["animal"],["pet","zoo","farm","dog","cat","jungle","fur","paw","tail","forest","wild"]],
  ["pet","pet","animal domestique",["pet","animal","home"],["dog","cat","fish","hamster","rabbit","animal","home","love","fur","paw","tail","vet"]],
  ["dog","dog","chien",["animal","pet"],["cat","bone","puppy","paw","tail","fur","pet","ball","walk","wolf"]],
  ["puppy","puppy","chiot",["animal","pet"],["dog","baby","cute","play","paw"]],
  ["cat","cat","chat",["animal","pet"],["dog","mouse","milk","kitten","paw","tail","fur","pet"]],
  ["kitten","kitten","chaton",["animal","pet"],["cat","baby","cute","milk"]],
  ["fur","fur","fourrure",["animal","body"],["dog","cat","bear","soft","warm","rabbit","fox"]],
  ["paw","paw","patte",["animal","body"],["dog","cat","bear","foot"]],
  ["tail","tail","queue",["animal","body"],["dog","cat","monkey","mouse","fox","fish","horse"]],
  ["bird","bird","oiseau",["animal","sky"],["nest","wing","feather","fly","egg","sky","tree","sing","owl","parrot"]],
  ["fish","fish","poisson",["animal","ocean","water"],["water","ocean","swim","sea","shark","boat","pet","river","aquarium"]],
  ["horse","horse","cheval",["animal","farm"],["farm","ride","unicorn","knight","tail","pony","hay"]],
  ["pony","pony","poney",["animal","farm"],["horse","ride","farm","cute","unicorn"]],
  ["cow","cow","vache",["animal","farm"],["milk","farm","grass","cheese","barn","farmer"]],
  ["pig","pig","cochon",["animal","farm"],["farm","mud","pink","barn"]],
  ["sheep","sheep","mouton",["animal","farm"],["farm","wool","grass","white","cloud","sleep"]],
  ["chicken","chicken","poule",["animal","farm"],["egg","farm","feather","nest","barn"]],
  ["duck","duck","canard",["animal","water","farm"],["pond","feather","swim","farm","wing","bird"]],
  ["lion","lion","lion",["animal"],["tiger","king","roar","zoo","jungle","cat","wild"]],
  ["tiger","tiger","tigre",["animal"],["lion","jungle","zoo","orange","roar","wild","cat"]],
  ["elephant","elephant","éléphant",["animal"],["zoo","big","jungle","circus","grey","giraffe"]],
  ["monkey","monkey","singe",["animal"],["banana","jungle","tree","zoo","tail","climb","funny"]],
  ["bear","bear","ours",["animal","nature"],["forest","honey","teddy_bear","fur","cave","paw","big","winter","panda"]],
  ["teddy_bear","teddy bear","nounours",["toy","home"],["bear","toy","soft","bed","hug","cute"]],
  ["frog","frog","grenouille",["animal","water"],["pond","jump","green","prince","fly","river"]],
  ["bee","bee","abeille",["animal","nature"],["honey","flower","garden","yellow","insect"]],
  ["butterfly","butterfly","papillon",["animal","nature"],["flower","wing","garden","caterpillar","color","fly","spring","insect"]],
  ["caterpillar","caterpillar","chenille",["animal","nature"],["butterfly","leaf","green","insect","garden","grow"]],
  ["insect","insect","insecte",["animal","nature"],["bee","ant","butterfly","ladybug","spider","garden","grass"]],
  ["ant","ant","fourmi",["animal","nature"],["insect","picnic","small","garden","grass"]],
  ["ladybug","ladybug","coccinelle",["animal","nature"],["insect","red","garden","leaf"]],
  ["spider","spider","araignée",["animal","nature"],["insect","halloween","scary","leg","ghost","haunted_house"]],
  ["owl","owl","hibou",["animal","night","nature"],["night","bird","forest","tree","moon","feather"]],
  ["bat","bat","chauve-souris",["animal","night"],["night","cave","halloween","dark","wing","vampire"]],
  ["wolf","wolf","loup",["animal","nature","story"],["forest","moon","dog","fox","wild"]],
  ["fox","fox","renard",["animal","nature"],["forest","orange","tail","wolf","rabbit","fur"]],
  ["rabbit","rabbit","lapin",["animal","pet"],["carrot","ear","easter","pet","fur","garden","jump"]],
  ["mouse","mouse","souris",["animal","pet"],["cat","cheese","small","tail","computer"]],
  ["hamster","hamster","hamster",["animal","pet"],["pet","small","wheel","cute","mouse"]],
  ["parrot","parrot","perroquet",["animal","pet"],["bird","pirate","jungle","feather","color"]],
  ["snake","snake","serpent",["animal"],["jungle","scary","desert","zoo","crocodile"]],
  ["giraffe","giraffe","girafe",["animal"],["zoo","elephant","zebra","tree","animal","jungle"]],
  ["zebra","zebra","zèbre",["animal"],["zoo","horse","giraffe","black","white"]],
  ["penguin","penguin","pingouin",["animal","cold"],["ice","cold","snow","fish","swim","bird"]],
  ["panda","panda","panda",["animal"],["bear","zoo","black","white","cute"]],
  ["shark","shark","requin",["animal","ocean"],["ocean","fish","tooth","sea","scary","swim"]],
  ["whale","whale","baleine",["animal","ocean"],["ocean","sea","big","dolphin","swim","fish"]],
  ["dolphin","dolphin","dauphin",["animal","ocean"],["ocean","sea","swim","whale","jump","wave"]],
  ["octopus","octopus","pieuvre",["animal","ocean"],["ocean","sea","arm","fish"]],
  ["crab","crab","crabe",["animal","ocean"],["beach","sand","sea","shell","ocean","starfish"]],
  ["turtle","turtle","tortue",["animal","water"],["shell","slow","sea","beach","pond","green"]],
  ["snail","snail","escargot",["animal","nature"],["slow","shell","garden","rain","leaf"]],
  ["dinosaur","dinosaur","dinosaure",["animal","science","story"],["fossil","big","roar","egg","volcano","dragon","bone","museum"]],

  // Fantasy and stories
  ["dragon","dragon","dragon",["magic","story","fire"],["fire","castle","knight","princess","wing","treasure","dinosaur","scary","cave","magic"]],
  ["unicorn","unicorn","licorne",["magic","story","animal"],["horse","rainbow","magic","princess","fairy","dream","sparkle"]],
  ["castle","castle","château",["story","magic","home"],["king","queen","princess","knight","dragon","tower","crown","prince","sandcastle"]],
  ["princess","princess","princesse",["story","magic"],["prince","castle","crown","queen","king","dress","fairy","dragon"]],
  ["prince","prince","prince",["story","magic"],["princess","castle","king","frog","crown","knight","horse"]],
  ["knight","knight","chevalier",["story","adventure"],["castle","sword","dragon","horse","shield","king","princess"]],
  ["king","king","roi",["story"],["queen","crown","castle","prince","lion","knight","princess"]],
  ["queen","queen","reine",["story"],["king","crown","castle","princess","bee"]],
  ["crown","crown","couronne",["story","clothes"],["king","queen","princess","gold","castle","jewel","prince"]],
  ["pirate","pirate","pirate",["story","adventure","ocean"],["treasure","ship","parrot","island","map","sea","sword","captain"]],
  ["treasure","treasure","trésor",["adventure","story"],["pirate","gold","map","island","dragon","jewel"]],
  ["magic","magic","magie",["magic"],["wizard","wand","fairy","spell","unicorn","witch","dragon","sparkle"]],
  ["wizard","wizard","sorcier",["magic","story"],["magic","wand","spell","hat","witch","castle","owl","beard"]],
  ["witch","witch","sorcière",["magic","story","holiday"],["broom","halloween","hat","spell","cat","wizard","magic","cauldron"]],
  ["fairy","fairy","fée",["magic","story"],["wing","magic","wand","princess","flower","sparkle","tooth","unicorn"]],
  ["wand","wand","baguette magique",["magic"],["wizard","magic","fairy","spell","witch","star"]],
  ["spell","spell","sortilège",["magic"],["magic","wizard","witch","wand","potion"]],
  ["ghost","ghost","fantôme",["story","holiday"],["halloween","scary","haunted_house","white","monster","night"]],
  ["monster","monster","monstre",["story"],["scary","halloween","ghost","nightmare","tooth","dragon","alien","closet"]],
  ["hero","hero","héros",["story","adventure"],["superhero","brave","adventure","cape","knight","story"]],
  ["superhero","superhero","super-héros",["story","adventure"],["hero","cape","mask","fly","strong"]],
  ["cape","cape","cape",["clothes","story"],["superhero","hero","wizard","fly","mask","costume"]],
  ["robot","robot","robot",["tech","toy","science"],["computer","space","alien","toy","battery"]],
  ["adventure","adventure","aventure",["adventure"],["explore","map","treasure","hero","jungle","pirate","camping"]],
  ["map","map","carte",["adventure"],["treasure","pirate","island","adventure","explore"]],
  ["story","story","histoire",["story","book"],["book","read","bedtime","fairy","hero","princess","dragon","write"]],
  ["book","book","livre",["book","school"],["read","story","library","school","write","teacher"]],

  // School
  ["school","school","école",["school"],["teacher","book","pencil","class","student","read","write","library","backpack","homework","friend"]],
  ["teacher","teacher","maîtresse",["school","job"],["school","class","student","book","read","write"]],
  ["student","student","élève",["school"],["school","teacher","class","homework","backpack"]],
  ["class","class","classe",["school"],["school","teacher","student","desk"]],
  ["pencil","pencil","crayon",["school","art"],["write","draw","paper","eraser","school","pen","color"]],
  ["pen","pen","stylo",["school"],["write","pencil","paper","letter"]],
  ["paper","paper","papier",["school","art"],["pencil","write","draw","book","letter","scissors"]],
  ["eraser","eraser","gomme",["school"],["pencil","school","paper","pen","desk"]],
  ["read","read","lire",["book","school"],["book","story","library","write","letter","school","word"]],
  ["write","write","écrire",["book","school"],["pencil","pen","read","paper","letter","story","word"]],
  ["library","library","bibliothèque",["book","school","city"],["book","read","quiet","story","school"]],
  ["homework","homework","devoirs",["school"],["school","pencil","teacher","student","math"]],
  ["backpack","backpack","cartable",["school","clothes"],["school","book","camping","hike","lunch"]],
  ["math","math","maths",["school","science"],["number","count","school","homework","brain"]],
  ["word","word","mot",["school","book"],["letter","read","write","book","story"]],
  ["letter","letter","lettre",["school","book"],["write","read","word","alphabet"]],

  // Family, home, feelings
  ["family","family","famille",["family","home"],["mom","dad","baby","brother","sister","home","love","grandma","grandpa"]],
  ["mom","mom","maman",["family"],["dad","family","baby","love","hug","home"]],
  ["dad","dad","papa",["family"],["mom","family","baby","love","hug","home"]],
  ["baby","baby","bébé",["family"],["mom","dad","cry","small","family","cute"]],
  ["brother","brother","frère",["family"],["sister","family","mom","dad","play"]],
  ["sister","sister","sœur",["family"],["brother","family","mom","dad","play"]],
  ["grandma","grandma","mamie",["family"],["grandpa","family","cookie","hug","old"]],
  ["grandpa","grandpa","papi",["family"],["grandma","family","story","old","beard"]],
  ["home","home","maison",["home","family"],["family","door","window","kitchen","bed","roof","garden","key","cozy"]],
  ["love","love","amour",["feeling","family"],["heart","hug","kiss","family","friend","mom","happy"]],
  ["friend","friend","ami",["feeling","family"],["play","love","hug","share","school","team","happy","party"]],
  ["hug","hug","câlin",["feeling","family"],["love","mom","dad","friend","teddy_bear","warm","arm"]],
  ["kiss","kiss","bisou",["feeling","family"],["love","hug","mom","heart"]],
  ["heart","heart","cœur",["body","feeling","shape"],["love","red","kiss","body","valentine","shape"]],
  ["happy","happy","content",["feeling"],["smile","laugh","fun","party","sad","love"]],
  ["sad","sad","triste",["feeling"],["cry","happy","rain","hurt"]],
  ["scary","scary","effrayant",["feeling"],["monster","ghost","dark","halloween","spider","nightmare","shark","fear"]],
  ["fear","fear","peur",["feeling"],["scary","dark","monster","brave","nightmare"]],
  ["fun","fun","amusant",["feeling","game"],["play","game","party","happy","laugh","friend","park","toy"]],
  ["smile","smile","sourire",["feeling","body"],["happy","laugh","tooth","face","mouth"]],
  ["laugh","laugh","rire",["feeling","sound"],["smile","happy","funny","clown","fun"]],
  ["cry","cry","pleurer",["feeling"],["sad","baby","hurt","angry"]],
  ["door","door","porte",["home"],["key","window","home","roof"]],
  ["window","window","fenêtre",["home"],["door","glass","home","eye"]],
  ["kitchen","kitchen","cuisine",["home","food"],["cook","oven","fridge","food","plate","spoon","home","table"]],
  ["garden","garden","jardin",["home","plant","nature"],["flower","grass","tree","grow","seed","vegetable","bee","butterfly","rain","home"]],
  ["candle","candle","bougie",["light","fire","celebration"],["cake","birthday","fire","light","wish","dark"]],

  // Body
  ["body","body","corps",["body"],["hand","foot","head","arm","leg","heart","eye"]],
  ["hand","hand","main",["body"],["finger","arm","wave","glove","body","foot"]],
  ["eye","eye","œil",["body"],["glasses","face","nose","cry"]],
  ["tooth","tooth","dent",["body"],["smile","dentist","mouth","fairy"]],
  ["foot","foot","pied",["body"],["shoe","sock","leg","walk","hand","run"]],
  ["face","face","visage",["body"],["eye","nose","mouth","smile","head"]],
  ["head","head","tête",["body"],["hat","hair","face","brain","body"]],

  // Clothes
  ["clothes","clothes","vêtements",["clothes"],["shirt","dress","shoe","sock","hat","coat","pajamas","pants"]],
  ["shoe","shoe","chaussure",["clothes"],["foot","sock","boots","walk","run"]],
  ["sock","sock","chaussette",["clothes"],["shoe","foot","warm"]],
  ["hat","hat","chapeau",["clothes"],["head","wizard","witch","sun","scarf"]],
  ["boots","boots","bottes",["clothes"],["rain","puddle","snow","shoe","mud"]],
  ["coat","coat","manteau",["clothes","cold"],["winter","cold","warm","scarf","rain","jacket"]],
  ["scarf","scarf","écharpe",["clothes","cold"],["winter","cold","warm","snowman","coat","mitten"]],
  ["mitten","mitten","moufle",["clothes","cold"],["winter","snow","cold","hand","scarf"]],
  ["pajamas","pajamas","pyjama",["clothes","night"],["sleep","bed","night","cozy"]],
  ["dress","dress","robe",["clothes"],["princess","party","wedding"]],

  // Food
  ["food","food","nourriture",["food"],["eat","hungry","cook","lunch","dinner","kitchen","plate","fruit","vegetable"]],
  ["pizza","pizza","pizza",["food"],["cheese","oven","tomato","party","dinner"]],
  ["apple","apple","pomme",["food","plant"],["tree","fruit","red","pie","juice","green","teacher"]],
  ["banana","banana","banane",["food","plant"],["monkey","yellow","fruit","jungle","snack"]],
  ["orange","orange","orange",["color","food"],["fruit","juice","color","pumpkin","carrot","fox","tiger"]],
  ["fruit","fruit","fruit",["food","plant"],["apple","banana","orange","strawberry","grape","tree","juice"]],
  ["strawberry","strawberry","fraise",["food","plant","sweet"],["red","fruit","cake","jam","summer"]],
  ["grape","grape","raisin",["food","plant"],["fruit","purple","juice","green","snack"]],
  ["lemon","lemon","citron",["food","plant"],["yellow","juice","fruit","lemonade","tea"]],
  ["cake","cake","gâteau",["food","sweet","celebration"],["birthday","candle","party","chocolate","oven","sugar","dessert","bake"]],
  ["cookie","cookie","biscuit",["food","sweet"],["chocolate","milk","oven","bake","sugar","grandma","dessert"]],
  ["ice_cream","ice cream","glace",["food","sweet","cold"],["summer","cold","chocolate","dessert","strawberry","beach"]],
  ["chocolate","chocolate","chocolat",["food","sweet"],["cake","candy","cookie","easter","sweet","brown","ice_cream","hot_chocolate"]],
  ["candy","candy","bonbon",["food","sweet"],["sweet","sugar","halloween","lollipop","chocolate","party"]],
  ["lollipop","lollipop","sucette",["food","sweet"],["candy","sugar","sweet","party","pink"]],
  ["sweet","sweet","friandise",["food","sweet"],["sugar","candy","cake","honey","chocolate","dessert"]],
  ["sugar","sugar","sucre",["food","sweet"],["sweet","candy","cake","cookie","tea"]],
  ["dessert","dessert","dessert",["food","sweet"],["cake","ice_cream","pie","cookie","dinner","sweet"]],
  ["bread","bread","pain",["food"],["butter","sandwich","bakery","toast","jam","oven","cheese"]],
  ["cheese","cheese","fromage",["food"],["mouse","pizza","milk","sandwich","cow","bread"]],
  ["milk","milk","lait",["food","drink"],["cow","cookie","cereal","cat","white","glass","baby"]],
  ["water","water","eau",["water","drink","nature"],["drink","river","ocean","rain","swim","glass","lake","wet","fish"]],
  ["juice","juice","jus",["drink","food"],["orange","apple","glass","breakfast","fruit","drink"]],
  ["tea","tea","thé",["drink","hot"],["cup","hot","sugar","milk","party","grandma"]],
  ["hot_chocolate","hot chocolate","chocolat chaud",["drink","hot","sweet"],["chocolate","winter","cup","milk","warm","cozy"]],
  ["drink","drink","boire",["drink"],["water","juice","milk","glass","cup"]],
  ["soup","soup","soupe",["food","hot"],["spoon","hot","vegetable","winter","carrot"]],
  ["egg","egg","œuf",["food","animal"],["chicken","nest","bird","breakfast","easter","dinosaur","shell","bake"]],
  ["honey","honey","miel",["food","sweet"],["bee","bear","sweet","yellow","toast","flower"]],
  ["carrot","carrot","carotte",["food","plant"],["rabbit","orange","vegetable","snowman","garden","soup"]],
  ["vegetable","vegetable","légume",["food","plant"],["carrot","garden","tomato","salad","soup","farm","potato"]],
  ["tomato","tomato","tomate",["food","plant"],["red","pizza","salad","vegetable","garden"]],
  ["sandwich","sandwich","sandwich",["food"],["bread","cheese","lunch","picnic","butter"]],
  ["picnic","picnic","pique-nique",["food","nature","adventure"],["park","sandwich","basket","ant","summer","blanket","grass","lunch"]],
  ["oven","oven","four",["home","food","hot"],["bake","cake","cookie","pizza","bread","kitchen","hot","cook"]],
  ["cook","cook","cuisiner",["food","home"],["kitchen","oven","chef","food","bake","dinner","soup"]],
  ["bake","bake","pâtisserie",["food","sweet"],["cake","cookie","oven","bread","pie"]],
  ["party","party","fête",["celebration"],["birthday","cake","balloon","dance","music","friend","gift","candy","fun","game","costume"]],
  ["birthday","birthday","anniversaire",["celebration"],["cake","candle","party","gift","balloon","wish","friend"]],
  ["gift","gift","cadeau",["celebration","holiday"],["birthday","christmas","surprise","party","box","santa"]],
  ["balloon","balloon","ballon gonflable",["celebration","toy"],["party","birthday","fly","red"]],
  ["surprise","surprise","surprise",["celebration","feeling"],["gift","party","birthday","box","happy"]],
  ["wish","wish","vœu",["magic","feeling"],["star","birthday","candle","dream","fairy"]],

  // Holidays and seasons
  ["christmas","christmas","noël",["holiday","celebration","cold"],["santa","gift","tree","snow","winter","reindeer","star","elf","candle"]],
  ["santa","santa","père noël",["holiday","story"],["christmas","gift","reindeer","sleigh","elf","beard","red","chimney"]],
  ["reindeer","reindeer","renne",["animal","holiday","cold"],["santa","christmas","snow","sleigh","elf","winter"]],
  ["halloween","halloween","halloween",["holiday","celebration","night"],["ghost","pumpkin","witch","costume","candy","scary","spider","bat","monster","autumn"]],
  ["pumpkin","pumpkin","citrouille",["holiday","food","plant"],["halloween","orange","autumn","pie","witch","farm"]],
  ["costume","costume","déguisement",["clothes","celebration"],["halloween","party","mask","cape","pirate","princess"]],
  ["easter","easter","pâques",["holiday","celebration","season"],["egg","rabbit","chocolate","spring","basket"]],
  ["holiday","holiday","vacances",["holiday","time"],["beach","summer","travel","camping","fun"]],
  ["summer","summer","été",["season","hot"],["sun","beach","hot","holiday","swim","ice_cream","pool","camping","sunflower"]],
  ["winter","winter","hiver",["season","cold"],["snow","cold","ice","christmas","scarf","sled","coat","snowman","ski"]],
  ["spring","spring","printemps",["season","nature"],["flower","rain","grow","garden","butterfly","easter","bird","green"]],
  ["autumn","autumn","automne",["season","nature"],["leaf","orange","wind","pumpkin","halloween","school","rain","brown"]],
  ["season","season","saison",["season","time"],["summer","winter","spring","autumn","year","weather"]],
  ["time","time","temps",["time"],["clock","day","year","night","season"]],
  ["clock","clock","horloge",["time"],["time","morning","day","year"]],

  // Beach and ocean
  ["beach","beach","plage",["ocean","holiday","hot"],["sand","sea","ocean","wave","sun","summer","shell","swim","sandcastle","crab","towel"]],
  ["ocean","ocean","océan",["ocean","water"],["sea","wave","fish","whale","shark","boat","beach","dolphin","blue","island"]],
  ["sea","sea","mer",["ocean","water"],["ocean","wave","beach","fish","boat","shell","sand","blue"]],
  ["wave","wave","vague",["ocean","water"],["sea","ocean","surf","beach","puddle"]],
  ["sand","sand","sable",["ocean","nature"],["beach","sandcastle","desert","shell","bucket"]],
  ["sandcastle","sandcastle","château de sable",["ocean","toy"],["sand","beach","bucket","castle"]],
  ["shell","shell","coquillage",["ocean","nature"],["beach","sea","sand","snail","turtle","crab"]],
  ["boat","boat","bateau",["transport","water"],["sea","ocean","river","fish","pirate","island","ship"]],
  ["ship","ship","navire",["transport","ocean"],["boat","pirate","sea","captain","ocean"]],
  ["island","island","île",["ocean","nature","adventure"],["sea","ocean","treasure","pirate","beach","palm_tree","boat"]],
  ["swim","swim","nager",["water","sport"],["pool","water","fish","sea","beach","summer","dolphin","duck"]],
  ["pool","pool","piscine",["water","sport"],["swim","summer","puddle","water","dive"]],

  // Music and art
  ["music","music","musique",["music","sound"],["song","dance","sing","guitar","piano","drum","party","radio","band"]],
  ["song","song","chanson",["music"],["sing","music","dance","radio","band","birthday"]],
  ["sing","sing","chanter",["music","sound"],["song","music","bird","band"]],
  ["dance","dance","danse",["music","celebration"],["music","party","song","jump"]],
  ["drum","drum","tambour",["music","sound"],["music","band","loud","guitar","concert"]],
  ["guitar","guitar","guitare",["music"],["music","song","band","rock","drum","sing"]],
  ["piano","piano","piano",["music"],["music","song","black","white"]],
  ["band","band","groupe",["music"],["music","drum","guitar","sing","concert"]],
  ["art","art","art",["art"],["paint","draw","color","museum","picture","artist","pencil"]],
  ["paint","paint","peinture",["art","color"],["art","color","picture","draw","rainbow"]],
  ["draw","draw","dessiner",["art"],["pencil","paper","art","picture","paint"]],
  ["picture","picture","image",["art"],["draw","paint","photo","art"]],
  ["color","color","couleur",["color","art"],["red","blue","green","yellow","rainbow","paint","pencil","purple"]],
  ["red","red","rouge",["color"],["color","apple","fire","heart","strawberry","blue","rainbow","tomato"]],
  ["blue","blue","bleu",["color"],["sky","sea","ocean","color","red","water"]],
  ["green","green","vert",["color","nature"],["grass","leaf","tree","frog","color","nature"]],
  ["yellow","yellow","jaune",["color"],["sun","banana","lemon","color","bee"]],
  ["purple","purple","violet",["color"],["grape","color","rainbow","pink","unicorn","flower"]],
  ["pink","pink","rose",["color"],["pig","color","princess","flower","purple","candy"]],
  ["white","white","blanc",["color"],["snow","cloud","milk","black","sheep"]],
  ["black","black","noir",["color"],["white","dark","night","bat","panda","zebra"]],
  ["brown","brown","marron",["color"],["chocolate","bear","autumn","tree","mud"]],

  // Games, sports, toys
  ["game","game","jeu",["game"],["play","win","toy","fun","team","puzzle","ball","board_game","video_game"]],
  ["play","play","jouer",["game","toy"],["game","toy","friend","fun","park","ball"]],
  ["toy","toy","jouet",["toy"],["play","game","teddy_bear","doll","ball","puzzle","robot"]],
  ["ball","ball","ballon",["sport","toy"],["soccer","throw","catch","play","basketball","round","dog"]],
  ["soccer","soccer","foot",["sport"],["ball","goal","team","win","field","player"]],
  ["team","team","équipe",["sport","game"],["soccer","win","player","friend","basketball"]],
  ["win","win","gagner",["sport","game"],["game","team","trophy","race","medal"]],
  ["puzzle","puzzle","puzzle",["game","toy"],["game","toy","brain","board_game","blocks"]],
  ["doll","doll","poupée",["toy"],["toy","play","dress","teddy_bear","princess"]],
  ["kite","kite","cerf-volant",["toy","sky"],["wind","fly","sky","beach","park"]],
  ["park","park","parc",["city","nature"],["swing","slide","play","tree","grass","picnic","dog"]],
  ["zoo","zoo","zoo",["animal","city"],["animal","lion","elephant","monkey","giraffe","tiger","penguin","zebra"]],
  ["circus","circus","cirque",["celebration","adventure"],["clown","tent","elephant","lion","show"]],
  ["clown","clown","clown",["celebration","job"],["circus","funny","nose","laugh","balloon"]],

  // Tech, transport, jobs
  ["computer","computer","ordinateur",["tech"],["screen","mouse","game","robot","tablet"]],
  ["phone","phone","téléphone",["tech"],["screen","photo","computer","parrot","tablet"]],
  ["car","car","voiture",["transport","city"],["road","wheel","bus","truck","race"]],
  ["train","train","train",["transport"],["station","bus","travel","fast"]],
  ["plane","plane","avion",["transport","sky"],["fly","sky","pilot","airport","wing","cloud","travel"]],
  ["bike","bike","vélo",["transport","sport"],["ride","wheel","helmet","park","car"]],
  ["bus","bus","bus",["transport","city"],["school","car","train","road"]],
  ["doctor","doctor","docteur",["job","body"],["nurse","hospital","sick","medicine","vet","dentist"]],
  ["firefighter","firefighter","pompier",["job","fire"],["fire","truck","brave","help","police"]],
  ["police","police","police",["job","city"],["car","help","firefighter","ambulance","city"]],

  // Nature
  ["farm","farm","ferme",["farm","animal"],["cow","pig","horse","sheep","chicken","barn","tractor","farmer","hay"]],
  ["tree","tree","arbre",["nature","plant"],["leaf","forest","bird","apple","branch","wood","nest","climb","green"]],
  ["flower","flower","fleur",["nature","plant"],["garden","bee","butterfly","spring","rain","grow","seed","sunflower"]],
  ["sunflower","sunflower","tournesol",["plant","nature"],["sun","flower","yellow","seed","summer","garden"]],
  ["grass","grass","herbe",["nature","plant"],["green","garden","cow","park","field"]],
  ["leaf","leaf","feuille",["nature","plant"],["tree","green","autumn","wind","branch","caterpillar"]],
  ["seed","seed","graine",["plant","nature"],["grow","flower","garden","plant","bird","sunflower"]],
  ["grow","grow","pousser",["plant","nature"],["seed","plant","garden","flower","rain","tree"]],
  ["plant","plant","plante",["plant","nature"],["seed","grow","flower","garden","leaf","water","green"]],
  ["forest","forest","forêt",["nature"],["tree","wolf","bear","owl","fox","leaf","camping","mushroom"]],
  ["mountain","mountain","montagne",["nature","adventure"],["snow","climb","hike","ski","rock","volcano"]],
  ["river","river","rivière",["nature","water"],["water","fish","boat","bridge","lake","frog","swim"]],
  ["lake","lake","lac",["nature","water"],["water","river","boat","fish","duck","pond","swim"]],
  ["pond","pond","étang",["nature","water"],["frog","duck","fish","lake","water"]],
  ["fire","fire","feu",["fire","hot"],["hot","dragon","firefighter","camping","candle","wood","red"]],
  ["ice","ice","glaçon",["cold","water"],["cold","snow","winter","skate","penguin","water"]],
  ["hot","hot","chaud",["hot"],["sun","fire","summer","cold","warm","soup","desert","oven"]],
  ["cold","cold","froid",["cold"],["ice","snow","winter","hot","penguin","scarf"]],
  ["warm","warm","tiède",["hot","feeling"],["hot","blanket","sun","cozy","coat","hug"]],
  ["cozy","cozy","douillet",["home","feeling"],["blanket","warm","bed","home","hot_chocolate","pajamas"]],
  ["jungle","jungle","jungle",["nature","animal","adventure"],["monkey","tiger","snake","parrot","tree","adventure","lion"]],
  ["desert","desert","désert",["nature","hot"],["sand","hot","camel","cactus","sun","snake"]],
  ["volcano","volcano","volcan",["nature","fire","science"],["lava","fire","mountain","hot","dinosaur","island"]],
  ["nest","nest","nid",["animal","nature"],["bird","egg","tree","feather","branch"]],
  ["wing","wing","aile",["animal","body"],["bird","fly","feather","butterfly","plane","angel","fairy","dragon"]],
  ["feather","feather","plume",["animal"],["bird","wing","pillow","soft","chicken","owl"]],
  ["fly","fly","voler",["sky"],["bird","wing","plane","sky","kite","rocket","superhero"]],
  ["bone","bone","os",["body","animal"],["dog","skeleton","dinosaur","fossil","halloween","body"]],
  ["camping","camping","camping",["nature","adventure"],["tent","fire","forest","marshmallow","sleeping_bag","hike","star"]],
  ["tent","tent","tente",["adventure","nature"],["camping","circus","sleeping_bag","forest","hike"]],

  // Describing words
  ["soft","soft","doux",["feeling"],["pillow","blanket","fur","teddy_bear","feather","cloud","kitten","cozy"]],
  ["cute","cute","mignon",["feeling","animal"],["puppy","kitten","baby","panda","rabbit","hamster","teddy_bear"]],
  ["big","big","grand",["shape"],["elephant","whale","giant","small","dinosaur","bear","mountain"]],
  ["small","small","petit",["shape"],["ant","mouse","baby","big","seed","ladybug","hamster"]],
  ["fast","fast","rapide",["sport","transport"],["race","car","run","rocket","cheetah","slow","train"]],
  ["slow","slow","lent",["animal"],["snail","turtle","fast","walk","sleep"]],
  ["loud","loud","bruyant",["sound"],["drum","thunder","roar","quiet","music"]],
  ["quiet","quiet","calme",["sound","feeling"],["library","sleep","loud","mouse","night"]],
  ["bright","bright","brillant",["light"],["sun","light","star","lightning","shine","sparkle"]],
  ["wet","wet","mouillé",["water"],["rain","water","puddle","swim","towel"]],
  ["wild","wild","sauvage",["animal","nature"],["lion","tiger","wolf","jungle","forest","animal"]],
  ["funny","funny","drôle",["feeling"],["laugh","clown","monkey","smile"]],
  ["brave","brave","courageux",["feeling","adventure"],["knight","hero","firefighter","fear","lion","superhero"]],
  ["strong","strong","fort",["body","sport"],["superhero","lion","bear","elephant","brave"]],
  ["old","old","vieux",["time"],["grandma","grandpa","castle","dinosaur","fossil","new"]],
  ["new","new","nouveau",["time"],["old","gift","baby","year","birthday","toy"]],
  ["round","round","rond",["shape"],["ball","circle","moon","planet","wheel","earth"]],
  ["tired","tired","fatigué",["feeling","night"],["sleep","bed","night","pillow","bedtime"]],
  ["angry","angry","en colère",["feeling"],["sad","red","happy","storm"]],
  ["hungry","hungry","faim",["food","feeling"],["food","eat","lunch","dinner","breakfast","snack"]],

  // Activities
  ["jump","jump","sauter",["sport","game"],["frog","kangaroo","rabbit","puddle","trampoline","dance"]],
  ["run","run","courir",["sport"],["race","fast","shoe","foot","soccer","walk"]],
  ["walk","walk","marcher",["sport"],["foot","dog","park","hike","shoe","run"]],
  ["climb","climb","grimper",["sport","adventure"],["tree","mountain","monkey","rock"]],
  ["ride","ride","balade",["transport"],["horse","bike","pony","car","train","skateboard"]],
  ["eat","eat","manger",["food"],["food","hungry","lunch","dinner","plate","spoon","fork"]],
  ["help","help","aider",["feeling","job"],["friend","firefighter","doctor","police","share","nurse"]],
  ["share","share","partager",["feeling"],["friend","toy","help","cookie","love"]],
  ["hide","hide","cacher",["game"],["hide_and_seek","closet","cave","game","play","dark"]],
  ["hide_and_seek","hide-and-seek","cache-cache",["game"],["hide","game","play","count","friend"]],
  ["explore","explore","explorer",["adventure"],["adventure","map","jungle","cave","space","treasure"]],
  ["travel","travel","voyage",["transport","adventure","holiday"],["plane","train","holiday","suitcase","map","car","boat"]],
  ["hike","hike","randonnée",["sport","nature","adventure"],["mountain","forest","walk","backpack","camping","boots"]],
  ["ski","ski","ski",["sport","cold"],["snow","mountain","winter","sled","cold"]],
  ["sled","sled","luge",["sport","cold"],["snow","winter","hill","ski","snowman"]],
  ["skate","skate","patin",["sport","cold"],["ice","winter","skateboard","cold","snow"]],
  ["race","race","course",["sport"],["run","fast","car","win","medal","bike"]],
  ["dive","dive","plonger",["water","sport"],["pool","swim","ocean","dolphin","submarine"]],
  ["surf","surf","surf",["sport","ocean"],["wave","beach","sea","summer","ocean"]],
  ["roar","roar","rugir",["sound","animal"],["lion","tiger","dinosaur","dragon","loud","bear"]],
  ["shine","shine","briller",["light"],["sun","star","light","bright","sparkle","gold"]],
  ["sparkle","sparkle","paillettes",["light","magic"],["magic","unicorn","fairy","star","shine","jewel"]],
  ["count","count","compter",["school"],["number","math","hide_and_seek","finger","school"]],
  ["throw","throw","lancer",["sport"],["ball","catch","basketball","rock"]],
  ["catch","catch","attraper",["sport","game"],["ball","throw","fish","play","game"]],

  // Places
  ["city","city","ville",["city"],["car","bus","park","shop","museum"]],
  ["road","road","route",["city","transport"],["car","bus","truck","bike","bridge"]],
  ["bridge","bridge","pont",["city","water"],["river","road","train","car","water"]],
  ["shop","shop","magasin",["city"],["money","toy","city","bakery"]],
  ["money","money","argent",["city"],["shop","gold","treasure","bakery","pirate","baker"]],
  ["bakery","bakery","boulangerie",["food","city"],["bread","cake","baker","croissant","shop","oven"]],
  ["baker","baker","boulanger",["job","food"],["bakery","bread","cake","oven","bake","croissant"]],
  ["croissant","croissant","croissant",["food"],["bakery","breakfast","butter","bread","baker"]],
  ["restaurant","restaurant","restaurant",["food","city"],["chef","food","dinner","pizza","burger"]],
  ["museum","museum","musée",["city","art","science"],["dinosaur","art","painting","fossil"]],
  ["hospital","hospital","hôpital",["city","job","body"],["doctor","nurse","sick","ambulance","medicine"]],
  ["airport","airport","aéroport",["transport","city"],["plane","pilot","suitcase","travel","helicopter"]],
  ["station","station","gare",["transport","city"],["train","travel","bus","city","suitcase"]],
  ["playground","playground","aire de jeux",["game","city"],["swing","slide","park","play","school"]],
  ["swing","swing","balançoire",["game","toy"],["playground","park","slide","play","tree"]],
  ["slide","slide","toboggan",["game","toy"],["playground","park","swing","play","pool"]],
  ["cave","cave","grotte",["nature","adventure"],["bat","bear","dragon","dark","rock","explore"]],
  ["hill","hill","colline",["nature"],["mountain","sled","grass","climb","field"]],
  ["rock","rock","rocher",["nature"],["stone","mountain","cave","climb","volcano"]],
  ["stone","stone","caillou",["nature"],["rock","river","throw","beach","castle"]],
  ["field","field","champ",["farm","nature"],["farm","grass","tractor","flower","cow","soccer"]],
  ["world","world","monde",["nature","space"],["earth","map","travel","planet","nature"]],

  // Home and everyday objects
  ["bedroom","bedroom","chambre",["home","night"],["bed","toy","sleep","closet","pillow"]],
  ["bath","bath","bain",["home","water"],["bubble","soap","towel","duck","water","clean"]],
  ["bubble","bubble","bulle",["water","toy"],["bath","soap","water","balloon","swim","fish"]],
  ["soap","soap","savon",["home","water"],["bath","bubble","clean","hand","towel"]],
  ["clean","clean","propre",["home"],["soap","bath","broom","dirty","towel","toothbrush"]],
  ["dirty","dirty","sale",["home"],["mud","clean","pig","sock","clothes"]],
  ["towel","towel","serviette",["home","ocean"],["bath","beach","wet","swim","soap"]],
  ["toothbrush","toothbrush","brosse à dents",["home","body"],["tooth","smile","dentist","bath","morning"]],
  ["key","key","clé",["home"],["door","home","car","treasure","castle","closet"]],
  ["roof","roof","toit",["home"],["home","rain","chimney","cat"]],
  ["chimney","chimney","cheminée",["home","fire"],["santa","fire","roof","christmas","home","wood"]],
  ["table","table","table",["home"],["chair","plate","dinner","kitchen","eat"]],
  ["chair","chair","chaise",["home","school"],["table","desk","sofa","kitchen","class"]],
  ["sofa","sofa","canapé",["home"],["tv","cozy","pillow","chair","blanket"]],
  ["tv","tv","télé",["tech","home"],["cartoon","movie","sofa","screen"]],
  ["lamp","lamp","lampe",["light","home"],["light","bright","dark","bed","flashlight"]],
  ["flashlight","flashlight","lampe torche",["light","adventure"],["dark","light","camping","battery","night"]],
  ["fridge","fridge","frigo",["home","cold","food"],["kitchen","cold","milk","ice","food"]],
  ["plate","plate","assiette",["food","home"],["fork","spoon","food","table","dinner"]],
  ["spoon","spoon","cuillère",["food","home"],["fork","soup","plate","eat"]],
  ["fork","fork","fourchette",["food","home"],["spoon","plate","eat","table","dinner","pasta","kitchen"]],
  ["cup","cup","tasse",["drink","home"],["tea","hot_chocolate","drink","coffee","glass"]],
  ["glass","glass","verre",["drink","home"],["water","milk","juice","drink","window","cup"]],
  ["box","box","boîte",["home"],["gift","toy","surprise","suitcase","blocks"]],
  ["suitcase","suitcase","valise",["transport","holiday"],["travel","holiday","plane","airport","clothes"]],
  ["basket","basket","panier",["food"],["picnic","easter","egg","fruit","shop"]],
  ["closet","closet","placard",["home","clothes"],["clothes","bedroom","hide","monster","door"]],
  ["broom","broom","balai",["home","magic"],["witch","clean","fly","halloween","home","kitchen"]],
  ["scissors","scissors","ciseaux",["school","art"],["paper","hair","art","school","draw"]],
  ["desk","desk","bureau",["school","home"],["chair","school","pencil","class","computer"]],
  ["number","number","nombre",["school"],["math","count","clock","phone","year"]],
  ["alphabet","alphabet","alphabet",["school","book"],["letter","word","read","school","song"]],

  // Body
  ["arm","arm","bras",["body"],["hand","hug","leg","body"]],
  ["leg","leg","jambe",["body"],["foot","arm","run","walk","body"]],
  ["finger","finger","doigt",["body"],["hand","count","ring","glove","paint","foot"]],
  ["mouth","mouth","bouche",["body"],["tooth","smile","kiss","eat","face"]],
  ["nose","nose","nez",["body"],["face","clown","eye","mouth","elephant"]],
  ["ear","ear","oreille",["body","sound"],["rabbit","music","head","elephant","face"]],
  ["hair","hair","cheveux",["body"],["head","beard","face","hat"]],
  ["beard","beard","barbe",["body"],["santa","grandpa","wizard","hair","face"]],
  ["brain","brain","cerveau",["body","science","school"],["head","puzzle","science","school"]],
  ["hurt","hurt","bobo",["body","feeling"],["cry","doctor","sick","nurse"]],
  ["sick","sick","malade",["body"],["doctor","medicine","hospital","nurse","bed"]],
  ["medicine","medicine","médicament",["body","job"],["doctor","sick","nurse","hospital","vet"]],
  ["skeleton","skeleton","squelette",["body","holiday"],["bone","halloween","scary","doctor"]],
  ["glasses","glasses","lunettes",["body","clothes"],["eye","read","grandpa","sun","face","teacher"]],

  // Clothes
  ["shirt","shirt","chemise",["clothes"],["clothes","pants","dress","sweater","jacket"]],
  ["pants","pants","pantalon",["clothes"],["shirt","clothes","leg","jacket","sock","shoe"]],
  ["jacket","jacket","veste",["clothes"],["coat","rain","clothes","winter"]],
  ["glove","glove","gant",["clothes","cold"],["hand","mitten","winter","finger","snow"]],
  ["helmet","helmet","casque",["clothes","sport"],["bike","astronaut","knight","firefighter","head"]],
  ["mask","mask","masque",["clothes","celebration"],["superhero","costume","halloween","face","party"]],
  ["swimsuit","swimsuit","maillot de bain",["clothes","water"],["swim","pool","beach","summer","towel"]],

  // Food
  ["breakfast","breakfast","petit déjeuner",["food","time"],["morning","cereal","egg","toast","juice","milk","pancake","croissant"]],
  ["lunch","lunch","déjeuner",["food","time"],["sandwich","school","food","picnic","eat"]],
  ["dinner","dinner","dîner",["food","time"],["food","family","table","plate","cook","night","soup"]],
  ["snack","snack","goûter",["food"],["cookie","apple","hungry"]],
  ["pie","pie","tarte",["food","sweet"],["apple","oven","pumpkin","bake","dessert","cherry"]],
  ["pancake","pancake","crêpe",["food","sweet"],["breakfast","sugar","butter","jam","honey","bake"]],
  ["jam","jam","confiture",["food","sweet"],["strawberry","bread","toast","pancake","sweet"]],
  ["toast","toast","tartine",["food"],["bread","butter","jam","breakfast","honey"]],
  ["butter","butter","beurre",["food"],["bread","toast","croissant","milk","pancake"]],
  ["cereal","cereal","céréales",["food"],["breakfast","milk","spoon","morning","corn"]],
  ["salad","salad","salade",["food","plant"],["vegetable","tomato","green","lunch","plate","dinner"]],
  ["potato","potato","pomme de terre",["food","plant"],["fries","vegetable","farm","soup","dinner","oven"]],
  ["fries","fries","frites",["food"],["potato","burger","restaurant","lunch","snack"]],
  ["burger","burger","hamburger",["food"],["fries","cheese","bread","dinner"]],
  ["pasta","pasta","pâtes",["food"],["cheese","tomato","dinner","spoon","pizza"]],
  ["cherry","cherry","cerise",["food","plant","sweet"],["red","fruit","pie","tree","cake"]],
  ["pear","pear","poire",["food","plant"],["fruit","tree","green","apple","juice","pie"]],
  ["watermelon","watermelon","pastèque",["food","plant"],["summer","fruit","green","red","picnic","seed"]],
  ["pineapple","pineapple","ananas",["food","plant"],["fruit","yellow","juice","island","pizza"]],
  ["corn","corn","maïs",["food","plant","farm"],["popcorn","farm","yellow","field","vegetable"]],
  ["popcorn","popcorn","pop-corn",["food"],["corn","movie","snack","cartoon","party"]],
  ["marshmallow","marshmallow","guimauve",["food","sweet"],["camping","fire","hot_chocolate","soft","candy"]],
  ["lemonade","lemonade","limonade",["drink","sweet"],["lemon","summer","drink","glass","sugar"]],
  ["coffee","coffee","café",["drink","hot"],["cup","morning","milk","hot","tea"]],
  ["chef","chef","chef cuisinier",["job","food"],["cook","kitchen","restaurant","hat","food"]],
  ["donut","donut","beignet",["food","sweet"],["sugar","sweet","bakery","round","breakfast"]],

  // Animals more
  ["kangaroo","kangaroo","kangourou",["animal"],["jump","zoo","baby","animal","run"]],
  ["cheetah","cheetah","guépard",["animal"],["fast","run","lion","jungle","zoo"]],
  ["squirrel","squirrel","écureuil",["animal","nature"],["tree","forest","tail","autumn","jump","climb"]],
  ["camel","camel","chameau",["animal","hot"],["desert","sand","hot","zoo","animal","palm_tree"]],
  ["crocodile","crocodile","crocodile",["animal","water"],["river","tooth","jungle","green","zoo"]],
  ["wool","wool","laine",["animal","clothes"],["sheep","scarf","sweater","soft","mitten","blanket"]],
  ["sweater","sweater","pull",["clothes","cold"],["wool","winter","warm","coat"]],
  ["goat","goat","chèvre",["animal","farm"],["farm","cheese","mountain","milk","animal","grass"]],
  ["hay","hay","foin",["farm"],["horse","cow","barn","farm","field","pony"]],
  ["barn","barn","grange",["farm"],["farm","hay","cow","horse","tractor"]],
  ["tractor","tractor","tracteur",["farm","transport"],["farm","farmer","field","barn","truck","wheel"]],
  ["farmer","farmer","fermier",["job","farm"],["farm","tractor","cow","field","barn"]],
  ["vet","vet","vétérinaire",["job","animal"],["pet","dog","cat","doctor","animal"]],
  ["aquarium","aquarium","aquarium",["water","pet"],["fish","water","glass","octopus","shark"]],
  ["jellyfish","jellyfish","méduse",["animal","ocean"],["sea","ocean","beach","octopus","swim","fish"]],
  ["polar_bear","polar bear","ours polaire",["animal","cold"],["bear","ice","snow","cold","penguin"]],
  ["eagle","eagle","aigle",["animal","sky"],["bird","fly","mountain","wing","feather"]],
  ["mud","mud","boue",["nature","water"],["pig","puddle","rain","dirty","boots"]],

  // Ocean, fantasy
  ["mermaid","mermaid","sirène",["magic","ocean","story"],["sea","ocean","fish","tail","shell","princess","island"]],
  ["starfish","starfish","étoile de mer",["animal","ocean"],["star","beach","sea","shell","sand"]],
  ["submarine","submarine","sous-marin",["transport","ocean"],["ocean","sea","dive","fish","whale"]],
  ["captain","captain","capitaine",["ocean","job"],["ship","pirate","boat","sea","team"]],
  ["palm_tree","palm tree","palmier",["plant","hot"],["island","beach","summer","sand","tree","hot"]],
  ["bucket","bucket","seau",["toy","ocean"],["sand","beach","water","sandcastle","swim"]],
  ["sword","sword","épée",["story","adventure"],["knight","pirate","shield","dragon","castle","treasure"]],
  ["shield","shield","bouclier",["story","adventure"],["knight","sword","castle","hero","prince"]],
  ["tower","tower","tour",["story","city"],["castle","princess","dragon"]],
  ["gold","gold","or",["color","adventure"],["treasure","money","crown","pirate","yellow","jewel","shine"]],
  ["jewel","jewel","bijou",["adventure"],["crown","treasure","gold","princess","ring"]],
  ["ring","ring","bague",["clothes"],["jewel","finger","gold","wedding","princess","queen"]],
  ["potion","potion","potion",["magic"],["witch","wizard","magic","cauldron","spell"]],
  ["cauldron","cauldron","chaudron",["magic"],["witch","potion","halloween","magic","wizard","soup"]],
  ["vampire","vampire","vampire",["story","holiday","night"],["bat","halloween","night","castle","scary"]],
  ["haunted_house","haunted house","maison hantée",["story","holiday"],["ghost","halloween","scary","skeleton","night"]],
  ["angel","angel","ange",["story","magic"],["wing","christmas","cloud","fairy","sky"]],
  ["giant","giant","géant",["story","magic"],["big","castle","tower","fairy_tale","dinosaur","whale"]],
  ["elf","elf","lutin",["magic","holiday"],["santa","christmas","toy","fairy","small"]],
  ["sleigh","sleigh","traîneau",["holiday","cold","transport"],["santa","reindeer","snow","christmas","sled"]],
  ["fairy_tale","fairy tale","conte",["story","book","magic"],["story","fairy","princess","book","wolf","castle"]],
  ["bedtime","bedtime","dodo",["night","home"],["bed","sleep","story","pajamas","night","teddy_bear"]],

  // Holidays and celebrations
  ["valentine","valentine","saint-valentin",["holiday","feeling"],["heart","love","red","flower","kiss"]],
  ["wedding","wedding","mariage",["celebration","family"],["dress","ring","cake","love","flower","dance"]],
  ["fireworks","fireworks","feu d'artifice",["celebration","light","night"],["sky","night","party","color","holiday","bright"]],
  ["year","year","année",["time"],["birthday","season","time"]],
  ["snowball","snowball","boule de neige",["cold","game","season"],["snow","throw","winter","snowman","cold","ice"]],

  // Music, art, shows
  ["violin","violin","violon",["music"],["music","song","piano","concert","band","stage"]],
  ["trumpet","trumpet","trompette",["music","sound"],["music","band","loud","concert","sing","song"]],
  ["flute","flute","flûte",["music"],["music","song","band","bird","piano","concert"]],
  ["concert","concert","concert",["music","celebration"],["music","band","sing","stage","guitar"]],
  ["stage","stage","scène",["music","art"],["concert","show","dance","sing","band","music"]],
  ["show","show","spectacle",["art","celebration"],["stage","circus","clown","dance","magic"]],
  ["radio","radio","radio",["music","tech","sound"],["music","song","car","tv","dance"]],
  ["movie","movie","film",["art","story"],["popcorn","tv","story","cartoon","show","stage"]],
  ["cartoon","cartoon","dessin animé",["art","story"],["tv","movie","funny","draw"]],
  ["artist","artist","artiste",["art","job"],["paint","draw","art","museum","painting"]],
  ["painting","painting","tableau",["art"],["paint","artist","museum","picture","color","draw"]],
  ["photo","photo","photo",["art","tech"],["picture","smile","family","art","birthday"]],

  // Shapes
  ["shape","shape","forme",["shape"],["circle","square","triangle","star","heart"]],
  ["circle","circle","cercle",["shape"],["round","ball","wheel","square","sun"]],
  ["square","square","carré",["shape"],["circle","triangle","box","window"]],
  ["triangle","triangle","triangle",["shape","music"],["square","circle","pizza","mountain"]],

  // Games, sport, toys more
  ["board_game","board game","jeu de société",["game","family"],["game","family","win","toy","play"]],
  ["video_game","video game","jeu vidéo",["game","tech"],["game","computer","tv","screen","win","tablet"]],
  ["blocks","blocks","cubes",["toy"],["toy","build","tower","square","play"]],
  ["build","build","construire",["toy","job"],["blocks","home","tower","sandcastle","builder"]],
  ["builder","builder","maçon",["job"],["build","home","helmet","truck","blocks"]],
  ["skateboard","skateboard","skate",["sport","toy"],["skate","wheel","ride","park","helmet"]],
  ["trampoline","trampoline","trampoline",["sport","toy"],["jump","garden","fun","play","sport","playground"]],
  ["basketball","basketball","basket",["sport"],["ball","team","throw","shoe","player"]],
  ["tennis","tennis","tennis",["sport"],["ball","player","win","team","run"]],
  ["player","player","joueur",["sport","game"],["team","game","soccer","basketball","win"]],
  ["goal","goal","but",["sport"],["soccer","ball","win","team","player","basketball"]],
  ["trophy","trophy","trophée",["sport"],["win","gold","medal","team","sport"]],
  ["medal","medal","médaille",["sport"],["win","gold","race","trophy","sport","team"]],
  ["sport","sport","sport",["sport"],["soccer","basketball","tennis","run","swim","team","ball"]],

  // Tech and science
  ["screen","screen","écran",["tech"],["computer","tv","phone","tablet","video_game"]],
  ["tablet","tablet","tablette",["tech"],["screen","computer","phone","video_game","game"]],
  ["battery","battery","pile",["tech","science"],["robot","flashlight","electricity","toy","phone","tablet"]],
  ["electricity","electricity","électricité",["tech","science"],["lightning","battery","lamp","light","computer","tv"]],
  ["science","science","science",["science","school"],["scientist","planet","dinosaur","volcano","space"]],
  ["scientist","scientist","scientifique",["science","job"],["science","robot","space","doctor","fossil","brain"]],
  ["fossil","fossil","fossile",["science","nature"],["dinosaur","bone","museum","rock"]],
  ["lava","lava","lave",["fire","nature","hot"],["volcano","fire","hot","red","rock"]],

  // Transport and jobs more
  ["truck","truck","camion",["transport"],["car","road","firefighter","build"]],
  ["wheel","wheel","roue",["transport","shape"],["car","bike","bus","round","circle"]],
  ["helicopter","helicopter","hélicoptère",["transport","sky"],["fly","plane","pilot","sky"]],
  ["pilot","pilot","pilote",["job","transport","sky"],["plane","helicopter","fly","airport","sky","astronaut"]],
  ["ambulance","ambulance","ambulance",["transport","job"],["hospital","doctor","nurse","sick"]],
  ["nurse","nurse","infirmière",["job","body"],["doctor","hospital","sick","medicine"]],
  ["dentist","dentist","dentiste",["job","body"],["tooth","doctor","smile","toothbrush","nurse","mouth"]],
  ["wood","wood","bois",["nature","fire"],["tree","fire","forest","branch","camping"]],
  ["branch","branch","branche",["nature","plant"],["tree","leaf","bird","nest","wood"]],
  ["sleeping_bag","sleeping bag","sac de couchage",["adventure","night"],["camping","tent","sleep","night","blanket","pillow"]],

  // Nature more
  ["nature","nature","nature",["nature"],["tree","forest","flower","animal","river","mountain"]],
  ["mushroom","mushroom","champignon",["nature","plant","food"],["forest","autumn","rain","fairy","garden","snail"]],
  ["cactus","cactus","cactus",["plant","hot"],["desert","hot","green","sand","plant","flower"]],
  ["waterfall","waterfall","cascade",["water","nature"],["river","water","mountain","rock","jungle"]],
  ["sunset","sunset","coucher de soleil",["sky","time","color"],["sun","sky","evening","orange","beach","night"]],
  ["evening","evening","soir",["time","night"],["night","dinner","sunset","bedtime","moon"]],
  ["grey","grey","gris",["color"],["cloud","elephant","rock","mouse","color","storm"]],
  ["weather","weather","météo",["weather"],["rain","sun","snow","cloud","wind","storm"]],
];
