// Extra everyday words a child might type, beyond the concept labels in
// data.js. They are not linked in the association graph; the speller treats
// them as known so it never "corrects" a real word.
export const EXTRA_WORDS = {
  en: [
    "above", "acorn", "across", "actor", "actress", "add", "afraid", "afternoon", "ago", "air", "airplane",
    "all", "alligator", "almost", "along", "alpaca", "also", "always", "am", "an", "anchor", "ancient", "and",
    "ankle", "answer", "anyone", "anything", "apartment", "apricot", "april", "apron", "are", "armchair",
    "armor", "around", "ask", "asked", "attic", "aubergine", "august", "aunt", "author", "avenue", "avocado",
    "away", "baa", "baboon", "back", "bacon", "bad", "badger", "badminton", "bag", "bagel", "balcony",
    "ballet", "balloons", "bamboo", "bandage", "bang", "bank", "bark", "baseball", "basement", "bathe",
    "bathroom", "bathtub", "be", "beak", "bean", "beanie", "beans", "beat", "beautiful", "beaver", "because",
    "beef", "been", "beep", "beet", "beetle", "begin", "behind", "beige", "being", "belly", "below", "belt",
    "bench", "berry", "beside", "best", "better", "between", "bicycle", "bigger", "biggest", "biscuit",
    "bison", "bite", "bitter", "blackberry", "blaze", "blender", "blink", "bloom", "blouse", "blueberry",
    "blunt", "board", "boil", "bones", "bonnet", "boom", "boot", "bored", "borrow", "bottle", "bottom",
    "boulder", "bounce", "bouquet", "bowl", "bowling", "boy", "bracelet", "brake", "break", "breeze", "bring",
    "broccoli", "broken", "brownie", "brunch", "brush", "bubbles", "buffalo", "bug", "building", "bull",
    "bumpy", "bun", "bunk", "bunny", "burn", "burrito", "bush", "but", "butcher", "button", "buy", "buzz",
    "bye", "cabbage", "cabinet", "cable", "calendar", "calf", "call", "calm", "came", "camera", "can",
    "canary", "candles", "canoe", "canvas", "canyon", "cap", "caramel", "card", "cards", "care", "carpet",
    "carry", "cart", "cashier", "cauliflower", "ceiling", "celebration", "celery", "cello", "centipede",
    "chalk", "chameleon", "charger", "chase", "chat", "cheek", "cheer", "cheerful", "chess", "chest", "chew",
    "chewing", "chewy", "chick", "child", "children", "chilly", "chimp", "chimpanzee", "chin", "chipmunk",
    "chirp", "chop", "church", "cinema", "clam", "clap", "classroom", "claw", "clay", "cleaner", "clear",
    "clementine", "cliff", "clinic", "close", "closed", "clouds", "cloudy", "cluck", "coach", "coast",
    "cocoa", "coconut", "coin", "collar", "college", "colour", "comb", "come", "comet", "compass", "cone",
    "conifer", "cool", "copy", "coral", "corner", "couch", "country", "courgette", "cousin", "coyote",
    "cracker", "crackle", "cradle", "cranberry", "crash", "crawl", "crayon", "crayons", "cream", "creamy",
    "creek", "crib", "cricket", "crimson", "croak", "crossing", "crow", "crunchy", "crying", "cucumber",
    "cupboard", "cupcake", "curious", "curtain", "curtains", "custard", "cut", "cycling", "daddy", "daffodil",
    "daisy", "damp", "dancer", "dancing", "dandelion", "date", "daughter", "dawn", "december", "deep", "deer",
    "delicious", "deliver", "dice", "did", "different", "dig", "dim", "ding", "dino", "dirt", "discover",
    "do", "does", "dolly", "done", "dong", "donkey", "dotted", "dove", "down", "dozen", "dragonfly", "drawer",
    "drawing", "drip", "drive", "driver", "drizzle", "drop", "drums", "dry", "duckling", "dull", "dumpling",
    "dusk", "dust", "dusty", "duvet", "dwarf", "each", "early", "earring", "earrings", "easel", "easy",
    "edge", "eggplant", "eight", "eighteen", "elbow", "eleven", "elk", "email", "empty", "emu", "end",
    "engine", "enormous", "enough", "every", "everybody", "everyone", "everything", "exam", "excited",
    "experiment", "eyebrow", "eyelash", "factory", "fake", "falcon", "false", "fan", "fancy", "far", "fat",
    "father", "faucet", "feast", "february", "feel", "fence", "fern", "ferry", "festival", "few", "fifteen",
    "fifty", "fig", "fill", "fin", "find", "finish", "fireman", "first", "fishing", "five", "fix", "fixed",
    "flag", "flamingo", "flash", "flat", "flicker", "float", "floor", "flour", "fluffy", "fog", "foggy",
    "fold", "follow", "football", "forehead", "forty", "found", "four", "fourteen", "freeze", "freezing",
    "fresh", "friday", "front", "frost", "frosting", "fry", "fudge", "full", "furry", "future", "fuzzy",
    "galaxy", "garage", "gardener", "garlic", "gate", "gave", "gecko", "genie", "gentle", "geography",
    "gerbil", "get", "gifts", "giggle", "girl", "give", "glacier", "glad", "glitter", "glittery", "glow",
    "glue", "go", "goblin", "goes", "goldfish", "golf", "gone", "good", "goodbye", "goose", "gorilla", "got",
    "grade", "grandfather", "grandmother", "grandparents", "granny", "grapefruit", "grasshopper", "gravy",
    "gray", "great", "greet", "grill", "ground", "growl", "grumpy", "guard", "guess", "guinea", "gum", "gym",
    "gymnastics", "had", "hail", "hairy", "half", "hall", "hallway", "ham", "harbor", "harbour", "hard",
    "hare", "harp", "has", "have", "hawk", "he", "healthy", "hear", "heater", "heavy", "hedge", "hedgehog",
    "heel", "hello", "hen", "her", "here", "hers", "hi", "high", "him", "hip", "hippo", "hippopotamus", "his",
    "hiss", "history", "hit", "hockey", "hold", "holidays", "hollow", "honk", "hoodie", "hoot", "hop", "hope",
    "horn", "hornet", "hotdog", "hour", "house", "how", "howl", "huge", "hum", "hummingbird", "hundred",
    "hurricane", "hurry", "hyena", "icicle", "icing", "icy", "if", "iguana", "imagine", "in", "indigo", "ink",
    "inside", "internet", "into", "invite", "is", "it", "its", "ivy", "jaguar", "january", "jar", "jeans",
    "jelly", "jellybean", "jet", "join", "jolly", "judge", "judo", "jug", "juggle", "juicy", "july", "jumper",
    "jumprope", "june", "karate", "kayak", "keep", "kept", "ketchup", "kettle", "keyboard", "kick", "kid",
    "kids", "kind", "kiwi", "knee", "knew", "knife", "knit", "knock", "know", "knuckle", "koala", "ladder",
    "ladybird", "lamb", "land", "lane", "laptop", "large", "lasagna", "last", "late", "lavender", "lay",
    "lead", "leak", "learn", "leash", "least", "leaves", "left", "leggings", "lemur", "lend", "leopard",
    "less", "lesson", "let", "lettuce", "librarian", "lick", "licorice", "lid", "lie", "lifeguard", "lift",
    "lightbulb", "like", "lily", "lime", "lip", "lips", "listen", "little", "living", "lizard", "llama",
    "lobster", "lock", "lonely", "long", "look", "lorry", "lose", "lots", "lovely", "low", "lunchbox",
    "lungs", "lynx", "macaroni", "machine", "mad", "made", "magical", "magnet", "mail", "make", "mall",
    "mama", "man", "mango", "many", "maple", "marble", "marbles", "march", "margarine", "marker", "market",
    "marsh", "maths", "mattress", "may", "maybe", "mayonnaise", "me", "meal", "mean", "measure", "meat",
    "meatball", "mechanic", "meet", "melody", "melon", "melt", "men", "mend", "menu", "meow", "message",
    "messy", "metal", "meteor", "metro", "microphone", "microwave", "middle", "midnight", "milkshake",
    "million", "mine", "minute", "mirror", "mist", "mix", "modern", "mole", "moment", "mommy", "monday",
    "month", "moo", "moose", "mop", "more", "mosquito", "moss", "most", "moth", "mother", "motorbike",
    "motorcycle", "move", "mow", "muddy", "muffin", "mug", "mule", "mum", "mummy", "munch", "muscle",
    "mustard", "my", "myself", "nail", "nap", "napkin", "narrow", "navy", "near", "neat", "neck", "necklace",
    "nectarine", "need", "neigh", "neighbor", "neighbour", "nephew", "nervous", "never", "newt", "next",
    "nice", "niece", "nightlight", "nine", "nineteen", "no", "nobody", "nod", "noisy", "noodle", "noodles",
    "noon", "normal", "not", "note", "notebook", "notes", "nothing", "november", "now", "nugget", "nuggets",
    "nut", "oak", "oatmeal", "october", "odd", "off", "office", "officer", "often", "ogre", "oil", "oink",
    "ok", "okay", "olive", "on", "one", "onion", "only", "onto", "open", "or", "orangutan", "orbit", "orchid",
    "order", "ornament", "ostrich", "other", "otter", "our", "ours", "out", "outside", "over", "overalls",
    "ox", "oyster", "page", "paintbrush", "painter", "palace", "palm", "pan", "panther", "papa", "papaya",
    "parade", "parent", "parents", "past", "path", "pavement", "pay", "pea", "peach", "peacock", "peanut",
    "peas", "pebble", "peel", "pelican", "people", "pepper", "person", "petal", "pharmacy", "photograph",
    "pick", "pigeon", "piglet", "pine", "pinecone", "plain", "playtime", "please", "plenty", "plug", "plum",
    "plumber", "pocket", "poem", "point", "pointy", "policeman", "polite", "pomegranate", "pop", "poppy",
    "popsicle", "porch", "pork", "porridge", "port", "post", "pot", "pour", "power", "prawn", "present",
    "presents", "press", "pretend", "pretty", "printer", "prize", "protect", "proud", "pudding", "pull",
    "pupil", "purr", "purse", "push", "put", "quack", "quick", "quilt", "quite", "quiz", "raccoon", "racing",
    "radiator", "radish", "raft", "raincoat", "raindrop", "rainy", "raisin", "rake", "ram", "raspberry",
    "rat", "raven", "real", "really", "receive", "recess", "recipe", "recorder", "referee", "rent", "reply",
    "rescue", "rest", "rhino", "rhinoceros", "rhythm", "ribbon", "rice", "right", "rinse", "roast", "robin",
    "roll", "rollerskate", "room", "rooster", "root", "rope", "rose", "rough", "rubber", "rude", "rug",
    "rugby", "ruler", "running", "rush", "said", "sail", "sailboat", "sailor", "salmon", "salt", "salty",
    "same", "sandals", "sandbox", "saturday", "sauce", "sausage", "save", "saw", "saxophone", "say", "scared",
    "schoolbag", "scooter", "scorpion", "scream", "scrub", "sculpture", "seagull", "seahorse", "seal",
    "search", "seat", "seatbelt", "seaweed", "second", "see", "seek", "seen", "seesaw", "sell", "send",
    "sentence", "september", "serious", "set", "seven", "seventeen", "sew", "shadow", "shake", "shallow",
    "shampoo", "sharp", "sharpener", "she", "sheet", "shelf", "shiny", "shore", "short", "shorts", "shoulder",
    "shout", "shovel", "shower", "shrimp", "shrub", "shut", "shy", "side", "sidewalk", "sign", "silent",
    "silly", "silver", "simple", "singer", "sink", "sip", "sit", "six", "sixteen", "skating", "skiing",
    "skin", "skinny", "skip", "skirt", "skunk", "sleepy", "sleet", "sleeve", "slice", "slippers", "sloth",
    "slug", "smaller", "smallest", "smell", "smoke", "smooth", "smoothie", "snap", "sneakers", "sneeze",
    "snore", "snowy", "so", "sob", "soda", "soil", "solid", "solve", "some", "somebody", "someone",
    "something", "sometimes", "son", "songs", "soon", "sorbet", "sorry", "sour", "spaghetti", "sparkly",
    "sparrow", "speak", "special", "spend", "spicy", "spill", "spin", "spinach", "splash", "spots", "spotted",
    "spread", "sprinkles", "sprout", "squash", "squeak", "squeeze", "squid", "stadium", "staircase", "stairs",
    "stand", "stars", "start", "statue", "steak", "stegosaurus", "stem", "sticker", "stickers", "sticky",
    "sting", "stir", "stomach", "stool", "stop", "store", "stormy", "stove", "strange", "straw", "stream",
    "street", "stretch", "striped", "stripes", "study", "subtract", "subway", "sunday", "sunny", "sunrise",
    "sunshine", "supermarket", "supper", "surfing", "surprised", "sushi", "swallow", "swamp", "swan", "sweep",
    "sweets", "swimming", "switch", "syrup", "taco", "tadpole", "tag", "take", "talk", "tall", "tambourine",
    "tangerine", "tap", "tape", "taste", "tasty", "taxi", "teach", "tear", "teddy", "teeth", "telephone",
    "television", "tell", "temple", "ten", "test", "than", "thank", "thanks", "thanksgiving", "that", "thaw",
    "the", "theater", "theatre", "their", "theirs", "them", "then", "there", "these", "they", "thick",
    "thief", "thin", "think", "third", "thirsty", "thirteen", "thirty", "this", "thorn", "those", "thought",
    "thousand", "three", "throne", "through", "thumb", "thursday", "tick", "ticket", "tickle", "tidy", "tie",
    "tights", "tin", "tiny", "toad", "toaster", "tock", "today", "toe", "toes", "toffee", "toilet", "told",
    "tomorrow", "tongue", "tonight", "too", "took", "toothpaste", "top", "tornado", "tortoise", "toucan",
    "touch", "toward", "town", "toys", "trace", "track", "traffic", "trainers", "tram", "tray", "treat",
    "trex", "triceratops", "tricky", "troll", "trombone", "trousers", "true", "trunk", "try", "tshirt",
    "tuesday", "tulip", "tummy", "tuna", "tune", "tunnel", "turkey", "turn", "turquoise", "tweet", "twelve",
    "twenty", "twig", "twin", "twinkle", "twins", "two", "ugly", "uncle", "under", "uniform", "universe",
    "university", "unlock", "untie", "up", "upset", "us", "use", "usually", "vacation", "valley", "van",
    "vanilla", "very", "vest", "video", "village", "villain", "vine", "vinegar", "violet", "visit", "voice",
    "volleyball", "waffle", "wagon", "waiter", "waitress", "wake", "wall", "wallaby", "wallet", "walrus",
    "want", "was", "wash", "wasp", "watch", "we", "web", "wednesday", "weed", "week", "weekend", "weird",
    "well", "went", "were", "what", "when", "where", "which", "whiskers", "whisper", "whistle", "who", "whom",
    "why", "wide", "wiggle", "willow", "windy", "wink", "wipe", "woman", "women", "wonder", "woodpecker",
    "work", "worm", "worried", "worse", "worst", "wrap", "wrist", "writer", "xylophone", "yacht", "yawn",
    "yell", "yes", "yesterday", "yogurt", "you", "young", "your", "yours", "yourself", "yoyo", "yummy",
    "zero", "zip", "zipper", "zucchini"
  ],
  fr: [
    "aboyer", "abricot", "acheter", "acide", "acteur", "actrice", "adorer", "affamé", "agneau", "ail",
    "aimant", "aimer", "air", "ajouter", "algue", "aller", "alligator", "alors", "alpaga", "amer", "amère",
    "ampoule", "ancien", "ancienne", "ancre", "âne", "août", "appareil", "appartement", "appeler",
    "applaudir", "apporter", "apprendre", "appuyer", "après-midi", "argenté", "argile", "armure", "arrêter",
    "arroser", "asseoir", "assez", "assoiffé", "attacher", "au", "aube", "aubergine", "aujourd'hui", "aussi",
    "auteur", "autocollant", "autour", "autre", "autruche", "aux", "avaler", "averse", "avocat", "avoir",
    "avril", "babouin", "bac", "badminton", "baguette", "baie", "baigner", "baignoire", "bâiller", "balancer",
    "balayer", "balcon", "balle", "ballet", "ballons", "bambou", "banc", "banque", "barrière", "bas",
    "baseball", "basketball", "baskets", "basse", "batterie", "bavarder", "beau", "beaucoup", "bec", "beige",
    "bêler", "bélier", "belle", "berceau", "bête", "betterave", "bibliothécaire", "biche", "bicyclette",
    "bidon", "bientôt", "billes", "bison", "bizarre", "blaireau", "blanche", "bleue", "bob", "bocal", "bœuf",
    "bol", "bon", "bonjour", "bonne", "bonnet", "bonsoir", "bord", "boucherie", "boucle", "boueux", "bouger",
    "bougies", "bouillir", "bouilloire", "boulette", "boum", "bouquet", "bourdonner", "boussole", "bouteille",
    "boutique", "bouton", "boutonner", "bowling", "bracelet", "brillante", "brillants", "brindille",
    "brioche", "brise", "brocoli", "brosse", "brosser", "brouillard", "brûler", "brume", "bruyante",
    "buisson", "bulles", "câble", "cadeaux", "cadenas", "cahier", "caissier", "calendrier", "calmar",
    "caméléon", "camionnette", "canari", "caneton", "canoë", "cantine", "caqueter", "car", "carafe",
    "caramel", "carnaval", "carrée", "cartes", "casquette", "cassé", "cassée", "casser", "casserole",
    "cassis", "castor", "cave", "ce", "ceinture", "célébration", "céleri", "cent", "cerf", "ces", "cet",
    "cette", "chacun", "chansons", "chanteur", "chanteuse", "chaque", "chargeur", "chariot", "charrette",
    "chatouiller", "chaude", "chauffeur", "chaussons", "chemin", "chêne", "chercher", "chevalet", "cheville",
    "chewing-gum", "chimpanzé", "chose", "chou", "chou-fleur", "chouette", "chuchoter", "cil", "cinéma",
    "cinq", "cinquante", "clair", "claire", "clavier", "clémentine", "cligner", "clignoter", "coasser",
    "coffre", "coin", "col", "colibri", "collant", "colle", "collège", "coller", "collier", "colombe",
    "colorier", "comète", "commander", "commencer", "comment", "concombre", "conduire", "contrôle", "copier",
    "coq", "coquelicot", "corail", "corbeau", "corde", "cornet", "côté", "cou", "coucher", "coude", "coudre",
    "couette", "couiner", "couler", "couloir", "couper", "courageuse", "courgette", "court", "courte",
    "cousin", "cousine", "couteau", "couvercle", "coyote", "crac", "craie", "crapaud", "cravate", "crème",
    "crémeux", "creuser", "crevette", "crier", "croire", "croquant", "croquer", "croustillant", "cueillir",
    "cuire", "cuisinier", "cuisinière", "cupcake", "curieuse", "curieux", "cygne", "dans", "danseur",
    "danseuse", "datte", "de", "décembre", "décoration", "découvrir", "dedans", "défilé", "dégeler", "dehors",
    "délicieuse", "délicieux", "demain", "demander", "dentifrice", "dents", "dépêcher", "dépenser", "dernier",
    "dernière", "derrière", "des", "dessin", "dessous", "dessus", "deux", "deuxième", "devant", "deviner",
    "devoir", "difficile", "dimanche", "dinde", "dindon", "dire", "dix", "donc", "donner", "doré", "dorée",
    "dos", "douce", "douche", "doucher", "doudou", "douzaine", "douze", "drap", "drapeau", "droite",
    "dromadaire", "du", "duveteux", "échecs", "échelle", "éclabousser", "éclater", "écorce", "écouter",
    "écrivain", "effrayé", "effrayée", "église", "élan", "elle", "elles", "emballer", "embrasser",
    "emprunter", "encourager", "encre", "enfant", "enfants", "ennuyé", "énorme", "enseigner", "ensoleillé",
    "entendre", "entraîneur", "entre", "envoyer", "épais", "épaisse", "épaule", "épeler", "épinard", "épine",
    "éplucher", "érable", "escalier", "espérer", "essayer", "essuyer", "et", "étagère", "éternuer",
    "étinceler", "étirer", "étoiles", "étrange", "être", "étroit", "étudier", "évier", "excité", "excitée",
    "expérience", "fâché", "fâchée", "facile", "faire", "falaise", "farine", "fatiguée", "faucon", "fausse",
    "fauteuil", "faux", "femme", "fermée", "fermer", "fermeture", "ferry", "festin", "feuilles", "feutre",
    "feux", "février", "fier", "fière", "figue", "fille", "fils", "finir", "flamant", "fleurir", "flotter",
    "fondre", "football", "fougère", "fraîche", "frais", "framboise", "frapper", "frein", "frelon", "frire",
    "froide", "front", "frotter", "fumée", "furieux", "futur", "galaxie", "garage", "garçon", "garder",
    "gauche", "gaufre", "gazouiller", "gecko", "gelée", "geler", "génie", "genou", "gens", "gentil",
    "gentille", "géographie", "gerbille", "germer", "gigantesque", "gilet", "givre", "glaçage", "glacée",
    "glacier", "gland", "glisser", "gobelin", "golf", "gorille", "goutte", "goutter", "grand-mère",
    "grand-père", "grande", "grands-parents", "grêle", "grenade", "grenier", "griffe", "grignoter",
    "grille-pain", "griller", "grillon", "grise", "grogner", "grognon", "gros", "groseille", "grosse",
    "guêpe", "gym", "gymnastique", "haie", "hanche", "haricot", "harpe", "haut", "haute", "hennir",
    "hérisson", "heure", "heureuse", "heureux", "hier", "hippocampe", "hippopotame", "hockey", "homard",
    "homme", "huile", "huit", "huître", "hululer", "humide", "hurler", "hyène", "iguane", "il", "ils",
    "imaginer", "immense", "immeuble", "imperméable", "impoli", "imprimante", "infirmier", "inquiet",
    "inquiète", "internet", "interrupteur", "inviter", "jaguar", "jamais", "jambon", "janvier", "jardinier",
    "je", "jean", "jeudi", "jeune", "joli", "jolie", "jongler", "jonquille", "joue", "jouets", "joyeuse",
    "joyeux", "judo", "juge", "juillet", "juin", "jumeau", "jumeaux", "jumelle", "jupe", "juteux", "karaté",
    "kayak", "ketchup", "kiwi", "klaxon", "klaxonner", "koala", "la", "laisse", "laisser", "laitue", "lama",
    "langue", "lapinou", "large", "larme", "lasagnes", "lavande", "laver", "laveur", "le", "lécher", "leçon",
    "léger", "légère", "lémurien", "lente", "léopard", "les", "leur", "leurs", "lever", "lèvre", "lèvres",
    "lézard", "libellule", "lierre", "lièvre", "limace", "lisse", "loin", "long", "longue", "lourd", "lourde",
    "loutre", "lundi", "lycée", "lynx", "lys", "ma", "macaronis", "mâcher", "machine", "magicien", "magique",
    "magnifique", "mai", "maintenant", "maître", "manche", "manchot", "mandarine", "mangue", "marais",
    "marché", "mardi", "marguerite", "marin", "mars", "matelas", "mauvais", "mauvaise", "mayonnaise", "me",
    "mécanicien", "méchant", "méchante", "médecin", "meilleur", "meilleure", "mélanger", "mélodie", "melon",
    "même", "menton", "menu", "merci", "mercredi", "mère", "mes", "message", "mesurer", "métal", "météore",
    "métro", "mettre", "meugler", "miam", "miauler", "micro", "micro-ondes", "midi", "mignonne", "milieu",
    "milkshake", "mille", "mille-pattes", "million", "mince", "minuit", "minuscule", "minute", "miroir",
    "mixeur", "moche", "modeler", "moderne", "moi", "moineau", "moins", "mois", "moitié", "moment", "momie",
    "mon", "montre", "montrer", "mordre", "morse", "moteur", "moto", "mouche", "mouette", "mouillée",
    "mousse", "moustaches", "moustique", "moutarde", "muffin", "mulet", "mur", "mûre", "muscle", "myrtille",
    "nageoire", "nain", "natation", "neigeux", "nettoyer", "neuf", "neuve", "neveu", "nièce", "noire",
    "noisette", "noix", "non", "normal", "nos", "note", "notre", "nouilles", "nous", "nouvelle", "novembre",
    "nuages", "nuageux", "octobre", "ogre", "oie", "oignon", "olive", "ombre", "on", "oncle", "ongle", "onze",
    "orageux", "orang-outan", "orchidée", "orteil", "ou", "oui", "ouragan", "ouvert", "ouverte", "ouvrir",
    "page", "paille", "pailleté", "palais", "palourde", "pamplemousse", "panneau", "pansement", "panthère",
    "paon", "pardon", "parent", "parents", "paresseux", "parfois", "parler", "passé", "pâte", "patinage",
    "payer", "pays", "peau", "pêche", "peigne", "peigner", "peindre", "peintre", "pélican", "pelle", "penser",
    "perdre", "père", "personne", "pétale", "petite", "peu", "peut-être", "pharmacie", "phoque", "phrase",
    "pic", "pièce", "pierre", "pigeon", "pin", "pinceau", "piquant", "piqûre", "pissenlit", "place",
    "plafond", "planter", "plat", "plate", "plateau", "plein", "pleine", "pleurs", "plier", "plombier",
    "plouf", "plus", "plusieurs", "pluvieux", "poche", "poêle", "poème", "poignet", "poilu", "pointu",
    "pointue", "pois", "poitrine", "poivre", "poivron", "poli", "policier", "pop", "porc", "porcelet", "port",
    "portable", "portefeuille", "porter", "poste", "poster", "pouce", "poulet", "poumon", "pourquoi",
    "poursuivre", "poussière", "poussiéreux", "poussin", "pouvoir", "premier", "première", "prendre", "près",
    "presque", "prêter", "prise", "prix", "professeur", "profond", "profonde", "protéger", "prune", "pudding",
    "quand", "quarante", "quatorze", "quatre", "que", "quel", "quelle", "quelque", "qui", "quinze", "quoi",
    "racine", "radeau", "radiateur", "radis", "rails", "ramper", "ranger", "rat", "raton", "raviolis", "rayé",
    "rayée", "rayures", "rebondir", "recette", "recevoir", "récréation", "regarder", "règle", "réglisse",
    "remplir", "rencontrer", "renverser", "réparer", "repas", "répondre", "reposer", "résoudre", "réveil",
    "réveiller", "rêver", "rhinocéros", "rideau", "rien", "rigolo", "rigolote", "rincer", "rivage", "riz",
    "robinet", "ronde", "ronfler", "ronronner", "rouge-gorge", "rouler", "ruban", "rue", "rugby", "rugueux",
    "ruisseau", "rythme", "sa", "sac", "salée", "salon", "salopette", "saluer", "salut", "samedi", "sandales",
    "santé", "sapin", "sauce", "saucisse", "saule", "saumon", "sauterelle", "sautiller", "sauver", "savoir",
    "saxophone", "scarabée", "sciences", "scintiller", "scorpion", "scotch", "sculpture", "sec", "sèche",
    "sécher", "seconde", "secouer", "seize", "sel", "semaine", "sentir", "sept", "septembre", "sérieux",
    "serrer", "serveur", "serveuse", "ses", "seul", "seule", "seulement", "shampoing", "shooter", "short",
    "si", "siège", "siffler", "sifflet", "silencieux", "simple", "sirop", "six", "soixante", "sol", "son",
    "sonner", "sorbet", "sort", "soulever", "sourcil", "sous", "souvent", "spaghettis", "spécial", "stade",
    "statue", "steak", "sucrée", "suivre", "supermarché", "sur", "surpris", "sweat", "t-shirt", "ta",
    "tablier", "tabouret", "tac", "taches", "tacheté", "taille-crayon", "talon", "tambourin", "tante",
    "taper", "tapis", "tard", "tartiner", "taupe", "taureau", "taxi", "te", "télévision", "tenir", "terrasse",
    "tes", "têtard", "théâtre", "thon", "tic", "ticket", "tige", "timide", "tirelire", "tirer", "tiroir",
    "toi", "toile", "tomber", "ton", "tornade", "tôt", "toucan", "toucher", "toujours", "toupie", "tourner",
    "tourniquet", "tous", "tout", "toute", "toutes", "tramway", "tranquille", "travailler", "travers",
    "treize", "trente", "très", "tricératops", "tricoter", "trois", "troisième", "troll", "trombone",
    "trompe", "tronc", "trône", "trop", "trottinette", "trottoir", "trousse", "trouver", "tu", "tulipe",
    "tunnel", "turquoise", "tyrannosaure", "un", "une", "uniforme", "univers", "université", "usine",
    "utiliser", "vallée", "vanille", "veau", "veilleuse", "vendre", "vendredi", "venir", "venteux",
    "ventilateur", "ventre", "ver", "vermicelles", "vers", "verser", "verte", "viande", "vide", "vidéo",
    "vieil", "vieille", "village", "vinaigre", "vingt", "violette", "violoncelle", "visiter", "vite", "voile",
    "voilier", "voir", "voisin", "voisine", "voix", "voleur", "volley", "vos", "votre", "vouloir", "vous",
    "vrai", "vraie", "vraiment", "week-end", "xylophone", "yaourt", "zéro"
  ]
};
